// lib/blog-data.js
// Seed articles for the blog. Expand by appending entries; routes pick them up automatically.

export const POSTS = [
  {
    slug: 'how-to-pick-a-neighborhood-before-you-book',
    title: 'How to pick the right neighborhood before you book your hotel',
    excerpt: 'The single most important decision on any city trip is where you sleep. Here is how to choose well.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-04-06',
    tags: ['travel-tips', 'hotels', 'guide'],
    body: [
      "The single most important decision on any city trip is not which hotel you book — it is which neighborhood that hotel sits in. The difference between a wonderful weekend and a mediocre one is almost entirely geographical.",
      "The rule of thumb we follow at 50 Best Neighborhoods is simple: pick the neighborhood first, then pick the best hotel within it. Starting from the hotel end will always push you toward generic business districts, airport-adjacent blocks, or whatever the booking site's algorithm is promoting this week.",
      "So how do you choose? Three questions.",
      "**1. What do you actually want to do?** A foodie trip to Rome belongs in Testaccio, not Prati. A first-time museum-heavy Paris trip belongs in the Marais, not La Défense. Match the neighborhood's personality to the shape of your trip.",
      "**2. What is the 10-minute walk?** The best test of any neighborhood is what you can reach on foot in ten minutes from your hotel door. Coffee, dinner, a bookshop, a park, a bar: if all five are in that radius, you will have a great trip. If none of them are, the neighborhood is too quiet or too car-dependent.",
      "**3. Where do locals actually spend time?** Tourist neighborhoods empty out at night and on Sundays. Residential neighborhoods keep their soul. When in doubt, pick the one where local families walk their dogs on Sunday mornings — Trastevere over Prati, the Marais over the 16th, Prenzlauer Berg over Mitte.",
      "Our city guides are structured around this logic: each of the five neighborhoods we list for a city answers a different version of the above questions. Start there. Then book the hotel.",
    ],
  },
  {
    slug: 'the-neighborhood-brunch-rule',
    title: 'The Neighborhood Brunch Rule: a 60-second test for a great district',
    excerpt: 'There is one reliable shortcut for spotting the best neighborhood in any unfamiliar city. We call it the Brunch Rule.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-04-04',
    tags: ['travel-tips', 'food', 'guide'],
    body: [
      "Most people arrive in a new city on a Friday night and spend two days trying to figure out which neighborhood they should have booked instead. There is a faster way.",
      "We call it the Brunch Rule, and it works like this: on your first Sunday morning, walk the main street of your neighborhood at 11 AM. If every café has a queue of locals in workout clothes waiting for tables, you are in the right neighborhood. If every café is empty, or full of people taking photos of their avocado toast for Instagram, you are in the wrong one — move hotels.",
      "That sounds glib, but it is remarkably diagnostic. Queues of locals in workout clothes mean: this neighborhood has people who live here, who care about their Sunday routine, who have opinions about which café makes the best flat white. It means the district works as a place to live, not just a place to visit.",
      "Neighborhoods that pass the Brunch Rule around the world: Williamsburg, Brooklyn. Mile End, Montreal. Fitzroy, Melbourne. Vesterbro, Copenhagen. Kreuzberg, Berlin. Notting Hill, London. Condesa, Mexico City. Nørrebro, Copenhagen. Palermo Soho, Buenos Aires.",
      "Neighborhoods that fail: almost any central business district. Almost any stretch dominated by hotel chains. Almost any street where the shops close on Sundays. Beautiful but empty is the worst combination.",
      "Use the rule. Book better.",
    ],
  },
  {
    slug: 'five-underrated-cities',
    title: 'Five underrated cities with extraordinary neighborhoods',
    excerpt: 'Paris, Tokyo and London get the headlines. These five cities deserve far more attention than they get.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-04-02',
    tags: ['cities', 'underrated', 'guide'],
    body: [
      "Every 'world's best city' ranking looks roughly the same: Paris, Tokyo, London, New York, Barcelona, and a handful of usual suspects. They are all wonderful. They are also, in 2026, crowded, expensive, and — crucially — no longer surprising.",
      "Here are five cities we think are quietly hosting some of the most interesting neighborhoods in the world right now.",
      "**1. Tbilisi, Georgia.** Old Tbilisi's wooden balconies and sulphur baths, Sololaki's artistic quarter, Vera's riverside cafés — Tbilisi is the most atmospheric city in the Caucasus and still a fraction of the price of any European capital.",
      "**2. Porto, Portugal.** Lisbon is increasingly Lisbon-priced. Porto remains the quieter, grittier, more rewarding Portuguese city — especially Ribeira's UNESCO-listed riverfront and the emerging Cedofeita design quarter.",
      "**3. Bologna, Italy.** Florence and Venice get the tourists. Bologna gets the food. The porticoes of the centro storico, the food market in the Quadrilatero, the university-town energy — Bologna is the smartest Italian city for a food-focused weekend.",
      "**4. Ljubljana, Slovenia.** A capital the size of a large town. Metelkova's autonomous culture zone, Trnovo's riverside and the castle-hill old town make for one of Europe's most walkable city trips.",
      "**5. Tel Aviv, Israel.** Bauhaus boulevards, Neve Tzedek's stone alleys, the Florentin nightlife scene, and ancient Jaffa at the southern edge. Few cities combine beach, ancient history and contemporary design culture so elegantly.",
      "We have full neighborhood guides for each of these cities — use the city index to explore.",
    ],
  },
  {
    slug: 'why-we-synthesize-editorial-sources',
    title: 'Why our rankings synthesize editorial sources (and do not scrape them)',
    excerpt: 'A note on how we build our rankings, and why you will not find scraped article text on this site.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-30',
    tags: ['editorial', 'about'],
    body: [
      "Every neighborhood page on 50 Best Neighborhoods lists three editorial sources — Time Out, Condé Nast Traveler, The New York Times, The Guardian, local city press — where you can read more. We link to publication homepages and travel sections, but we do not scrape, mirror or republish their editorial content. That is deliberate.",
      "First, the legal point: scraping and republishing copyrighted editorial content is copyright infringement, full stop. Many travel aggregators have tried it and many have been forced to shut down or settle. We are not going to play that game.",
      "Second, the editorial point: a synthesis is more useful than a paste. A travel reader does not need to read fifteen 'Best Neighborhoods in London' articles in full — they need the short version that reconciles what the fifteen articles agree on and disagree about. That is what we are trying to provide.",
      "Third, the encyclopedic point: for factual context about each neighborhood — history, architecture, demographics, famous residents, cultural landmarks — we draw on Wikipedia, which is licensed under Creative Commons Attribution-ShareAlike 4.0. That license permits reuse with attribution, which we render on every neighborhood page and in the site footer.",
      "The result: original editorial rankings, plus factual encyclopedic context, plus attributed links to the best travel journalism. No scraping, no pasting, no copyright gray area. That is the deal.",
    ],
  },
  {
    slug: 'where-to-stay-for-nightlife-vs-sleep',
    title: 'Where to stay for nightlife — and where to stay if you like sleeping',
    excerpt: 'The two most common hotel mistakes in every major city, and how to avoid them.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-28',
    tags: ['travel-tips', 'hotels'],
    body: [
      "Two of the most common mistakes travelers make when picking a neighborhood are symmetrical. The first is booking far from the nightlife because 'it will be quieter' — and then spending 40 minutes and €25 in a taxi every time you want dinner. The second is booking in the middle of the nightlife district because 'we'll walk everywhere' — and then being kept awake until 4 AM by people throwing up in the street below your window.",
      "The sweet spot is almost always adjacent. One neighborhood over from the loudest district, within walking distance of the action but out of earshot of the worst of it. Examples:",
      "• In Berlin: stay in Kreuzberg or Friedrichshain, not on Oranienburger Straße.",
      "• In Lisbon: stay in Príncipe Real or Chiado, not in Bairro Alto itself.",
      "• In Buenos Aires: stay in Palermo Chico or Villa Crespo, not in Palermo Soho's loudest blocks.",
      "• In Bangkok: stay in Ari or Ekkamai, not on Sukhumvit Soi 11.",
      "• In Madrid: stay in Chueca or Malasaña (but not on the main drag), not in Sol.",
      "Our neighborhood pages note the nightlife character of each district explicitly — check the tagline before you book. 'Loud' districts have a tagline that tells you so.",
    ],
  },

  // ── New posts (20) ──
  {
    slug: 'the-walking-city-test',
    title: 'The Walking City Test: why a 30-minute walk tells you everything',
    excerpt: 'The single clearest test of whether a city is a great city is how far you can walk from your hotel without getting bored.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-25',
    tags: ['travel-tips', 'guide', 'walking'],
    body: [
      "The single clearest test of whether a city is a great city is how far you can walk from your hotel without getting bored. Half an hour is our standard. If you can walk for 30 minutes in any direction from a central hotel and still see interesting things every block, the city is great. If you hit a dead zone within five minutes, the city is badly planned or you are in the wrong neighborhood — usually both.",
      "Venice passes the Walking City Test everywhere. Paris does within the Périphérique. Barcelona does in Ciutat Vella and most of L'Eixample. Tokyo does almost absurdly well — its density of small, interesting shops is unmatched anywhere.",
      "Cities that fail the test: Los Angeles, almost anywhere. Houston, anywhere. Dubai outside a few walkable pockets. Most American cities, if you are honest about it — the ones with walkable downtowns (Boston, San Francisco, New York) are the exceptions that prove the rule.",
      "The implication for travelers is simple: prioritize dense, walkable historic centers over central business districts. A bad hotel in a great neighborhood beats a great hotel in a bad one, every single time.",
    ],
  },
  {
    slug: 'neighborhoods-for-solo-travelers',
    title: '15 neighborhoods that are particularly welcoming to solo travelers',
    excerpt: 'Some neighborhoods feel lonely when you travel alone. These fifteen feel like the opposite.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-22',
    tags: ['solo-travel', 'cities', 'guide'],
    body: [
      "Traveling alone changes what you want from a neighborhood. You need places where showing up alone at a bar is normal, where cafés don't treat solo diners like a problem, where you can walk safely at 11 PM, and where there is enough street life that you never feel like the only person out.",
      "Our shortlist of neighborhoods that do all of the above, in rough order of how easy they are for first-time solo travelers:",
      "**Europe:** Le Marais (Paris), Neubau (Vienna), Vesterbro (Copenhagen), Kreuzberg (Berlin), Trastevere (Rome), Bairro Alto (Lisbon), Södermalm (Stockholm).",
      "**Asia:** Shimokitazawa (Tokyo), Seongsu-dong (Seoul), Tiong Bahru (Singapore), Nimmanhaemin (Chiang Mai).",
      "**Americas:** Williamsburg (Brooklyn), Palermo Soho (Buenos Aires), Mile End (Montreal), Condesa (Mexico City).",
      "What these places share: excellent café density (so you are never far from a reason to sit down), good public transit (so you can get home easily), a mix of locals and travelers (so you are not the only tourist), and an active street life that continues after sunset.",
    ],
  },
  {
    slug: 'how-to-tell-a-real-neighborhood-from-a-tourist-zone',
    title: 'How to tell a real neighborhood from a tourist zone',
    excerpt: 'A short checklist for recognizing when you have drifted into tourist-trap territory — and what to do about it.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-20',
    tags: ['travel-tips', 'guide'],
    body: [
      "Tourist zones look like neighborhoods. They have restaurants, bars, shops. From a distance — especially in photos — they can even look picturesque. But spend a day in one and the difference is unmistakable.",
      "Here is our checklist. If a district hits three or more of these, treat it as a tourist zone and reset your expectations.",
      "**1. Every restaurant has a multilingual menu with photos.** Real neighborhoods have restaurants that assume you speak the local language (or will figure it out).",
      "**2. Souvenir shops outnumber bookshops, bakeries and hardware stores.** Locals don't buy fridge magnets. Real neighborhoods have the infrastructure of daily life.",
      "**3. Restaurants empty out between 3 PM and 7 PM.** Locals eat lunch at one and dinner at eight. Tourist zones serve dinner at 5 PM because that is when Americans arrive.",
      "**4. There are no children anywhere.** Real neighborhoods have playgrounds, strollers, and kids getting out of school. Tourist zones do not.",
      "**5. The buildings are picturesque but closed shops downstairs.** Locals have turned the ground floors into Airbnbs. The neighborhood has been hollowed out.",
      "The good news: in almost every city, a genuine neighborhood is a 15-minute walk from the tourist zone. Go there.",
    ],
  },
  {
    slug: 'the-case-for-staying-in-the-same-neighborhood-twice',
    title: 'The case for staying in the same neighborhood twice',
    excerpt: 'There is a strong argument for revisiting neighborhoods you already know — and for most travelers, it is the wrong one.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-17',
    tags: ['travel-philosophy', 'guide'],
    body: [
      "There is something slightly unfashionable about staying in the same neighborhood twice. Travel magazines are structured around novelty — 'this year's hot new district' — and the implicit message is that revisiting anywhere is a failure of imagination.",
      "We disagree. The second time you stay in a neighborhood is when you start actually knowing it. The first visit is an audit: you learn the streets, you figure out where the coffee is, you identify the one restaurant you want to return to. The second visit is the payoff. You skip the tourist sites, you eat at the restaurant you loved last time, and you walk around like someone who lives there for a week.",
      "The third visit is where it gets interesting. You start recognizing regulars at your favorite bar. You have opinions about which bakery is best. You stop photographing the neighborhood and start just living in it.",
      "Our editorial recommendation: pick three neighborhoods you love around the world and go back to each of them every few years. You will learn more about those three places than you will learn from thirty novel trips, and you will enjoy them far more.",
    ],
  },
  {
    slug: 'the-rise-of-the-15-minute-city',
    title: 'The rise of the 15-minute city, and why it matters for travelers',
    excerpt: 'Urbanists are talking about 15-minute cities. Travelers should be too.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-14',
    tags: ['urbanism', 'travel-philosophy'],
    body: [
      "The 15-minute city — a concept popularized by urbanist Carlos Moreno — is a city where everything you need is within a 15-minute walk or bike ride of your home. Groceries, schools, parks, doctors, work, entertainment. The idea has become one of the organizing principles of modern urban planning, championed most visibly by Paris under Mayor Anne Hidalgo.",
      "For travelers, the 15-minute city has a surprising implication: it tells you where to stay. The neighborhoods that rank highest on 15-minute-city metrics are, almost without exception, the ones where tourists have the best time too. That is not a coincidence. What makes a neighborhood liveable for residents — density, walkability, café culture, independent shops, public space — is exactly what makes it rewarding for visitors.",
      "Paris's 11th arrondissement is a textbook example. So is Copenhagen's Nørrebro, Melbourne's Fitzroy, Barcelona's Gràcia, Mexico City's Roma Norte. All of them pass the 15-minute test. All of them are on our highest-rated neighborhood lists. Again: not a coincidence.",
      "When you are picking a neighborhood on an unfamiliar city's map, use the 15-minute test as a shortcut. Does this place work for a local who has to do everything on foot? If yes, it will work for you too.",
    ],
  },
  {
    slug: 'europes-most-liveable-neighborhoods',
    title: "Europe's ten most liveable neighborhoods, according to us",
    excerpt: 'Our editorial picks for the ten European neighborhoods we would most want to live in for a year.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-11',
    tags: ['europe', 'cities', 'liveability'],
    body: [
      "We get asked this question a lot, and every answer is contested — liveability is a personal measure. But the ten neighborhoods we argue about most internally, the ones that keep coming up when we say 'if I had to live in Europe for a year, I would live in…', are these.",
      "**1. Prenzlauer Berg, Berlin.** The benchmark for walkable, leafy, café-dense European city life.",
      "**2. Vesterbro, Copenhagen.** The highest concentration of great restaurants per square meter in Northern Europe.",
      "**3. Nørrebro, Copenhagen.** Nørrebro slightly edges Vesterbro on diversity and the Superkilen park.",
      "**4. Gràcia, Barcelona.** A village inside a city. The plazas in the evening, the festa major in August, the café density.",
      "**5. Le Marais, Paris.** If we had to pick one neighborhood in Paris. The walking, the food, the Jewish quarter, the Place des Vosges.",
      "**6. Kreuzberg, Berlin.** Still the best neighborhood for culture-first urban life in Europe, even after gentrification.",
      "**7. Södermalm, Stockholm.** Stockholm's hippest island, with better views than anywhere else on the list.",
      "**8. Oltrarno, Florence.** Florence's left bank — artisan workshops, great trattorias, real neighborhood life.",
      "**9. De Pijp, Amsterdam.** The Albert Cuyp market, the best coffee in Amsterdam, a residential core that still works.",
      "**10. Lavapiés, Madrid.** The most multicultural neighborhood on this list, and one of the most alive.",
    ],
  },
  {
    slug: 'asia-s-most-walkable-cities',
    title: "Asia's most walkable cities (and the neighborhoods inside them)",
    excerpt: "Asia's megacities are often called impossible to walk. That is half-true. Here are the exceptions.",
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-08',
    tags: ['asia', 'walking', 'guide'],
    body: [
      "Asia's megacities have a reputation for being impossible to walk. That is half-true. The highways and the scale are often intimidating, but almost every major Asian city has pockets — sometimes small, sometimes enormous — that are as walkable as anywhere in Europe.",
      "**Tokyo** is the hidden champion. The density of small streets and shop-lined alleyways makes most of central Tokyo extraordinarily walkable. Shimokitazawa, Yanaka, Shibuya, Daikanyama, the alleys of Shinjuku — every one a walking city unto itself.",
      "**Seoul** has been a revelation of the last decade. Seongsu-dong, Ikseon-dong's hanok alleys, Yeonnam-dong along the Gyeongui Line Forest — Seoul is now one of the best walking cities in Asia.",
      "**Singapore** is Asia's most planned walkable city. Tiong Bahru, Kampong Glam, Katong and Chinatown are all proper walking neighborhoods, well-shaded, well-signposted.",
      "**Bangkok** surprises people. The sois off Sukhumvit — Ari, Thonglor, Ekkamai — are deeply walkable once you are inside them. The challenge is crossing main roads.",
      "**Chiang Mai** is all walkable. The Old City within the moat is a proper walking town.",
      "**Hanoi**'s Old Quarter is one of the best walking districts in Asia, chaos and all.",
      "What these neighborhoods share: human-scaled blocks, street food, narrow lanes, and a density of interesting things per meter walked. In that respect, Asia's best neighborhoods are not so different from Europe's.",
    ],
  },
  {
    slug: 'the-coffee-test',
    title: 'The Coffee Test: what espresso tells you about a neighborhood',
    excerpt: 'Every great neighborhood has great coffee. The reverse is almost always true too.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-05',
    tags: ['food', 'coffee', 'travel-tips'],
    body: [
      "Every great neighborhood has at least one excellent café. The reverse is almost always true too: a neighborhood that has no good coffee is almost certainly a neighborhood that does not work for us.",
      "This is not because coffee matters so much in itself. It is because what it takes to sustain a great independent café — knowledgeable customers, enough density that a small business can survive on regulars, a neighborhood that values craft over convenience — is the same thing that makes a neighborhood great overall.",
      "The shortcut: on your first day in a new neighborhood, walk for 10 minutes in any direction and count independent specialty coffee shops. If you count three or more, you are in a neighborhood worth exploring. If you count zero and only see chains, move on.",
      "This test cuts ruthlessly against travel brochures. Many famously 'beautiful' neighborhoods fail it — because beauty without a daily local rhythm is just a film set. The Coffee Test is one of the simplest ways to tell the two apart.",
      "If you want a starting point: Melbourne's Fitzroy, Copenhagen's Nørrebro, Seoul's Yeonnam-dong, Wellington's Cuba Street, Mexico City's Condesa, and Brooklyn's Williamsburg would all score eight or more on our ten-minute walk. That is not an accident.",
    ],
  },
  {
    slug: 'the-case-against-central-business-districts',
    title: 'The case against central business districts',
    excerpt: "CBDs look central on the map. They are usually the worst place to stay.",
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-02',
    tags: ['travel-tips', 'hotels'],
    body: [
      "Central business districts look appealing on the map because they are in the middle. That is their only virtue. Almost everything else about them is bad.",
      "CBDs empty out at night. The restaurants close at 9 PM because their office-worker lunch clientele has gone home. The streets feel dead after dark — not dangerous, just sterile. The hotels are designed for business travelers, which means chain properties, uninspired breakfast, and a clientele that disappears on weekends, taking the life of the building with them.",
      "CBDs are rarely walkable in any meaningful sense. They are walkable for office workers between their office and the nearest lunch spot. For visitors trying to have a city experience, they are dead zones that you will spend your trip leaving.",
      "Examples you should avoid: the City in London (beautiful architecture, no life after 6 PM), Downtown Washington, DC (closed on weekends), Frankfurt's banking district, Makati's Ayala business strip (convenient but lifeless), Singapore's Raffles Place after dark.",
      "The alternative is always a residential neighborhood adjacent to the CBD. Shoreditch instead of the City. Mount Pleasant instead of downtown Vancouver. Poblacion instead of Ayala. Kreuzberg instead of Potsdamer Platz. You will pay less for your hotel and have a much better trip.",
    ],
  },
  {
    slug: 'the-neighborhood-dinner-rule',
    title: 'The Neighborhood Dinner Rule: eat where you are, not where Google tells you',
    excerpt: 'The best dinner in a new city is almost never the one with the most Google reviews.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-28',
    tags: ['food', 'travel-tips'],
    body: [
      "Here is a simple rule we live by: on the first night in a new neighborhood, eat at the closest restaurant that passes a three-part test. One, it is full of locals. Two, the menu is in the local language. Three, the staff are unhurried — nobody is trying to upsell you anything.",
      "That is it. Do not look at Google reviews. Do not consult a 'best of' list. Walk out of your hotel, walk for ten minutes in the direction that looks most alive, and pick the restaurant that matches those three criteria.",
      "This almost always produces a better dinner than following Google. The reason is that Google reviews reward tourist-optimized restaurants — the ones with English menus, Instagram decor, and staff trained to smile for photos. Those restaurants are not bad, but they are rarely great. Great neighborhood restaurants are too busy feeding locals to care about the global review economy.",
      "The second-night rule: ask the locals you met at dinner where they would eat tomorrow. Every great meal we have ever had in a new city came from a recommendation given over the table at another meal. Never from the internet.",
    ],
  },
  {
    slug: 'where-to-stay-in-paris-by-trip-type',
    title: 'Where to stay in Paris, by trip type',
    excerpt: 'Paris is not one city — it is twenty. Here is how to pick the right arrondissement for the trip you are actually taking.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-25',
    tags: ['paris', 'hotels', 'guide'],
    body: [
      "Paris's twenty arrondissements spiral clockwise from the center, and choosing between them is the most important decision of a Paris trip. Here is our shortlist by trip type.",
      "**First-time trip, must see the monuments.** Le Marais (3rd/4th). Central, walkable, fifteen minutes from every major site. Expensive, but justifiable.",
      "**Food-focused trip.** The 11th arrondissement, particularly around Oberkampf and Rue Paul Bert. Best concentration of neo-bistros in the city.",
      "**Bohemian, artist-Paris fantasy trip.** Montmartre (18th). Yes, it is touristy around Sacré-Cœur, but the quiet streets behind the basilica are the real thing.",
      "**Literary, Left Bank trip.** Saint-Germain-des-Prés (6th). Expensive, elegant, and walking distance from the Musée d'Orsay, Luxembourg Gardens, and the best bookshops in Europe.",
      "**Quiet, local Paris trip.** Canal Saint-Martin (10th). The most 'neighborhood' feel of any central Paris district.",
      "**Budget-conscious, young Paris trip.** Belleville (20th) or République (11th). Diverse, energetic, and noticeably cheaper than Paris proper.",
      "**Second-time Paris trip.** The 11th or the 9th (SoPi/South Pigalle). Both are cool without being loud, with great food and genuine Parisian life.",
      "Rule of thumb for all of them: Paris is at its best when you can walk out of your hotel and be at a café within two minutes. All of the above pass that test.",
    ],
  },
  {
    slug: 'the-return-of-the-mediterranean-summer',
    title: 'The return of the Mediterranean summer (and where to stay to enjoy it)',
    excerpt: 'Climate change is rewriting the summer travel calendar. Here is how we are adapting.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-22',
    tags: ['summer', 'mediterranean', 'climate'],
    body: [
      "The Mediterranean summer has become unpredictable in a way it was not twenty years ago. Peak July and August now routinely deliver heatwaves in the mid-40s Celsius in southern Spain, Italy and Greece. The traditional 'visit in July' advice that dominated travel writing for decades is quietly being replaced.",
      "Our current recommendation is to travel in May, June, and mid-September. The weather is warm but not hostile, the crowds are thinner, the prices are lower, and you can still walk through a city at 2 PM without planning your route between air-conditioned spaces.",
      "For summer itself, we prefer neighborhoods that have meaningful shade, proximity to water, and strong evening life. Examples: Trastevere in Rome (shade, river, evening aperitivos), Gràcia in Barcelona (trees, smaller plazas, elevation), Alfama in Lisbon (coastal breeze and miradouros), Vedado in Havana (grid of tree-lined streets).",
      "Neighborhoods to avoid in mid-summer heat: Seville's tourist core, central Athens, Naples' Quartieri Spagnoli (beautiful but a heat trap), Madrid's Sol. These places are wonderful in May and October. In August they can be genuinely dangerous.",
    ],
  },
  {
    slug: 'the-underrated-art-of-the-city-walk',
    title: 'The underrated art of the aimless city walk',
    excerpt: 'The best way to understand a neighborhood is to walk it with no agenda whatsoever.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-19',
    tags: ['travel-philosophy', 'walking'],
    body: [
      "The best thing you can do in any new neighborhood is also the simplest: leave your hotel in the morning with no plan at all, and walk until you are hungry. No monuments. No museums. No 'must-see' list.",
      "This is the technique the French call flânerie, and it is the only reliable way to actually understand a neighborhood. You will see things you would never see on a guided walk: how locals greet each other, where the school run happens, which corners are noisy at lunch, which streets are deserted at 3 PM, where the old men play chess.",
      "The mistake most travelers make is trying to optimize. They plan routes, they tick off landmarks, they chase the perfect photo spot. All of which produces the same trip everyone else has. The aimless walker, by contrast, leaves with a story nobody else has.",
      "Our suggestion: dedicate the first morning of every trip to a walk with no destination. You will thank us for the rest of your stay.",
    ],
  },
  {
    slug: 'neighborhood-safety-the-honest-version',
    title: 'Neighborhood safety: the honest version',
    excerpt: 'How to think about safety in an unfamiliar neighborhood, without falling for panic or complacency.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-16',
    tags: ['safety', 'travel-tips'],
    body: [
      "Safety advice about neighborhoods is almost always either too panicked or too casual. The panicked version tells you not to leave your hotel after dark in any city in Latin America. The casual version tells you that 'anywhere is fine if you just pay attention'. Both are useless.",
      "Our honest version: 99% of tourist crime is opportunistic theft — pickpocketing, bag-snatching, distraction scams. It happens disproportionately in crowded tourist areas during the day, not in 'sketchy' neighborhoods at night. The Las Ramblas, the Trevi Fountain, the metro between Gare du Nord and Châtelet. Not the dark alley your guidebook warned you about.",
      "Real safety advice is almost boring: do not carry valuables you do not need, keep your phone in a front pocket, stay on busy streets at night, do not get into unmarked taxis, trust your gut if something feels off. That covers about 95% of cases.",
      "The other 5% is neighborhood-specific. Before you go, ask a local where not to walk after dark. Every major city has two or three such blocks. The information is easy to get if you ask. And crucially, those blocks are almost never the ones travel-safety articles warn you about.",
    ],
  },
  {
    slug: 'why-neighborhood-hotels-beat-international-chains',
    title: 'Why a neighborhood boutique hotel will always beat an international chain',
    excerpt: 'You will pay the same and have a better trip. Here is the math.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-13',
    tags: ['hotels', 'travel-tips'],
    body: [
      "The traditional logic for booking an international chain — 'I know what I am getting' — has quietly broken down. The quality-floor chains used to promise is no longer meaningfully different from what you can expect at a good independent hotel, and the upside of an independent is much, much higher.",
      "Consider: an international chain in Lisbon will cost you roughly the same per night as the best boutique hotel in Príncipe Real or the Baixa. The chain will give you a standardized room, a standardized breakfast, and a staff trained on a corporate script. The boutique will give you a room with character, a breakfast sourced from local bakeries, and a concierge who actually knows the city.",
      "More importantly: boutique hotels are almost always in better neighborhoods. Chains cluster around airports, convention centers, and tourist strips because that is where their corporate clients are. Boutiques cluster in the neighborhoods locals actually want to live in — which, as we have been arguing all along, is where you want to be.",
      "Our recommendation: next time, pick your neighborhood first, then book the best small hotel in that neighborhood. You will pay roughly the same as a chain, and you will have a trip you actually remember.",
    ],
  },
  {
    slug: 'the-best-neighborhoods-for-rainy-days',
    title: 'The best neighborhoods for a rainy day',
    excerpt: 'Some neighborhoods are made for sunshine. These are made for bad weather.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-10',
    tags: ['weather', 'guide'],
    body: [
      "A rainy day in a great city should be no less great. The trick is picking a neighborhood with enough indoor density — bookshops, cafés, museums, covered markets, hotel bars — that the weather becomes a backdrop rather than a problem.",
      "Our favorites worldwide:",
      "**Paris's 6th arrondissement.** Bookshops, covered passages, Saint-Germain hotel bars. Rainy Paris at its most romantic.",
      "**London's Bloomsbury.** The British Museum, Persephone Books, Waterstones Gower Street, and endless cafés. A full rainy day is a feature, not a bug.",
      "**Tokyo's Jimbocho.** The world's densest concentration of second-hand bookshops, many with cafés attached.",
      "**Porto's Ribeira.** The port tasting rooms alone justify a rainy afternoon.",
      "**Copenhagen's Vesterbro.** Kødbyen's covered courtyards, Vesterbro's cafés, the Meatpacking District's bars.",
      "**Vienna's Innere Stadt.** Coffeehouses that have been designed to absorb rainy afternoons for 200 years.",
      "**Seoul's Insa-dong.** Tea houses, galleries and covered arcades designed for exactly this weather.",
      "Rain is not a trip-ruiner. A bad neighborhood is. Book the right one and you will remember the rain fondly.",
    ],
  },
  {
    slug: 'latin-america-next-wave',
    title: "Latin America's next wave: six neighborhoods getting talked about in 2026",
    excerpt: 'The Latin American neighborhoods our editors are visiting this year.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-07',
    tags: ['latin-america', 'cities'],
    body: [
      "Every few years, a new neighborhood in Latin America breaks through. Roma Norte did it in the 2010s. Palermo Soho did it before that. These are the six districts our editors are watching in 2026.",
      "**1. Laureles, Medellín.** The cooler, more local sister of El Poblado. The best evening walk in Colombia right now.",
      "**2. Getsemaní, Cartagena.** The Getsemaní of ten years ago was a backpacker quarter. Today it is arguably the most interesting walled-city-adjacent neighborhood in Latin America.",
      "**3. Barranco, Lima.** Barranco has been 'the next thing' for a decade, and it is finally living up to it. The bar and restaurant scene is now serious.",
      "**4. Bellavista, Santiago.** Santiago's bohemian heart continues to punch above its weight. The best murals in South America.",
      "**5. Barrio Italia, Santiago.** Antique shops and design workshops in a neighborhood that feels hand-crafted.",
      "**6. La Floresta, Quito.** Quito's quietly excellent bohemian district is one of our editors' favorites in the Andes.",
      "City guides for all six are live on the site. The common thread: warmth, walkability, and the kind of neighborhood identity that tourist districts can never manufacture.",
    ],
  },
  {
    slug: 'the-tiny-bar-rule',
    title: 'The Tiny Bar Rule: why the best drinks are always in the smallest rooms',
    excerpt: 'Almost every great bar we have ever loved had fewer than 20 seats. Here is why.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-04',
    tags: ['bars', 'nightlife', 'guide'],
    body: [
      "Think of the best bar you have ever been to. Really think. Now count how many seats it had.",
      "If your answer is 'fewer than twenty', you are not alone. Almost every great bar in the world — the kind you will remember years later — is tiny. Tokyo's Golden Gai bars seat six people. London's best cocktail bars seat twelve. New York's best speakeasies seat fifteen. This is not a coincidence.",
      "Small bars are great because they force intimacy. The bartender becomes an actual person. Other customers become temporary friends. The room has an acoustic where conversation actually works. Staff know when to leave you alone.",
      "Big bars can never do this. They are designed around throughput. Every great big bar we have ever been to was essentially a great small bar that outgrew its building and never quite kept the soul.",
      "Our rule of thumb: when a local recommends a bar, ask how many people it seats. If the answer is 'about twelve', go tonight. If the answer is 'it is big, they always have room', file it away for another time.",
    ],
  },
  {
    slug: 'what-a-good-neighborhood-market-tells-you',
    title: 'What a good neighborhood market tells you about a city',
    excerpt: 'Every great city has a great neighborhood market. Here is how to read one.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-01',
    tags: ['food', 'markets', 'guide'],
    body: [
      "Every great neighborhood has a market, and every great market tells a story about its neighborhood. Walk through it carefully and you learn more than any guidebook will ever tell you.",
      "What to look for:",
      "**Who is shopping?** If it is mostly tourists with cameras, the market is a tourist attraction, not a market. Move along. If it is locals with wheeled shopping trolleys, this is a real market, and the neighborhood around it is probably a real neighborhood.",
      "**What is in season?** A good market is a calendar of what the region eats right now. White asparagus in April means you are in Northern Europe in spring. Tropical fruit you cannot identify means you are in Southeast Asia.",
      "**How specialized are the stalls?** One stall selling only olives means the olive-eating is serious. One stall selling 'everything' means the market is for shoppers who do not care.",
      "**Is there prepared food to eat on-site?** A market with a dozen tiny counters selling grilled fish, tortas, bánh mì, arepas, whatever the local snack food is — that is the mark of a market that is alive for locals.",
      "Our favorites worldwide: Mercado de San Miguel in Madrid (increasingly touristy but still excellent), Mercado Roma in Mexico City, Tsukiji's outer market in Tokyo, Borough Market in London (on weekdays only), Marché Bastille in Paris (Thursday and Sunday), the Testaccio market in Rome, Boqueria in Barcelona (early morning, before the tourists).",
    ],
  },
  {
    slug: 'the-case-for-slow-travel-neighborhoods',
    title: 'The case for slow travel, and the neighborhoods it needs',
    excerpt: 'Three days in a city is tourism. Three weeks is travel. Here is where to spend the three weeks.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-29',
    tags: ['slow-travel', 'travel-philosophy'],
    body: [
      "Three days in a city is tourism. You tick off the monuments, you eat one or two good meals, you come home with a photo of the cathedral. Three weeks in a single neighborhood is something else entirely. You learn the streets. You develop opinions about the bakeries. You find a café where the staff recognize you.",
      "The neighborhoods that reward slow travel are a specific kind. They need to have enough variety that three weeks does not exhaust them. They need to be walkable enough that daily errands are pleasant, not a logistical headache. They need enough residential density that the rhythm of the place is real — school runs, grocery shopping, evening walks — not performed for tourists.",
      "Our favorites for a three-week stay:",
      "**Europe:** Alfama (Lisbon), Oltrarno (Florence), Kreuzberg (Berlin), Le Marais (Paris), Gràcia (Barcelona), Södermalm (Stockholm).",
      "**Asia:** Shimokitazawa (Tokyo), Tiong Bahru (Singapore), Hanoi Old Quarter, Nimmanhaemin (Chiang Mai), Seongsu-dong (Seoul).",
      "**Americas:** Condesa (Mexico City), Mile End (Montreal), Palermo Soho (Buenos Aires), Brooklyn Heights (New York), Bernal Heights (San Francisco).",
      "Three weeks in one of these beats three days in five cities, every single time.",
    ],
  },
  {
    slug: 'how-we-rank-neighborhoods',
    title: 'How we actually rank the neighborhoods on this site',
    excerpt: 'A transparent look at the editorial process behind our rankings.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-26',
    tags: ['editorial', 'about'],
    body: [
      "A few readers have asked how we actually decide which neighborhoods make our lists. The honest answer is that it is editorial — we read widely, we travel, we synthesize — but there is more structure behind the process than that implies.",
      "**Step 1: collect external rankings.** For every city, we pull rankings from Time Out, Condé Nast Traveler, The New York Times, The Guardian, Monocle, Culture Trip, and the best local travel press. If a neighborhood appears in three or more of these, it is a serious contender.",
      "**Step 2: weight for walkability, café density, and residential life.** We deliberately down-weight neighborhoods that are interesting mainly because of a single museum or monument. A great neighborhood must function as a place to live.",
      "**Step 3: consult local experts where we can.** Our editors live in or regularly visit about 30 of the cities on the site. For the rest, we rely on conversations with locals we trust — journalists, chefs, hotel concierges, restaurant owners.",
      "**Step 4: our editorial call.** After the quantitative and qualitative input, the final ranking is an editorial decision. We pick the five neighborhoods per city that best represent the range of what a traveler should see, not just the five most famous ones.",
      "The process is imperfect. We miss things. We take reader feedback seriously — if you think we are wrong about your city, tell us. Our job is to update.",
    ],
  },
  // ── Wave 2 (added April 2026) ──
  {
    slug: 'asia-walking-cities-extended',
    title: 'Why Tokyo is secretly the best walking city in the world',
    excerpt: 'Forget the megacity stereotypes. Tokyo has more walkable neighborhoods than Paris and Barcelona combined.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-22',
    tags: ['tokyo', 'walking', 'asia'],
    body: [
      "Travel writers love to call Tokyo &lsquo;overwhelming.&rsquo; They are usually describing Shibuya Crossing or Shinjuku Station &mdash; the two most-photographed places in the city, both of which are actually outliers. The real Tokyo is something else entirely: a federation of small, walkable, intimate neighborhoods stitched together by the world&rsquo;s best train network.",
      "Once you leave the major stations, almost every district in central Tokyo is built around the same human-scale formula: narrow streets, small shop frontages, no setback from the sidewalk, mixed residential and commercial use, and a density of interesting things per meter that no European city can match. Yanaka could be a Kyoto temple village. Shimokitazawa could be Brooklyn in 2005. Daikanyama could be a Scandinavian design district. Kagurazaka could be a back-alley in Lyon.",
      "The secret is that Tokyo never demolished its alley grid. Where every European capital widened streets for cars in the 19th and 20th centuries, Tokyo kept the medieval scale of its side roads almost intact. The result is hundreds of square kilometers of neighborhood that reward exactly the kind of slow, aimless walking we keep recommending.",
      "Our advice: spend at least half your Tokyo trip walking through residential districts you have never heard of. Pick a station at random on the Yamanote line, get off, and walk. You will find a neighborhood worth its own trip.",
    ],
  },
  {
    slug: 'the-evening-walk-rule',
    title: 'The Evening Walk Rule: how to know if your neighborhood is real',
    excerpt: 'Tourist neighborhoods are dead at 7 PM. Real neighborhoods are alive at 7 PM. The test is that simple.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-19',
    tags: ['travel-tips', 'guide'],
    body: [
      "Here is a test that takes ten minutes and tells you everything: walk the main street of your neighborhood at 7 PM on a weeknight. If it is full &mdash; not crowded, but full of locals walking dogs, doing groceries, picking up kids, queuing at the wine shop, lingering outside cafés &mdash; you are in a real neighborhood and it will be a great trip. If the street is empty, you are in a tourist zone or a business district and you should probably move hotels.",
      "The Evening Walk Rule works because it captures something hard to fake: the rhythm of people who actually live somewhere. Tourists shop in the morning and eat dinner from 8 PM. Office workers go home by 6:30 PM. Locals are out at 7 PM precisely because their day is winding down and the neighborhood is their living room.",
      "Examples of neighborhoods that pass the test on any weeknight: Le Marais (Paris), Trastevere (Rome), Vesterbro (Copenhagen), Kreuzberg (Berlin), Roma Norte (Mexico City), Williamsburg (Brooklyn), Nimmanhaemin (Chiang Mai), Yeonnam-dong (Seoul), Bandra (Mumbai), El Born (Barcelona).",
      "Examples of neighborhoods that fail the test: Las Vegas Strip, Times Square, Singapore&rsquo;s Marina Bay, Dubai International Financial Centre, the City of London after work hours. Beautiful, sometimes spectacular &mdash; but lifeless when the workers and tourists go home.",
    ],
  },
  {
    slug: 'choosing-between-airbnb-and-hotels-by-neighborhood',
    title: 'When to book an Airbnb and when to book a hotel — by neighborhood type',
    excerpt: 'The choice between hotel and short-term rental is mostly a function of the neighborhood, not the city.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-16',
    tags: ['hotels', 'airbnb', 'travel-tips'],
    body: [
      "The decision to book an Airbnb instead of a hotel is usually framed as a price-versus-amenities question. We think it is more useful to frame it as a neighborhood-fit question.",
      "<strong>Book a hotel</strong> when the neighborhood has serious hotel infrastructure that you actually want to use &mdash; concierges who know the city, breakfast that justifies its price, public spaces that work as a meeting place. The classic European grand-hotel neighborhoods (Le Marais in Paris, Belgravia in London, the Innere Stadt in Vienna) reward hotels because the hotels themselves are part of the experience.",
      "<strong>Book an Airbnb</strong> when the neighborhood is residential and you want to feel like you live there for a week. The Brunch Rule neighborhoods we recommend most often &mdash; Vesterbro, Fitzroy, Mile End, Yeonnam-dong &mdash; are almost always better experienced from a small apartment with a kitchen and a balcony than from a hotel room.",
      "<strong>Avoid Airbnbs</strong> in neighborhoods that have been hollowed out by short-term rentals. Lisbon&rsquo;s Alfama, Barcelona&rsquo;s Gothic Quarter, Florence&rsquo;s historic centre, Venice almost everywhere &mdash; these neighborhoods have lost so many residents to tourism that staying in an Airbnb actively contributes to the problem. In these places, please book a hotel.",
      "<strong>Avoid hotels</strong> in genuinely residential neighborhoods where the only hotels are tired chain properties. If your only options are a Marriott on the edge of a residential district and a small apartment in the middle of it, the apartment will give you a better trip ten times out of ten.",
    ],
  },
  {
    slug: 'how-to-spend-48-hours-in-a-city-you-have-never-visited',
    title: 'How to spend 48 hours in a city you have never visited',
    excerpt: 'A short, opinionated framework for getting maximum value out of a two-day city trip.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-13',
    tags: ['travel-tips', 'guide', 'short-trips'],
    body: [
      "Two days in a new city is enough to fall in love but not enough to know it. Here is the framework we use to make those 48 hours count.",
      "<strong>Day 1, morning &mdash; aimless walk.</strong> Drop your bags. Walk out of the hotel in whichever direction looks most alive. Do not check the map. Do not have a destination. Walk for two hours, sit down for coffee somewhere that looks busy with locals, walk for another hour. This is the most important hour of the trip &mdash; you are calibrating your understanding of the place.",
      "<strong>Day 1, afternoon &mdash; one major site, no more.</strong> Pick the single thing you most want to see, go there, allow it the time it deserves, and skip everything else on the &lsquo;top 10&rsquo; list. Trying to do three sites in a day is how cities become a blur.",
      "<strong>Day 1, evening &mdash; long dinner in a real neighborhood.</strong> Not in the tourist zone. Look up the city&rsquo;s &lsquo;best restaurants&rsquo; list and find the highest-rated one in a residential neighborhood. Walk to it.",
      "<strong>Day 2, morning &mdash; market.</strong> Every great city has a great morning market. Find it, walk through it slowly, eat breakfast there.",
      "<strong>Day 2, afternoon &mdash; second neighborhood.</strong> Pick a different neighborhood from the one you stayed in. Take public transit (never a taxi) to get there. Spend the afternoon walking it. Buy a book or a small object you would not buy at home.",
      "<strong>Day 2, evening &mdash; the bar your dinner waiter recommended.</strong> Always ask. Always go. The best bar in any city is almost always one a local sent you to.",
      "Two days, two neighborhoods, one major site, three meals, one market. That is enough to want to come back &mdash; which is the point.",
    ],
  },
  {
    slug: 'the-best-neighborhoods-for-a-first-time-visitor-vs-a-tenth-time-visitor',
    title: 'The best neighborhoods for a first-time visitor vs a tenth-time visitor',
    excerpt: 'Where to stay the first time you visit a city is almost never where to stay the tenth time.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-10',
    tags: ['travel-tips', 'hotels', 'guide'],
    body: [
      "The neighborhood that&rsquo;s right for your first trip to a city is almost never the neighborhood that&rsquo;s right for your fifth or tenth. First-timers want centrality, walkability to the must-sees, the comfort of being near other tourists. Returning visitors want depth, residential life, the feeling of being inside the city instead of next to it.",
      "<strong>Paris.</strong> First time: the Marais (4th). Tenth time: the 11th around Oberkampf, or Belleville (20th).",
      "<strong>London.</strong> First time: Covent Garden or South Kensington. Tenth time: Hackney, Peckham, or Walthamstow.",
      "<strong>Tokyo.</strong> First time: Shinjuku or Shibuya. Tenth time: Shimokitazawa, Yanaka, Kagurazaka.",
      "<strong>New York.</strong> First time: Midtown. Tenth time: Williamsburg, the West Village, or Brooklyn Heights.",
      "<strong>Rome.</strong> First time: near the Pantheon. Tenth time: Pigneto, Testaccio, or Garbatella.",
      "<strong>Barcelona.</strong> First time: Eixample. Tenth time: Gràcia or Poblenou.",
      "<strong>Mexico City.</strong> First time: Roma Norte. Tenth time: Coyoacán or San Ángel.",
      "Returning visitors don&rsquo;t need to see the cathedral again. They need a neighborhood that gets richer with each visit. That is what depth feels like.",
    ],
  },
  {
    slug: 'the-paradox-of-the-instagram-neighborhood',
    title: 'The paradox of the Instagram neighborhood',
    excerpt: 'The neighborhoods that photograph best are often the worst to actually visit.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-07',
    tags: ['travel-philosophy', 'photography'],
    body: [
      "There is a strange inverse relationship between how photogenic a neighborhood is and how rewarding it is to actually spend time in. The most-photographed streets in any famous tourist city &mdash; Notting Hill&rsquo;s pastel houses, the rainbow staircases of Lisbon, the Bohemian Quarter of Prague, Venice&rsquo;s Burano &mdash; are usually the streets where actual neighborhood life has been most thoroughly displaced.",
      "The dynamic is straightforward. Once a street becomes Instagram-famous, two things happen: tourists arrive in numbers that overwhelm the residential population, and short-term rentals replace year-round residents. Within a few years, the street is still beautiful but it is empty of the people whose lives gave it its character. What remains is a film set.",
      "Our rule: be skeptical of any neighborhood whose name comes up disproportionately on travel Instagram. The neighborhoods that resist the gravitational pull &mdash; because they&rsquo;re harder to photograph, or because they&rsquo;ve quietly resisted Airbnb conversion, or because they&rsquo;re just not photogenic enough for the algorithm &mdash; are usually the ones still worth visiting.",
      "We try to flag this on our city pages. The five neighborhoods we list per city always include at least two that are deeply un-Instagrammable but where a serious traveler will have a much better time.",
    ],
  },
  {
    slug: 'middle-eastern-cities-rising',
    title: 'The Middle Eastern cities you should be visiting in 2026',
    excerpt: 'Beyond Dubai: the cities where the most interesting neighborhoods in the Middle East are quietly opening up.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-04',
    tags: ['middle-east', 'cities', 'underrated'],
    body: [
      "Western travelers&rsquo; mental map of the Middle East tends to start and end with Dubai. That is a mistake. Some of the most interesting urban neighborhoods in the world right now are in the cities Western travel writing has ignored.",
      "<strong>Amman, Jordan.</strong> Jabal Al-Weibdeh is the kind of artist-village hilltop neighborhood that 1990s Berlin or 2000s Brooklyn used to be. Coffee shops in restored stone houses, contemporary galleries, a quietly extraordinary food scene. Easy to reach, safe, English-friendly.",
      "<strong>Beirut, Lebanon.</strong> Despite the country&rsquo;s ongoing crises, Beirut&rsquo;s nightlife and creative neighborhoods &mdash; Mar Mikhael, Gemmayzeh, Hamra &mdash; remain among the most sophisticated in the eastern Mediterranean. Visit when you can.",
      "<strong>Tel Aviv, Israel.</strong> Bauhaus boulevards, the design district of Neve Tzedek, Florentin&rsquo;s street-art nightlife, ancient Jaffa at the southern edge. Few cities pack so much variety into such a small footprint.",
      "<strong>Doha, Qatar.</strong> Often dismissed as &lsquo;Dubai-lite,&rsquo; but the restored Souq Waqif and the Msheireb redevelopment make Doha a more interesting walking city than its richer neighbor.",
      "<strong>Muscat, Oman.</strong> Quietly one of the most beautiful capitals on Earth. Mutrah&rsquo;s old souq, the corniche, and the white-stone cityscape against red mountains.",
      "Each of these cities has full neighborhood guides on the site. Visit them while they&rsquo;re still uncrowded.",
    ],
  },
  {
    slug: 'african-cities-must-visit',
    title: "Africa's most underrated city neighborhoods",
    excerpt: 'African urban neighborhoods deserve far more attention than the global travel press gives them.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-01',
    tags: ['africa', 'cities', 'underrated'],
    body: [
      "Africa has 54 countries and dozens of major cities, but Western travel writing covers maybe four of them with any depth. Our favorite African neighborhoods are mostly in places that get a fraction of the attention they deserve.",
      "<strong>Bo-Kaap, Cape Town.</strong> The rainbow-painted houses of the Cape Malay quarter, climbing Signal Hill above the city. Cape Town&rsquo;s most photogenic neighborhood by some distance, and home to one of the most distinctive food cultures in southern Africa.",
      "<strong>Maboneng, Johannesburg.</strong> A reborn industrial district at the eastern edge of downtown Joburg. Galleries, design shops, and one of the most vibrant Sunday markets on the continent. The transformation from no-go zone to creative hub took less than a decade.",
      "<strong>Osu, Accra.</strong> The nightlife and restaurant heart of Ghana&rsquo;s capital. Oxford Street is one of West Africa&rsquo;s great walking strips.",
      "<strong>Kalk Bay, Cape Town.</strong> A working fishing village half an hour from central Cape Town. Bookshops, antique shops, fish restaurants, and views across False Bay to the Hottentots Holland mountains.",
      "<strong>Bole, Addis Ababa.</strong> Ethiopia&rsquo;s capital is rebuilding fast, and Bole is its most cosmopolitan face: international restaurants, modern hotels, the airport district that has somehow become the cool one.",
      "<strong>The Medina of Fez, Morocco.</strong> The largest car-free urban area in the world, and arguably the most intact medieval city anywhere. Spend three days getting lost in it.",
      "These are not the only ones, but they are the ones we&rsquo;d send a friend to first.",
    ],
  },
  {
    slug: 'south-american-summer-stays',
    title: 'South America in southern-hemisphere summer: where to base yourself',
    excerpt: 'When Europe is freezing, South America is at its peak. Here is where to stay.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-12-29',
    tags: ['south-america', 'cities', 'summer'],
    body: [
      "The Northern hemisphere&rsquo;s winter is South America&rsquo;s peak. December through February is when Buenos Aires, Santiago, Rio, Lima and Bogotá are all at their best &mdash; warm, dry, alive. Here is where to base yourself in each.",
      "<strong>Buenos Aires.</strong> Palermo Soho if it&rsquo;s your first time. Villa Crespo if you&rsquo;ve been before and want a quieter, cheaper version of the same.",
      "<strong>Rio de Janeiro.</strong> Botafogo for the smartest mix of cool and convenient. Ipanema if you want the beach. Santa Teresa if you want the bohemian hilltop.",
      "<strong>São Paulo.</strong> Vila Madalena for the bar scene. Pinheiros for the food. Jardins for the elegance.",
      "<strong>Santiago de Chile.</strong> Lastarria or Bellavista. Both small, walkable, restaurant-dense.",
      "<strong>Lima.</strong> Barranco, every time. Lima&rsquo;s most interesting neighborhood by a wide margin.",
      "<strong>Medellín.</strong> Laureles, not El Poblado. El Poblado is what every guidebook recommends; Laureles is where Medellín locals actually want to live.",
      "<strong>Cartagena.</strong> Getsemaní, not the walled city. The walled city is for daytime; Getsemaní is where you eat dinner and go out.",
      "All of these have full neighborhood guides on the site. Book early &mdash; January is high season everywhere.",
    ],
  },
  {
    slug: 'north-american-cities-by-season',
    title: 'North American cities, by season',
    excerpt: 'When to visit which American city for the best version of itself.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-12-26',
    tags: ['usa', 'canada', 'travel-planning'],
    body: [
      "The right season makes a city. The wrong season ruins it. Here is our cheat sheet for North America.",
      "<strong>Spring (March–May):</strong> Washington DC for the cherry blossoms. Charleston and Savannah before the humidity kicks in. New Orleans for Jazz Fest. Mexico City year-round but particularly perfect in spring.",
      "<strong>Summer (June–August):</strong> Vancouver, Seattle and Portland are at their best. Montreal&rsquo;s outdoor festival season is unmatched. Toronto is alive on patios. Avoid Phoenix and Las Vegas. Avoid the South generally.",
      "<strong>Fall (September–November):</strong> New York at its peak. Boston for the foliage. Vermont and Quebec City for the leaves. San Francisco enjoys its only good weather of the year.",
      "<strong>Winter (December–February):</strong> Miami, New Orleans, San Diego and Tucson. Mexico City still works. Avoid Chicago, Toronto, Montreal and the Northeast generally unless you genuinely love winter.",
      "The pattern: most American cities have a 3–4 month sweet spot and are difficult to visit outside it. Plan accordingly.",
    ],
  },
  {
    slug: 'on-the-perfect-cafe',
    title: 'On the perfect café',
    excerpt: 'A short essay on what makes a café we keep coming back to.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-12-23',
    tags: ['cafes', 'travel-philosophy'],
    body: [
      "A perfect café has six elements. Get any one of them wrong and you don&rsquo;t come back.",
      "<strong>One: the coffee.</strong> Obviously. But this is the one element that has become essentially solved &mdash; in 2026, almost any café in any major city can produce a good espresso. The other five elements are where great cafés differ from ordinary ones.",
      "<strong>Two: the chairs.</strong> They have to be comfortable enough to sit in for an hour without your back hurting, but not so comfortable that the place feels like a hotel lobby. Bentwood is usually right. Modern Scandinavian wood-and-felt also works.",
      "<strong>Three: the noise level.</strong> Loud enough to mask other people&rsquo;s conversations, quiet enough to have your own. The Goldilocks zone is around 60 decibels &mdash; busy but not stressful. Most cafés get this wrong by erring loud.",
      "<strong>Four: the staff.</strong> Friendly without being chatty. They notice you but don&rsquo;t hover. They know which regulars take their coffee the same way every day. Crucially: they don&rsquo;t rush you when you&rsquo;ve been there for an hour.",
      "<strong>Five: the light.</strong> Daylight, ideally indirect. South-facing windows are great. Fluorescent overheads are an automatic disqualification.",
      "<strong>Six: the other customers.</strong> A mix of people working alone, people meeting friends, people reading. Not all teenagers. Not all retirees. Not all laptop monoculture.",
      "The cities that produce the most cafés meeting all six criteria, in our experience: Vienna, Melbourne, Tokyo, Stockholm, Copenhagen, and Mexico City. Worth visiting any of them with no other agenda.",
    ],
  },
  {
    slug: 'why-we-skip-the-monuments',
    title: 'Why we usually skip the monuments',
    excerpt: 'A confession: most of our editors do not visit the famous monuments on most trips. Here is why.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-12-20',
    tags: ['travel-philosophy', 'monuments'],
    body: [
      "A confession that may sound provocative: most of the editors of this site do not visit the famous monuments on most of our trips. We have skipped the Colosseum on at least three Rome visits. We have not climbed the Eiffel Tower this century. We have walked past the Brandenburg Gate without stopping. The Sagrada Família we have seen exactly once, in 2007, in passing.",
      "This is not because monuments are bad. They are wonderful, and we are glad we have seen them. It is because the marginal hour you spend at a monument on visit number five is almost always less rewarding than the marginal hour spent in a café you haven&rsquo;t been to before.",
      "The deeper point is that monuments are essentially museum pieces &mdash; static, scheduled, surrounded by infrastructure designed for tourists. Neighborhoods are the opposite: dynamic, residential, full of accidents you couldn&rsquo;t plan for. Both have their place. But once you have seen the monument once, the neighborhoods are where the actual learning happens.",
      "So go to the Colosseum on your first Rome trip. Go to the Eiffel Tower with your kids on their first Paris trip. And then on every subsequent visit, give the monuments a wave from a distance and spend your day somewhere with no entrance fee, no opening hours, and no guidebook entry.",
    ],
  },
  {
    slug: 'public-transit-as-a-feature',
    title: 'Public transit as a feature, not a chore',
    excerpt: "The cities with the best public transit are also the cities with the best neighborhoods. There's a reason.",
    author: '50 Best Neighborhoods Editorial',
    date: '2025-12-17',
    tags: ['urbanism', 'transit', 'travel-tips'],
    body: [
      "Travelers tend to think of public transit as a chore &mdash; something you tolerate to get from your hotel to a museum. We think of it as one of the most enjoyable parts of any trip, and the cities with the best transit are reliably the cities with the best neighborhoods.",
      "The relationship is causal in both directions. Cities with great transit develop great neighborhoods, because density and walkability follow station access. And great neighborhoods attract the political will to build great transit, because residents want to be able to move between districts without driving.",
      "Tokyo&rsquo;s rail network is the best in the world by every measure, and it produces the best urban texture in the world. Paris&rsquo;s metro is dense enough that no neighborhood is more than 500 meters from a station. Vienna, Berlin, Barcelona, Hong Kong, Seoul, Singapore, Madrid &mdash; all have transit systems that allow you to live and travel without ever needing a car.",
      "The cities with notoriously bad transit &mdash; Los Angeles, Houston, Atlanta, most of the Sun Belt &mdash; correspondingly have weaker neighborhood character. Their best neighborhoods (Silver Lake, the Heights, the Old Fourth Ward) feel like islands.",
      "Our advice: when you visit a new city, try to use the public transit system as much as possible. Buy a multi-day pass. Read the network map over coffee. Ride a line you don&rsquo;t need to ride, just to see where it goes. You will understand the city in a way that taxis can never match.",
    ],
  },
  {
    slug: 'the-best-neighborhoods-for-food',
    title: 'The 12 best neighborhoods in the world for food',
    excerpt: 'Picking the best neighborhoods purely on what you can eat there.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-12-14',
    tags: ['food', 'cities', 'guide'],
    body: [
      "If we had to rank neighborhoods purely on the quality and density of their food, ignoring everything else, this is our shortlist of twelve.",
      "<strong>1. Yaowarat (Bangkok).</strong> The greatest concentration of street food on Earth. Comes alive after dark.",
      "<strong>2. Testaccio (Rome).</strong> The most authentic Roman cuisine. The Testaccio market is the city&rsquo;s working food market.",
      "<strong>3. Tsukiji (Tokyo).</strong> Even after the wholesale market moved, the outer market remains a temple of Japanese seafood.",
      "<strong>4. Roma Norte (Mexico City).</strong> The current global epicenter of fine Mexican dining. Pujol, Contramar, Máximo Bistrot, Quintonil, Rosetta &mdash; the list goes on.",
      "<strong>5. Le 11ème (Paris).</strong> The 11th arrondissement is where Paris&rsquo;s most ambitious neo-bistros cluster. Septime, Clamato, Le Servan, Bistrot Paul Bert.",
      "<strong>6. Yaletown / Mount Pleasant (Vancouver).</strong> Vancouver punches well above its weight on Asian-fusion food.",
      "<strong>7. Chinatown (Singapore).</strong> Hawker centres alongside Michelin-starred dim sum. Unbeatable value.",
      "<strong>8. Bandra (Mumbai).</strong> Mumbai&rsquo;s most cosmopolitan food district, from old Iranian cafés to new modern Indian.",
      "<strong>9. Vesterbro (Copenhagen).</strong> Kødbyen&rsquo;s Meatpacking District has Noma alumni opening new restaurants every month.",
      "<strong>10. East Austin (Texas).</strong> American barbecue at its very highest level, plus a thriving new generation of Texas-fusion restaurants.",
      "<strong>11. Trastevere (Rome).</strong> Yes, twice for Rome. The trattoria density justifies it.",
      "<strong>12. The Mission (San Francisco).</strong> Mission Chinese, Foreign Cinema, Tartine Manufactory, the burrito holy land of La Taquería.",
      "If we extended the list to twenty, we&rsquo;d add Chiang Mai&rsquo;s Old City, Lima&rsquo;s Barranco, Naples&rsquo; Quartieri Spagnoli, Istanbul&rsquo;s Karaköy, Tel Aviv&rsquo;s Carmel Market quarter, Florence&rsquo;s Oltrarno, Lisbon&rsquo;s Mercado da Ribeira, and Seoul&rsquo;s Gwangjang.",
    ],
  },
  {
    slug: 'pre-dawn-walks-are-underrated',
    title: 'Pre-dawn walks are underrated',
    excerpt: 'The best hour to see any city is the hour before sunrise. Almost no one knows this.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-12-11',
    tags: ['travel-tips', 'walking', 'photography'],
    body: [
      "The hour before sunrise is the best time to see any city. The streets are nearly empty. The light is silver and slowly turning gold. The bakeries are starting up. The fishermen are coming in. The night-shift cleaners are heading home and the morning-shift workers are appearing on the streets in twos and threes. You can hear the city breathing.",
      "Almost no traveler does this, because almost no traveler is willing to set an alarm for 5:30 AM on holiday. We make a point of doing it once per trip &mdash; usually on the third morning, when jet lag is mostly resolved and we want to see the city in a different mode.",
      "Cities that reward this most: Venice (genuinely empty before 7 AM, even in summer), Marrakech (the muezzin call to dawn prayer is unforgettable), Tokyo (the Tsukiji outer market by 6 AM), Lisbon (Alfama before the cruise ships arrive), Paris (the Île de la Cité before tourists), Hanoi (the parks fill with tai chi practitioners at dawn).",
      "The other thing pre-dawn walks do is calibrate everything else about a city. The neighborhoods that are interesting at 6 AM are interesting at every hour. The neighborhoods that are dead at 6 AM are usually a little less alive than they appear at 2 PM, too.",
    ],
  },
  {
    slug: 'urban-gardens-and-parks',
    title: 'The case for urban parks (and the cities that have the best ones)',
    excerpt: 'A great park can save a neighborhood. A great neighborhood almost always has one.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-12-08',
    tags: ['parks', 'urbanism', 'cities'],
    body: [
      "It is almost impossible to find a great urban neighborhood without a great park nearby. The relationship is so reliable that we use park quality as a proxy for neighborhood quality when we&rsquo;re evaluating a city we don&rsquo;t know.",
      "A great park does several things at once: it gives residents somewhere to walk a dog, jog, picnic, read a book, have a difficult conversation, or just be alone in public. Cities that have these spaces in abundance produce richer street life around them &mdash; the cafés on the park&rsquo;s edge are always the best in the neighborhood, the apartments around it are the most desirable, the kids who grow up nearby end up coming back as adults.",
      "<strong>Our favorite urban parks worldwide:</strong> Buttes-Chaumont (Paris, 19th); Yoyogi Park (Tokyo); Prospect Park (Brooklyn); Park Güell and Ciutadella (Barcelona); Englischer Garten (Munich); Bois de la Cambre (Brussels); the Royal Parks of London (Hampstead Heath above all); Vondelpark (Amsterdam); Stanley Park (Vancouver); Parque México (Condesa, Mexico City); Lumphini (Bangkok); Centennial Park (Sydney); High Park (Toronto).",
      "When you&rsquo;re evaluating a neighborhood you might stay in, find the nearest park on a map. If the park is small, ugly, or fenced off, the neighborhood will probably feel similar. If the park is large, well-maintained, and full of locals at all hours, the neighborhood will too.",
    ],
  },
  {
    slug: 'a-defense-of-the-suburb',
    title: 'A defense of the suburb (yes, really)',
    excerpt: 'Some of the best urban neighborhoods in the world are technically suburbs.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-12-05',
    tags: ['urbanism', 'suburbs'],
    body: [
      "Travel writing tends to use &lsquo;suburb&rsquo; as a slur. The implication is that anything outside a city&rsquo;s historic core is a soulless commuter zone, full of strip malls and chain restaurants. That stereotype is American &mdash; specifically post-1945 American &mdash; and it does not generalize.",
      "In most of the world, &lsquo;suburb&rsquo; just means &lsquo;neighborhood outside the historic centre,&rsquo; and many of them are extraordinarily good places to live and to visit. London&rsquo;s Hampstead is a suburb. Vienna&rsquo;s Grinzing is a suburb. Sydney&rsquo;s Bondi is a suburb. Paris&rsquo;s Montmartre was a suburb until 1860. Many of our highest-rated neighborhoods on this site &mdash; Mile End in Montreal, Surry Hills in Sydney, Yarraville in Melbourne, Stoneybatter in Dublin &mdash; would be classified as suburbs in their own cities.",
      "What distinguishes a great suburb from a bad one is the same thing that distinguishes a great central neighborhood from a bad one: density, walkability, café culture, mixed use, and a residential rhythm that doesn&rsquo;t empty out at 6 PM. The geographical location relative to the city center matters far less than people assume.",
      "Our advice: when a guidebook tells you not to stay in &lsquo;the suburbs,&rsquo; ignore it. Find out which suburbs are which. The good ones are often better than anywhere downtown.",
    ],
  },
  {
    slug: 'the-second-bar-rule',
    title: 'The Second Bar Rule: how to find the best night out anywhere',
    excerpt: 'The first bar of the night is usually a mistake. The second bar is where the trip happens.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-12-02',
    tags: ['bars', 'nightlife', 'travel-tips'],
    body: [
      "Here is one of the most reliable travel tips we have. The first bar you visit on any night out is almost never the best bar of the night. It is usually the one closest to your hotel, or the one with the best Google reviews, or the one your hotel concierge recommended &mdash; meaning it is optimized for tourists. The bar that ends up being the best of the night is almost always the second one. We call this the Second Bar Rule.",
      "How it works: have one drink at the first bar. Pay attention to which other customers look like locals. Strike up a conversation. Ask them where they would go for the second drink. Then go there.",
      "The Second Bar will, with surprising reliability, be (a) cheaper, (b) less polished, (c) much more atmospheric, and (d) full of people who know each other. It will rarely have a Google rating because most of its customers don&rsquo;t bother to write reviews.",
      "Variations on the rule: the Second Restaurant Rule (ask your dinner waiter where they would eat tomorrow night). The Second Café Rule (ask your barista which other café they go to on their day off). The Second Shop Rule (ask the shopkeeper at the first vintage store which other vintage store you should visit).",
      "All of these work because they bypass the algorithmic selection bias of the modern web. The first place is where the algorithm sends you. The second place is where humans send you. They are almost never the same.",
    ],
  },
  {
    slug: 'the-best-european-cities-for-architecture-walks',
    title: 'The best European cities for an architecture-themed weekend',
    excerpt: 'For travelers who want to organize a city trip around buildings rather than restaurants.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-11-29',
    tags: ['architecture', 'europe', 'cities'],
    body: [
      "Most travel writing organizes trips around food. For travelers who would rather organize a trip around architecture, here is our shortlist of European cities where the buildings themselves are the destination.",
      "<strong>Vienna</strong> for the late-Habsburg ensemble &mdash; Otto Wagner&rsquo;s metro stations, the Postsparkasse, the Looshaus, the Secession building, and the entire Ringstraße as one continuous 19th-century theatre.",
      "<strong>Barcelona</strong> for Gaudí, obviously, but more importantly for the entire Eixample grid &mdash; Cerdà&rsquo;s 1859 plan is still the best urban-design idea of the 19th century.",
      "<strong>Berlin</strong> for the layered modernisms: the Bauhaus Archive, Hans Scharoun&rsquo;s Philharmonie, the Hansaviertel Interbau housing, the GDR Plattenbau, and the more recent Daniel Libeskind and Frank Gehry interventions.",
      "<strong>Helsinki</strong> for Alvar Aalto and his contemporaries. The Finlandia Hall, the Aalto House, Kaisaniemi, the Töölö neighborhood &mdash; Helsinki is a small, walkable masterclass in 20th-century Nordic modernism.",
      "<strong>Porto</strong> for Álvaro Siza Vieira and the Porto School. The Casa da Música, Boa Nova Tea House, the Serralves Foundation, and dozens of smaller works.",
      "<strong>Glasgow</strong> for Charles Rennie Mackintosh, the Victorian commercial city, and the contemporary Riverside Museum by Zaha Hadid.",
      "<strong>Rotterdam</strong> for the entire post-WWII reconstruction. There is nowhere in Europe with more 20th-century architectural experimentation per square mile.",
      "<strong>Lisbon</strong> for the manueline Jerónimos Monastery, Pombaline Baixa, Eduardo Souto de Moura&rsquo;s contemporary work, and the most ornate tile-clad façades in Europe.",
    ],
  },
  {
    slug: 'on-trains-not-planes',
    title: "On taking the train instead of the plane (in Europe especially)",
    excerpt: 'Within Europe, the train is almost always the better choice. Here is why we always recommend it.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-11-26',
    tags: ['trains', 'europe', 'travel-philosophy'],
    body: [
      "Within Europe, the train is almost always the better choice. Not just on the famous routes &mdash; Paris-Brussels, Berlin-Prague, Madrid-Seville &mdash; but on most journeys under 1,000 km the train wins on every dimension that matters.",
      "<strong>Time, end-to-end.</strong> Once you account for getting to the airport, security queues, boarding, and getting from the destination airport to the city centre, train journeys of up to about 6 hours are competitive with flights. Anything under 4 hours is almost always faster by train.",
      "<strong>Cost.</strong> Trains within Europe are not cheap, but they are usually cheaper than the equivalent flight by the time you add baggage, airport transfers, and the productivity loss of not being able to work or read during the journey.",
      "<strong>Comfort.</strong> Trains have legroom, working tables, real food, windows you can see out of, and (often) wifi that actually works. None of this needs explaining to anyone who has flown a budget European airline recently.",
      "<strong>Environment.</strong> Trains produce something like one-tenth the carbon emissions per passenger-kilometre as flights. If that matters to you, the choice is obvious.",
      "<strong>The trip itself.</strong> Train journeys go through landscapes. Flights go through clouds. The train from Geneva to Milan crosses the Alps. The train from Oslo to Bergen is one of the most beautiful train journeys on Earth. The train from Amsterdam to Berlin slides through the Dutch and German countryside in five quiet hours.",
      "Our default for any European trip under 1,000 km: take the train. It is almost always the more memorable choice.",
    ],
  },
  {
    slug: 'the-cheapest-great-neighborhoods',
    title: "Where great neighborhoods still come cheap (in 2026)",
    excerpt: 'Travel is expensive. These neighborhoods are world-class and still affordable.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-11-23',
    tags: ['budget', 'cities', 'travel-planning'],
    body: [
      "Travel is more expensive than it used to be, and the famous neighborhoods of Paris, London, Tokyo and New York have priced out a generation of younger travelers. The good news is that several of our highest-rated neighborhoods worldwide remain genuinely affordable. Here is our shortlist of great neighborhoods where you can still have a wonderful trip on a normal budget.",
      "<strong>Tbilisi, Georgia</strong> &mdash; Sololaki and Old Tbilisi. A flat in the old town, full restaurant for two, and a bottle of Saperavi will run you the price of a London round of cocktails.",
      "<strong>Belgrade, Serbia</strong> &mdash; Savamala and Dorćol. The most underrated nightlife in Europe and the best food-to-price ratio on the continent.",
      "<strong>Kraków, Poland</strong> &mdash; Kazimierz remains a bargain by Western European standards.",
      "<strong>Lisbon, Portugal</strong> &mdash; Lisbon has gone up dramatically, but Graça and Penha de França are still affordable and the food remains shockingly cheap.",
      "<strong>Mexico City, Mexico</strong> &mdash; Roma Sur, Doctores, Narvarte. The CDMX neighborhoods next door to Roma Norte deliver the same experience at half the price.",
      "<strong>Hanoi, Vietnam</strong> &mdash; The Old Quarter and the French Quarter. A great meal in Hanoi can cost three dollars. A wonderful one might cost five.",
      "<strong>Chiang Mai, Thailand</strong> &mdash; Santitham. Northern Thailand at its best for Western prices that look almost embarrassing.",
      "<strong>Naples, Italy</strong> &mdash; the Quartieri Spagnoli. The best food in southern Europe, often at half the prices of Florence or Rome.",
      "<strong>Tirana, Albania</strong> &mdash; Blloku. Eastern European prices, southern European weather.",
      "<strong>Medellín, Colombia</strong> &mdash; Laureles. The best South American value of the moment.",
    ],
  },
  {
    slug: 'how-to-find-the-best-bookshop-in-any-city',
    title: 'How to find the best independent bookshop in any city',
    excerpt: 'A great bookshop is a window into a city. Here is how to find one in 30 minutes.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-11-20',
    tags: ['bookshops', 'travel-tips', 'guide'],
    body: [
      "Finding the best independent bookshop in a new city tells you almost everything you need to know about its intellectual life. We always make a point of doing this within the first 24 hours of any trip.",
      "<strong>Step 1.</strong> Skip Google. Search results for &lsquo;best bookshop in X&rsquo; will return tourist-friendly options and chain stores. Useless.",
      "<strong>Step 2.</strong> Find the local independent newspaper or magazine&rsquo;s arts section online. They will have written about local bookshops repeatedly. Their recommendations will skew toward shops with serious literary programming.",
      "<strong>Step 3.</strong> Cross-reference with the international literary press. The New York Times and the Guardian both maintain lists of the best independent bookshops in major cities. These lists are reliable because the journalists writing them have actually visited.",
      "<strong>Step 4.</strong> Look for shops that host author events. A bookshop&rsquo;s event calendar is the most reliable indicator of how seriously its owners take the business. Shops with weekly events almost always have the best selections.",
      "<strong>Our personal favorites worldwide:</strong>",
      "&middot; <strong>Shakespeare and Company</strong>, Paris, 5th &mdash; the obvious one but still wonderful.",
      "&middot; <strong>Daunt Books</strong>, London, Marylebone &mdash; arranged by country, like a travel-bookshop dream.",
      "&middot; <strong>City Lights</strong>, San Francisco, North Beach &mdash; the Beat poetry capital, still essential.",
      "&middot; <strong>Strand</strong>, New York, East Village &mdash; eighteen miles of books.",
      "&middot; <strong>Persephone Books</strong>, London, Bath &mdash; small, opinionated, focused on overlooked 20th-century women writers.",
      "&middot; <strong>Cărturești Carusel</strong>, Bucharest &mdash; arguably the most beautiful bookshop in the world, in a restored 19th-century bank building.",
      "&middot; <strong>Livraria Lello</strong>, Porto &mdash; touristy now, but the building is unmissable.",
      "&middot; <strong>Pan Tau Books</strong>, Lisbon &mdash; tiny, eccentric, perfect.",
      "&middot; <strong>Kinokuniya Shinjuku</strong>, Tokyo &mdash; for the staggering selection of Japanese literature in translation on the seventh floor.",
      "&middot; <strong>Atlantis Books</strong>, Santorini &mdash; built into a cliff over the Aegean. Worth the trip on its own.",
    ],
  },
  {
    slug: 'the-art-of-saying-no-to-tourist-traps',
    title: 'The art of saying no to tourist traps (without missing the good stuff)',
    excerpt: 'How to avoid the bad parts of a famous neighborhood while still seeing the parts that matter.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-11-17',
    tags: ['travel-tips', 'tourist-traps'],
    body: [
      "Most famous neighborhoods are touristy in some places and authentic in others, often within a few hundred meters of each other. The skill is recognizing the line in real time and crossing it.",
      "Trastevere is a perfect example. The two main piazzas &mdash; Piazza Santa Maria in Trastevere and Piazza Trilussa &mdash; are tourist territory: overpriced, mediocre food, hassling waiters out front. Walk three streets in any direction and you are in the real Trastevere: family-run trattorias, locals walking their dogs, cobblestones with no English menus.",
      "The same dynamic operates in Le Marais (avoid Rue des Rosiers around lunchtime, walk one street north for the real neighborhood), in Notting Hill (Portobello Road on Saturdays is a tourist crush, the surrounding crescents are perfect), in Greenwich Village (Bleecker Street is now a chain-store strip, the side streets are still magic), in Plaka in Athens (the main pedestrian thoroughfare is a souvenir shop, the streets one level above on the Anafiotika hill are extraordinary).",
      "Our heuristics: <strong>(1)</strong> any street with multiple souvenir shops in a row is a tourist street, leave it. <strong>(2)</strong> any restaurant with a host outside trying to lure you in is a tourist trap, walk past. <strong>(3)</strong> any street where every menu has photos and English-only is a tourist street. <strong>(4)</strong> a quiet residential street with one café full of locals is almost always better than a busy commercial street with ten tourist restaurants.",
      "The good news: in almost every famous neighborhood, the authentic version is a five-minute walk from the touristy version. You just have to be willing to walk.",
    ],
  },
  {
    slug: 'why-cities-need-strong-second-tiers',
    title: "Why the best countries have strong second-tier cities",
    excerpt: "Italy doesn't have one great city. It has thirty.",
    author: '50 Best Neighborhoods Editorial',
    date: '2025-11-14',
    tags: ['cities', 'travel-philosophy'],
    body: [
      "One of the most reliable predictors of how rewarding a country is to travel in is whether it has a strong second tier of cities below the capital. Countries with hyper-centralized capitals tend to be one-trip destinations &mdash; you visit Paris, you fly home. Countries with strong networks of mid-sized cities reward returning visitors for years.",
      "Italy is the textbook case. Most travelers visit Rome on their first trip, Florence on their second, Venice on their third &mdash; and then they discover Bologna, Naples, Turin, Lecce, Palermo, Trieste, Catania, Verona, and they realize the country has thirty cities each with the depth of a capital. Italy is functionally inexhaustible.",
      "Spain is similar (Madrid, Barcelona, Seville, Bilbao, Valencia, Granada, San Sebastián, Salamanca). So is Germany (Berlin, Munich, Hamburg, Cologne, Frankfurt, Leipzig, Dresden). So is Japan (Tokyo, Osaka, Kyoto, Hiroshima, Sapporo, Kanazawa, Fukuoka). So is Mexico (Mexico City, Oaxaca, Mérida, Guadalajara, San Miguel de Allende, Puebla).",
      "Countries that don&rsquo;t have this depth tend to feel exhausted after one trip. France comes close to monocentric (everything outside Paris feels like Provincial France) &mdash; though Lyon, Marseille, Bordeaux and Strasbourg do their best. The UK is similarly London-centric, with Edinburgh, Manchester, Liverpool and Bristol filling out the second tier.",
      "Our recommendation: when planning return visits to a country you love, deliberately bypass the capital. The discoveries are almost always richer.",
    ],
  },
  {
    slug: 'how-many-neighborhoods-can-you-really-know',
    title: 'How many neighborhoods can you really know in a lifetime?',
    excerpt: 'A short meditation on the limits of travel.',
    author: '50 Best Neighborhoods Editorial',
    date: '2025-11-11',
    tags: ['travel-philosophy', 'longreads'],
    body: [
      "We have been thinking about the actual upper bound on this. How many neighborhoods can a person genuinely know in one lifetime? Not visit, not pass through, not even spend a long weekend in &mdash; but really know, in the sense of having walked them at all hours, learned the cafés, recognized the regulars at the corner bar, and understood why the people who live there love the place.",
      "Our best estimate is somewhere between twenty and forty. That number is shockingly small. It means that if you devote your travel life to depth rather than breadth &mdash; spending three weeks in one neighborhood instead of three days in seven cities &mdash; you can hope to develop intimate knowledge of perhaps thirty places in a 60-year travel career.",
      "Thirty neighborhoods. Out of how many tens of thousands worth knowing.",
      "This is not a counsel of despair. It is the opposite. The implication is that breadth is almost always the wrong strategy. If you have only thirty neighborhood-shaped slots in your lifetime, you should be ferociously selective about which ones you choose, and you should keep going back to the ones that earn return visits. Two weeks in Le Marais beats two days in Le Marais plus two days in five other cities, every single time.",
      "We try to write this site with that in mind. Our city guides are not bucket lists. They are starting points for travelers who want to pick a few neighborhoods and go deep.",
    ],
  },
  {
    slug: 'neighborhood-cafe-culture-by-city',
    title: 'Neighborhood café culture, by city',
    excerpt: 'Every great city has its own café ritual. Here is how to decode it.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-23',
    tags: ['cafes', 'food', 'guide'],
    body: [
      "Café culture is the single most reliable indicator of a great neighborhood, but the rituals vary wildly from city to city. Here is a short decoder for the ones we visit most.",
      "**Italy.** Stand at the bar, order an espresso, drink it in 60 seconds, pay, leave. Sitting at a table after 11 AM often means a 300% price markup. Locals never order a cappuccino after noon.",
      "**France.** Sitting is the whole point. Nursing one coffee for an hour while watching the street is not rude — it is the entire culture. Do not tip on coffee alone; a couple of coins is enough.",
      "**Vienna.** Coffeehouses are living rooms. You can sit for three hours reading a newspaper, and the waiter will not hurry you. A Melange is the local order; ask for it, not a 'cappuccino'.",
      "**Japan.** Two cultures in parallel. Traditional kissaten are slow, quiet, with classical music and 1960s decor. Specialty third-wave cafés serve the most precisely-brewed coffee on Earth. Both reward patience and silence.",
      "**Australia & New Zealand.** The inventors of modern café culture. Flat whites are the default. Baristas take their craft seriously to a degree unknown anywhere else. Brunch is an institution.",
      "**Nordics.** Coffee is not a ceremony, it is fuel, but the fuel is excellent. Expect single-origin, light-roast, pour-over culture. The fika break in Sweden is the exception — a daily social pause built around coffee and a pastry.",
      "When in doubt: watch what locals do, do the same.",
    ],
  },
];

export function getAllPosts() {
  return [...POSTS].sort((a, b) => (a.date < b.date ? 1 : -1));
}

export function getPost(slug) {
  return POSTS.find((p) => p.slug === slug);
}
