// lib/blog-data.js
// Seed articles for the blog. Expand by appending entries; routes pick them up automatically.

export const POSTS = [
  {
    slug: 'how-to-pick-a-neighborhood-before-you-book',
    title: 'How to pick the right neighborhood before you book your hotel',
    excerpt: 'The single most important decision on any city trip is where you sleep. Here is how to choose well.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-04-06',
    tags: ['travel-tips', 'hotels', 'guide'],
    body: [
      "The single most important decision on any city trip is not which hotel you book — it is which neighborhood that hotel sits in. The difference between a wonderful weekend and a mediocre one is almost entirely geographical.",
      "The rule of thumb we follow at 50 Best Neighborhoods is simple: pick the neighborhood first, then pick the best hotel within it. Starting from the hotel end will always push you toward generic business districts, airport-adjacent blocks, or whatever the booking site's algorithm is promoting this week.",
      "So how do you choose? Three questions.",
      "**1. What do you actually want to do?** A foodie trip to Rome belongs in Testaccio, not Prati. A first-time museum-heavy Paris trip belongs in the Marais, not La Défense. Match the neighborhood's personality to the shape of your trip.",
      "**2. What is the 10-minute walk?** The best test of any neighborhood is what you can reach on foot in ten minutes from your hotel door. Coffee, dinner, a bookshop, a park, a bar: if all five are in that radius, you will have a great trip. If none of them are, the neighborhood is too quiet or too car-dependent.",
      "**3. Where do locals actually spend time?** Tourist neighborhoods empty out at night and on Sundays. Residential neighborhoods keep their soul. When in doubt, pick the one where local families walk their dogs on Sunday mornings — Trastevere over Prati, the Marais over the 16th, Prenzlauer Berg over Mitte.",
      "Our city guides are structured around this logic: each of the five neighborhoods we list for a city answers a different version of the above questions. Start there. Then book the hotel.",
    ],
  },
  {
    slug: 'the-neighborhood-brunch-rule',
    title: 'The Neighborhood Brunch Rule: a 60-second test for a great district',
    excerpt: 'There is one reliable shortcut for spotting the best neighborhood in any unfamiliar city. We call it the Brunch Rule.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-04-04',
    tags: ['travel-tips', 'food', 'guide'],
    body: [
      "Most people arrive in a new city on a Friday night and spend two days trying to figure out which neighborhood they should have booked instead. There is a faster way.",
      "We call it the Brunch Rule, and it works like this: on your first Sunday morning, walk the main street of your neighborhood at 11 AM. If every café has a queue of locals in workout clothes waiting for tables, you are in the right neighborhood. If every café is empty, or full of people taking photos of their avocado toast for Instagram, you are in the wrong one — move hotels.",
      "That sounds glib, but it is remarkably diagnostic. Queues of locals in workout clothes mean: this neighborhood has people who live here, who care about their Sunday routine, who have opinions about which café makes the best flat white. It means the district works as a place to live, not just a place to visit.",
      "Neighborhoods that pass the Brunch Rule around the world: Williamsburg, Brooklyn. Mile End, Montreal. Fitzroy, Melbourne. Vesterbro, Copenhagen. Kreuzberg, Berlin. Notting Hill, London. Condesa, Mexico City. Nørrebro, Copenhagen. Palermo Soho, Buenos Aires.",
      "Neighborhoods that fail: almost any central business district. Almost any stretch dominated by hotel chains. Almost any street where the shops close on Sundays. Beautiful but empty is the worst combination.",
      "Use the rule. Book better.",
    ],
  },
  {
    slug: 'five-underrated-cities',
    title: 'Five underrated cities with extraordinary neighborhoods',
    excerpt: 'Paris, Tokyo and London get the headlines. These five cities deserve far more attention than they get.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-04-02',
    tags: ['cities', 'underrated', 'guide'],
    body: [
      "Every 'world's best city' ranking looks roughly the same: Paris, Tokyo, London, New York, Barcelona, and a handful of usual suspects. They are all wonderful. They are also, in 2026, crowded, expensive, and — crucially — no longer surprising.",
      "Here are five cities we think are quietly hosting some of the most interesting neighborhoods in the world right now.",
      "**1. Tbilisi, Georgia.** Old Tbilisi's wooden balconies and sulphur baths, Sololaki's artistic quarter, Vera's riverside cafés — Tbilisi is the most atmospheric city in the Caucasus and still a fraction of the price of any European capital.",
      "**2. Porto, Portugal.** Lisbon is increasingly Lisbon-priced. Porto remains the quieter, grittier, more rewarding Portuguese city — especially Ribeira's UNESCO-listed riverfront and the emerging Cedofeita design quarter.",
      "**3. Bologna, Italy.** Florence and Venice get the tourists. Bologna gets the food. The porticoes of the centro storico, the food market in the Quadrilatero, the university-town energy — Bologna is the smartest Italian city for a food-focused weekend.",
      "**4. Ljubljana, Slovenia.** A capital the size of a large town. Metelkova's autonomous culture zone, Trnovo's riverside and the castle-hill old town make for one of Europe's most walkable city trips.",
      "**5. Tel Aviv, Israel.** Bauhaus boulevards, Neve Tzedek's stone alleys, the Florentin nightlife scene, and ancient Jaffa at the southern edge. Few cities combine beach, ancient history and contemporary design culture so elegantly.",
      "We have full neighborhood guides for each of these cities — use the city index to explore.",
    ],
  },
  {
    slug: 'why-we-synthesize-editorial-sources',
    title: 'Why our rankings synthesize editorial sources (and do not scrape them)',
    excerpt: 'A note on how we build our rankings, and why you will not find scraped article text on this site.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-30',
    tags: ['editorial', 'about'],
    body: [
      "Every neighborhood page on 50 Best Neighborhoods lists three editorial sources — Time Out, Condé Nast Traveler, The New York Times, The Guardian, local city press — where you can read more. We link to publication homepages and travel sections, but we do not scrape, mirror or republish their editorial content. That is deliberate.",
      "First, the legal point: scraping and republishing copyrighted editorial content is copyright infringement, full stop. Many travel aggregators have tried it and many have been forced to shut down or settle. We are not going to play that game.",
      "Second, the editorial point: a synthesis is more useful than a paste. A travel reader does not need to read fifteen 'Best Neighborhoods in London' articles in full — they need the short version that reconciles what the fifteen articles agree on and disagree about. That is what we are trying to provide.",
      "Third, the encyclopedic point: for factual context about each neighborhood — history, architecture, demographics, famous residents, cultural landmarks — we draw on Wikipedia, which is licensed under Creative Commons Attribution-ShareAlike 4.0. That license permits reuse with attribution, which we render on every neighborhood page and in the site footer.",
      "The result: original editorial rankings, plus factual encyclopedic context, plus attributed links to the best travel journalism. No scraping, no pasting, no copyright gray area. That is the deal.",
    ],
  },
  {
    slug: 'where-to-stay-for-nightlife-vs-sleep',
    title: 'Where to stay for nightlife — and where to stay if you like sleeping',
    excerpt: 'The two most common hotel mistakes in every major city, and how to avoid them.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-28',
    tags: ['travel-tips', 'hotels'],
    body: [
      "Two of the most common mistakes travelers make when picking a neighborhood are symmetrical. The first is booking far from the nightlife because 'it will be quieter' — and then spending 40 minutes and €25 in a taxi every time you want dinner. The second is booking in the middle of the nightlife district because 'we'll walk everywhere' — and then being kept awake until 4 AM by people throwing up in the street below your window.",
      "The sweet spot is almost always adjacent. One neighborhood over from the loudest district, within walking distance of the action but out of earshot of the worst of it. Examples:",
      "• In Berlin: stay in Kreuzberg or Friedrichshain, not on Oranienburger Straße.",
      "• In Lisbon: stay in Príncipe Real or Chiado, not in Bairro Alto itself.",
      "• In Buenos Aires: stay in Palermo Chico or Villa Crespo, not in Palermo Soho's loudest blocks.",
      "• In Bangkok: stay in Ari or Ekkamai, not on Sukhumvit Soi 11.",
      "• In Madrid: stay in Chueca or Malasaña (but not on the main drag), not in Sol.",
      "Our neighborhood pages note the nightlife character of each district explicitly — check the tagline before you book. 'Loud' districts have a tagline that tells you so.",
    ],
  },

  // ── New posts (20) ──
  {
    slug: 'the-walking-city-test',
    title: 'The Walking City Test: why a 30-minute walk tells you everything',
    excerpt: 'The single clearest test of whether a city is a great city is how far you can walk from your hotel without getting bored.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-25',
    tags: ['travel-tips', 'guide', 'walking'],
    body: [
      "The single clearest test of whether a city is a great city is how far you can walk from your hotel without getting bored. Half an hour is our standard. If you can walk for 30 minutes in any direction from a central hotel and still see interesting things every block, the city is great. If you hit a dead zone within five minutes, the city is badly planned or you are in the wrong neighborhood — usually both.",
      "Venice passes the Walking City Test everywhere. Paris does within the Périphérique. Barcelona does in Ciutat Vella and most of L'Eixample. Tokyo does almost absurdly well — its density of small, interesting shops is unmatched anywhere.",
      "Cities that fail the test: Los Angeles, almost anywhere. Houston, anywhere. Dubai outside a few walkable pockets. Most American cities, if you are honest about it — the ones with walkable downtowns (Boston, San Francisco, New York) are the exceptions that prove the rule.",
      "The implication for travelers is simple: prioritize dense, walkable historic centers over central business districts. A bad hotel in a great neighborhood beats a great hotel in a bad one, every single time.",
    ],
  },
  {
    slug: 'neighborhoods-for-solo-travelers',
    title: '15 neighborhoods that are particularly welcoming to solo travelers',
    excerpt: 'Some neighborhoods feel lonely when you travel alone. These fifteen feel like the opposite.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-22',
    tags: ['solo-travel', 'cities', 'guide'],
    body: [
      "Traveling alone changes what you want from a neighborhood. You need places where showing up alone at a bar is normal, where cafés don't treat solo diners like a problem, where you can walk safely at 11 PM, and where there is enough street life that you never feel like the only person out.",
      "Our shortlist of neighborhoods that do all of the above, in rough order of how easy they are for first-time solo travelers:",
      "**Europe:** Le Marais (Paris), Neubau (Vienna), Vesterbro (Copenhagen), Kreuzberg (Berlin), Trastevere (Rome), Bairro Alto (Lisbon), Södermalm (Stockholm).",
      "**Asia:** Shimokitazawa (Tokyo), Seongsu-dong (Seoul), Tiong Bahru (Singapore), Nimmanhaemin (Chiang Mai).",
      "**Americas:** Williamsburg (Brooklyn), Palermo Soho (Buenos Aires), Mile End (Montreal), Condesa (Mexico City).",
      "What these places share: excellent café density (so you are never far from a reason to sit down), good public transit (so you can get home easily), a mix of locals and travelers (so you are not the only tourist), and an active street life that continues after sunset.",
    ],
  },
  {
    slug: 'how-to-tell-a-real-neighborhood-from-a-tourist-zone',
    title: 'How to tell a real neighborhood from a tourist zone',
    excerpt: 'A short checklist for recognizing when you have drifted into tourist-trap territory — and what to do about it.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-20',
    tags: ['travel-tips', 'guide'],
    body: [
      "Tourist zones look like neighborhoods. They have restaurants, bars, shops. From a distance — especially in photos — they can even look picturesque. But spend a day in one and the difference is unmistakable.",
      "Here is our checklist. If a district hits three or more of these, treat it as a tourist zone and reset your expectations.",
      "**1. Every restaurant has a multilingual menu with photos.** Real neighborhoods have restaurants that assume you speak the local language (or will figure it out).",
      "**2. Souvenir shops outnumber bookshops, bakeries and hardware stores.** Locals don't buy fridge magnets. Real neighborhoods have the infrastructure of daily life.",
      "**3. Restaurants empty out between 3 PM and 7 PM.** Locals eat lunch at one and dinner at eight. Tourist zones serve dinner at 5 PM because that is when Americans arrive.",
      "**4. There are no children anywhere.** Real neighborhoods have playgrounds, strollers, and kids getting out of school. Tourist zones do not.",
      "**5. The buildings are picturesque but closed shops downstairs.** Locals have turned the ground floors into Airbnbs. The neighborhood has been hollowed out.",
      "The good news: in almost every city, a genuine neighborhood is a 15-minute walk from the tourist zone. Go there.",
    ],
  },
  {
    slug: 'the-case-for-staying-in-the-same-neighborhood-twice',
    title: 'The case for staying in the same neighborhood twice',
    excerpt: 'There is a strong argument for revisiting neighborhoods you already know — and for most travelers, it is the wrong one.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-17',
    tags: ['travel-philosophy', 'guide'],
    body: [
      "There is something slightly unfashionable about staying in the same neighborhood twice. Travel magazines are structured around novelty — 'this year's hot new district' — and the implicit message is that revisiting anywhere is a failure of imagination.",
      "We disagree. The second time you stay in a neighborhood is when you start actually knowing it. The first visit is an audit: you learn the streets, you figure out where the coffee is, you identify the one restaurant you want to return to. The second visit is the payoff. You skip the tourist sites, you eat at the restaurant you loved last time, and you walk around like someone who lives there for a week.",
      "The third visit is where it gets interesting. You start recognizing regulars at your favorite bar. You have opinions about which bakery is best. You stop photographing the neighborhood and start just living in it.",
      "Our editorial recommendation: pick three neighborhoods you love around the world and go back to each of them every few years. You will learn more about those three places than you will learn from thirty novel trips, and you will enjoy them far more.",
    ],
  },
  {
    slug: 'the-rise-of-the-15-minute-city',
    title: 'The rise of the 15-minute city, and why it matters for travelers',
    excerpt: 'Urbanists are talking about 15-minute cities. Travelers should be too.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-14',
    tags: ['urbanism', 'travel-philosophy'],
    body: [
      "The 15-minute city — a concept popularized by urbanist Carlos Moreno — is a city where everything you need is within a 15-minute walk or bike ride of your home. Groceries, schools, parks, doctors, work, entertainment. The idea has become one of the organizing principles of modern urban planning, championed most visibly by Paris under Mayor Anne Hidalgo.",
      "For travelers, the 15-minute city has a surprising implication: it tells you where to stay. The neighborhoods that rank highest on 15-minute-city metrics are, almost without exception, the ones where tourists have the best time too. That is not a coincidence. What makes a neighborhood liveable for residents — density, walkability, café culture, independent shops, public space — is exactly what makes it rewarding for visitors.",
      "Paris's 11th arrondissement is a textbook example. So is Copenhagen's Nørrebro, Melbourne's Fitzroy, Barcelona's Gràcia, Mexico City's Roma Norte. All of them pass the 15-minute test. All of them are on our highest-rated neighborhood lists. Again: not a coincidence.",
      "When you are picking a neighborhood on an unfamiliar city's map, use the 15-minute test as a shortcut. Does this place work for a local who has to do everything on foot? If yes, it will work for you too.",
    ],
  },
  {
    slug: 'europes-most-liveable-neighborhoods',
    title: "Europe's ten most liveable neighborhoods, according to us",
    excerpt: 'Our editorial picks for the ten European neighborhoods we would most want to live in for a year.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-11',
    tags: ['europe', 'cities', 'liveability'],
    body: [
      "We get asked this question a lot, and every answer is contested — liveability is a personal measure. But the ten neighborhoods we argue about most internally, the ones that keep coming up when we say 'if I had to live in Europe for a year, I would live in…', are these.",
      "**1. Prenzlauer Berg, Berlin.** The benchmark for walkable, leafy, café-dense European city life.",
      "**2. Vesterbro, Copenhagen.** The highest concentration of great restaurants per square meter in Northern Europe.",
      "**3. Nørrebro, Copenhagen.** Nørrebro slightly edges Vesterbro on diversity and the Superkilen park.",
      "**4. Gràcia, Barcelona.** A village inside a city. The plazas in the evening, the festa major in August, the café density.",
      "**5. Le Marais, Paris.** If we had to pick one neighborhood in Paris. The walking, the food, the Jewish quarter, the Place des Vosges.",
      "**6. Kreuzberg, Berlin.** Still the best neighborhood for culture-first urban life in Europe, even after gentrification.",
      "**7. Södermalm, Stockholm.** Stockholm's hippest island, with better views than anywhere else on the list.",
      "**8. Oltrarno, Florence.** Florence's left bank — artisan workshops, great trattorias, real neighborhood life.",
      "**9. De Pijp, Amsterdam.** The Albert Cuyp market, the best coffee in Amsterdam, a residential core that still works.",
      "**10. Lavapiés, Madrid.** The most multicultural neighborhood on this list, and one of the most alive.",
    ],
  },
  {
    slug: 'asia-s-most-walkable-cities',
    title: "Asia's most walkable cities (and the neighborhoods inside them)",
    excerpt: "Asia's megacities are often called impossible to walk. That is half-true. Here are the exceptions.",
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-08',
    tags: ['asia', 'walking', 'guide'],
    body: [
      "Asia's megacities have a reputation for being impossible to walk. That is half-true. The highways and the scale are often intimidating, but almost every major Asian city has pockets — sometimes small, sometimes enormous — that are as walkable as anywhere in Europe.",
      "**Tokyo** is the hidden champion. The density of small streets and shop-lined alleyways makes most of central Tokyo extraordinarily walkable. Shimokitazawa, Yanaka, Shibuya, Daikanyama, the alleys of Shinjuku — every one a walking city unto itself.",
      "**Seoul** has been a revelation of the last decade. Seongsu-dong, Ikseon-dong's hanok alleys, Yeonnam-dong along the Gyeongui Line Forest — Seoul is now one of the best walking cities in Asia.",
      "**Singapore** is Asia's most planned walkable city. Tiong Bahru, Kampong Glam, Katong and Chinatown are all proper walking neighborhoods, well-shaded, well-signposted.",
      "**Bangkok** surprises people. The sois off Sukhumvit — Ari, Thonglor, Ekkamai — are deeply walkable once you are inside them. The challenge is crossing main roads.",
      "**Chiang Mai** is all walkable. The Old City within the moat is a proper walking town.",
      "**Hanoi**'s Old Quarter is one of the best walking districts in Asia, chaos and all.",
      "What these neighborhoods share: human-scaled blocks, street food, narrow lanes, and a density of interesting things per meter walked. In that respect, Asia's best neighborhoods are not so different from Europe's.",
    ],
  },
  {
    slug: 'the-coffee-test',
    title: 'The Coffee Test: what espresso tells you about a neighborhood',
    excerpt: 'Every great neighborhood has great coffee. The reverse is almost always true too.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-05',
    tags: ['food', 'coffee', 'travel-tips'],
    body: [
      "Every great neighborhood has at least one excellent café. The reverse is almost always true too: a neighborhood that has no good coffee is almost certainly a neighborhood that does not work for us.",
      "This is not because coffee matters so much in itself. It is because what it takes to sustain a great independent café — knowledgeable customers, enough density that a small business can survive on regulars, a neighborhood that values craft over convenience — is the same thing that makes a neighborhood great overall.",
      "The shortcut: on your first day in a new neighborhood, walk for 10 minutes in any direction and count independent specialty coffee shops. If you count three or more, you are in a neighborhood worth exploring. If you count zero and only see chains, move on.",
      "This test cuts ruthlessly against travel brochures. Many famously 'beautiful' neighborhoods fail it — because beauty without a daily local rhythm is just a film set. The Coffee Test is one of the simplest ways to tell the two apart.",
      "If you want a starting point: Melbourne's Fitzroy, Copenhagen's Nørrebro, Seoul's Yeonnam-dong, Wellington's Cuba Street, Mexico City's Condesa, and Brooklyn's Williamsburg would all score eight or more on our ten-minute walk. That is not an accident.",
    ],
  },
  {
    slug: 'the-case-against-central-business-districts',
    title: 'The case against central business districts',
    excerpt: "CBDs look central on the map. They are usually the worst place to stay.",
    author: '50 Best Neighborhoods Editorial',
    date: '2026-03-02',
    tags: ['travel-tips', 'hotels'],
    body: [
      "Central business districts look appealing on the map because they are in the middle. That is their only virtue. Almost everything else about them is bad.",
      "CBDs empty out at night. The restaurants close at 9 PM because their office-worker lunch clientele has gone home. The streets feel dead after dark — not dangerous, just sterile. The hotels are designed for business travelers, which means chain properties, uninspired breakfast, and a clientele that disappears on weekends, taking the life of the building with them.",
      "CBDs are rarely walkable in any meaningful sense. They are walkable for office workers between their office and the nearest lunch spot. For visitors trying to have a city experience, they are dead zones that you will spend your trip leaving.",
      "Examples you should avoid: the City in London (beautiful architecture, no life after 6 PM), Downtown Washington, DC (closed on weekends), Frankfurt's banking district, Makati's Ayala business strip (convenient but lifeless), Singapore's Raffles Place after dark.",
      "The alternative is always a residential neighborhood adjacent to the CBD. Shoreditch instead of the City. Mount Pleasant instead of downtown Vancouver. Poblacion instead of Ayala. Kreuzberg instead of Potsdamer Platz. You will pay less for your hotel and have a much better trip.",
    ],
  },
  {
    slug: 'the-neighborhood-dinner-rule',
    title: 'The Neighborhood Dinner Rule: eat where you are, not where Google tells you',
    excerpt: 'The best dinner in a new city is almost never the one with the most Google reviews.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-28',
    tags: ['food', 'travel-tips'],
    body: [
      "Here is a simple rule we live by: on the first night in a new neighborhood, eat at the closest restaurant that passes a three-part test. One, it is full of locals. Two, the menu is in the local language. Three, the staff are unhurried — nobody is trying to upsell you anything.",
      "That is it. Do not look at Google reviews. Do not consult a 'best of' list. Walk out of your hotel, walk for ten minutes in the direction that looks most alive, and pick the restaurant that matches those three criteria.",
      "This almost always produces a better dinner than following Google. The reason is that Google reviews reward tourist-optimized restaurants — the ones with English menus, Instagram decor, and staff trained to smile for photos. Those restaurants are not bad, but they are rarely great. Great neighborhood restaurants are too busy feeding locals to care about the global review economy.",
      "The second-night rule: ask the locals you met at dinner where they would eat tomorrow. Every great meal we have ever had in a new city came from a recommendation given over the table at another meal. Never from the internet.",
    ],
  },
  {
    slug: 'where-to-stay-in-paris-by-trip-type',
    title: 'Where to stay in Paris, by trip type',
    excerpt: 'Paris is not one city — it is twenty. Here is how to pick the right arrondissement for the trip you are actually taking.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-25',
    tags: ['paris', 'hotels', 'guide'],
    body: [
      "Paris's twenty arrondissements spiral clockwise from the center, and choosing between them is the most important decision of a Paris trip. Here is our shortlist by trip type.",
      "**First-time trip, must see the monuments.** Le Marais (3rd/4th). Central, walkable, fifteen minutes from every major site. Expensive, but justifiable.",
      "**Food-focused trip.** The 11th arrondissement, particularly around Oberkampf and Rue Paul Bert. Best concentration of neo-bistros in the city.",
      "**Bohemian, artist-Paris fantasy trip.** Montmartre (18th). Yes, it is touristy around Sacré-Cœur, but the quiet streets behind the basilica are the real thing.",
      "**Literary, Left Bank trip.** Saint-Germain-des-Prés (6th). Expensive, elegant, and walking distance from the Musée d'Orsay, Luxembourg Gardens, and the best bookshops in Europe.",
      "**Quiet, local Paris trip.** Canal Saint-Martin (10th). The most 'neighborhood' feel of any central Paris district.",
      "**Budget-conscious, young Paris trip.** Belleville (20th) or République (11th). Diverse, energetic, and noticeably cheaper than Paris proper.",
      "**Second-time Paris trip.** The 11th or the 9th (SoPi/South Pigalle). Both are cool without being loud, with great food and genuine Parisian life.",
      "Rule of thumb for all of them: Paris is at its best when you can walk out of your hotel and be at a café within two minutes. All of the above pass that test.",
    ],
  },
  {
    slug: 'the-return-of-the-mediterranean-summer',
    title: 'The return of the Mediterranean summer (and where to stay to enjoy it)',
    excerpt: 'Climate change is rewriting the summer travel calendar. Here is how we are adapting.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-22',
    tags: ['summer', 'mediterranean', 'climate'],
    body: [
      "The Mediterranean summer has become unpredictable in a way it was not twenty years ago. Peak July and August now routinely deliver heatwaves in the mid-40s Celsius in southern Spain, Italy and Greece. The traditional 'visit in July' advice that dominated travel writing for decades is quietly being replaced.",
      "Our current recommendation is to travel in May, June, and mid-September. The weather is warm but not hostile, the crowds are thinner, the prices are lower, and you can still walk through a city at 2 PM without planning your route between air-conditioned spaces.",
      "For summer itself, we prefer neighborhoods that have meaningful shade, proximity to water, and strong evening life. Examples: Trastevere in Rome (shade, river, evening aperitivos), Gràcia in Barcelona (trees, smaller plazas, elevation), Alfama in Lisbon (coastal breeze and miradouros), Vedado in Havana (grid of tree-lined streets).",
      "Neighborhoods to avoid in mid-summer heat: Seville's tourist core, central Athens, Naples' Quartieri Spagnoli (beautiful but a heat trap), Madrid's Sol. These places are wonderful in May and October. In August they can be genuinely dangerous.",
    ],
  },
  {
    slug: 'the-underrated-art-of-the-city-walk',
    title: 'The underrated art of the aimless city walk',
    excerpt: 'The best way to understand a neighborhood is to walk it with no agenda whatsoever.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-19',
    tags: ['travel-philosophy', 'walking'],
    body: [
      "The best thing you can do in any new neighborhood is also the simplest: leave your hotel in the morning with no plan at all, and walk until you are hungry. No monuments. No museums. No 'must-see' list.",
      "This is the technique the French call flânerie, and it is the only reliable way to actually understand a neighborhood. You will see things you would never see on a guided walk: how locals greet each other, where the school run happens, which corners are noisy at lunch, which streets are deserted at 3 PM, where the old men play chess.",
      "The mistake most travelers make is trying to optimize. They plan routes, they tick off landmarks, they chase the perfect photo spot. All of which produces the same trip everyone else has. The aimless walker, by contrast, leaves with a story nobody else has.",
      "Our suggestion: dedicate the first morning of every trip to a walk with no destination. You will thank us for the rest of your stay.",
    ],
  },
  {
    slug: 'neighborhood-safety-the-honest-version',
    title: 'Neighborhood safety: the honest version',
    excerpt: 'How to think about safety in an unfamiliar neighborhood, without falling for panic or complacency.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-16',
    tags: ['safety', 'travel-tips'],
    body: [
      "Safety advice about neighborhoods is almost always either too panicked or too casual. The panicked version tells you not to leave your hotel after dark in any city in Latin America. The casual version tells you that 'anywhere is fine if you just pay attention'. Both are useless.",
      "Our honest version: 99% of tourist crime is opportunistic theft — pickpocketing, bag-snatching, distraction scams. It happens disproportionately in crowded tourist areas during the day, not in 'sketchy' neighborhoods at night. The Las Ramblas, the Trevi Fountain, the metro between Gare du Nord and Châtelet. Not the dark alley your guidebook warned you about.",
      "Real safety advice is almost boring: do not carry valuables you do not need, keep your phone in a front pocket, stay on busy streets at night, do not get into unmarked taxis, trust your gut if something feels off. That covers about 95% of cases.",
      "The other 5% is neighborhood-specific. Before you go, ask a local where not to walk after dark. Every major city has two or three such blocks. The information is easy to get if you ask. And crucially, those blocks are almost never the ones travel-safety articles warn you about.",
    ],
  },
  {
    slug: 'why-neighborhood-hotels-beat-international-chains',
    title: 'Why a neighborhood boutique hotel will always beat an international chain',
    excerpt: 'You will pay the same and have a better trip. Here is the math.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-13',
    tags: ['hotels', 'travel-tips'],
    body: [
      "The traditional logic for booking an international chain — 'I know what I am getting' — has quietly broken down. The quality-floor chains used to promise is no longer meaningfully different from what you can expect at a good independent hotel, and the upside of an independent is much, much higher.",
      "Consider: an international chain in Lisbon will cost you roughly the same per night as the best boutique hotel in Príncipe Real or the Baixa. The chain will give you a standardized room, a standardized breakfast, and a staff trained on a corporate script. The boutique will give you a room with character, a breakfast sourced from local bakeries, and a concierge who actually knows the city.",
      "More importantly: boutique hotels are almost always in better neighborhoods. Chains cluster around airports, convention centers, and tourist strips because that is where their corporate clients are. Boutiques cluster in the neighborhoods locals actually want to live in — which, as we have been arguing all along, is where you want to be.",
      "Our recommendation: next time, pick your neighborhood first, then book the best small hotel in that neighborhood. You will pay roughly the same as a chain, and you will have a trip you actually remember.",
    ],
  },
  {
    slug: 'the-best-neighborhoods-for-rainy-days',
    title: 'The best neighborhoods for a rainy day',
    excerpt: 'Some neighborhoods are made for sunshine. These are made for bad weather.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-10',
    tags: ['weather', 'guide'],
    body: [
      "A rainy day in a great city should be no less great. The trick is picking a neighborhood with enough indoor density — bookshops, cafés, museums, covered markets, hotel bars — that the weather becomes a backdrop rather than a problem.",
      "Our favorites worldwide:",
      "**Paris's 6th arrondissement.** Bookshops, covered passages, Saint-Germain hotel bars. Rainy Paris at its most romantic.",
      "**London's Bloomsbury.** The British Museum, Persephone Books, Waterstones Gower Street, and endless cafés. A full rainy day is a feature, not a bug.",
      "**Tokyo's Jimbocho.** The world's densest concentration of second-hand bookshops, many with cafés attached.",
      "**Porto's Ribeira.** The port tasting rooms alone justify a rainy afternoon.",
      "**Copenhagen's Vesterbro.** Kødbyen's covered courtyards, Vesterbro's cafés, the Meatpacking District's bars.",
      "**Vienna's Innere Stadt.** Coffeehouses that have been designed to absorb rainy afternoons for 200 years.",
      "**Seoul's Insa-dong.** Tea houses, galleries and covered arcades designed for exactly this weather.",
      "Rain is not a trip-ruiner. A bad neighborhood is. Book the right one and you will remember the rain fondly.",
    ],
  },
  {
    slug: 'latin-america-next-wave',
    title: "Latin America's next wave: six neighborhoods getting talked about in 2026",
    excerpt: 'The Latin American neighborhoods our editors are visiting this year.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-07',
    tags: ['latin-america', 'cities'],
    body: [
      "Every few years, a new neighborhood in Latin America breaks through. Roma Norte did it in the 2010s. Palermo Soho did it before that. These are the six districts our editors are watching in 2026.",
      "**1. Laureles, Medellín.** The cooler, more local sister of El Poblado. The best evening walk in Colombia right now.",
      "**2. Getsemaní, Cartagena.** The Getsemaní of ten years ago was a backpacker quarter. Today it is arguably the most interesting walled-city-adjacent neighborhood in Latin America.",
      "**3. Barranco, Lima.** Barranco has been 'the next thing' for a decade, and it is finally living up to it. The bar and restaurant scene is now serious.",
      "**4. Bellavista, Santiago.** Santiago's bohemian heart continues to punch above its weight. The best murals in South America.",
      "**5. Barrio Italia, Santiago.** Antique shops and design workshops in a neighborhood that feels hand-crafted.",
      "**6. La Floresta, Quito.** Quito's quietly excellent bohemian district is one of our editors' favorites in the Andes.",
      "City guides for all six are live on the site. The common thread: warmth, walkability, and the kind of neighborhood identity that tourist districts can never manufacture.",
    ],
  },
  {
    slug: 'the-tiny-bar-rule',
    title: 'The Tiny Bar Rule: why the best drinks are always in the smallest rooms',
    excerpt: 'Almost every great bar we have ever loved had fewer than 20 seats. Here is why.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-04',
    tags: ['bars', 'nightlife', 'guide'],
    body: [
      "Think of the best bar you have ever been to. Really think. Now count how many seats it had.",
      "If your answer is 'fewer than twenty', you are not alone. Almost every great bar in the world — the kind you will remember years later — is tiny. Tokyo's Golden Gai bars seat six people. London's best cocktail bars seat twelve. New York's best speakeasies seat fifteen. This is not a coincidence.",
      "Small bars are great because they force intimacy. The bartender becomes an actual person. Other customers become temporary friends. The room has an acoustic where conversation actually works. Staff know when to leave you alone.",
      "Big bars can never do this. They are designed around throughput. Every great big bar we have ever been to was essentially a great small bar that outgrew its building and never quite kept the soul.",
      "Our rule of thumb: when a local recommends a bar, ask how many people it seats. If the answer is 'about twelve', go tonight. If the answer is 'it is big, they always have room', file it away for another time.",
    ],
  },
  {
    slug: 'what-a-good-neighborhood-market-tells-you',
    title: 'What a good neighborhood market tells you about a city',
    excerpt: 'Every great city has a great neighborhood market. Here is how to read one.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-02-01',
    tags: ['food', 'markets', 'guide'],
    body: [
      "Every great neighborhood has a market, and every great market tells a story about its neighborhood. Walk through it carefully and you learn more than any guidebook will ever tell you.",
      "What to look for:",
      "**Who is shopping?** If it is mostly tourists with cameras, the market is a tourist attraction, not a market. Move along. If it is locals with wheeled shopping trolleys, this is a real market, and the neighborhood around it is probably a real neighborhood.",
      "**What is in season?** A good market is a calendar of what the region eats right now. White asparagus in April means you are in Northern Europe in spring. Tropical fruit you cannot identify means you are in Southeast Asia.",
      "**How specialized are the stalls?** One stall selling only olives means the olive-eating is serious. One stall selling 'everything' means the market is for shoppers who do not care.",
      "**Is there prepared food to eat on-site?** A market with a dozen tiny counters selling grilled fish, tortas, bánh mì, arepas, whatever the local snack food is — that is the mark of a market that is alive for locals.",
      "Our favorites worldwide: Mercado de San Miguel in Madrid (increasingly touristy but still excellent), Mercado Roma in Mexico City, Tsukiji's outer market in Tokyo, Borough Market in London (on weekdays only), Marché Bastille in Paris (Thursday and Sunday), the Testaccio market in Rome, Boqueria in Barcelona (early morning, before the tourists).",
    ],
  },
  {
    slug: 'the-case-for-slow-travel-neighborhoods',
    title: 'The case for slow travel, and the neighborhoods it needs',
    excerpt: 'Three days in a city is tourism. Three weeks is travel. Here is where to spend the three weeks.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-29',
    tags: ['slow-travel', 'travel-philosophy'],
    body: [
      "Three days in a city is tourism. You tick off the monuments, you eat one or two good meals, you come home with a photo of the cathedral. Three weeks in a single neighborhood is something else entirely. You learn the streets. You develop opinions about the bakeries. You find a café where the staff recognize you.",
      "The neighborhoods that reward slow travel are a specific kind. They need to have enough variety that three weeks does not exhaust them. They need to be walkable enough that daily errands are pleasant, not a logistical headache. They need enough residential density that the rhythm of the place is real — school runs, grocery shopping, evening walks — not performed for tourists.",
      "Our favorites for a three-week stay:",
      "**Europe:** Alfama (Lisbon), Oltrarno (Florence), Kreuzberg (Berlin), Le Marais (Paris), Gràcia (Barcelona), Södermalm (Stockholm).",
      "**Asia:** Shimokitazawa (Tokyo), Tiong Bahru (Singapore), Hanoi Old Quarter, Nimmanhaemin (Chiang Mai), Seongsu-dong (Seoul).",
      "**Americas:** Condesa (Mexico City), Mile End (Montreal), Palermo Soho (Buenos Aires), Brooklyn Heights (New York), Bernal Heights (San Francisco).",
      "Three weeks in one of these beats three days in five cities, every single time.",
    ],
  },
  {
    slug: 'how-we-rank-neighborhoods',
    title: 'How we actually rank the neighborhoods on this site',
    excerpt: 'A transparent look at the editorial process behind our rankings.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-26',
    tags: ['editorial', 'about'],
    body: [
      "A few readers have asked how we actually decide which neighborhoods make our lists. The honest answer is that it is editorial — we read widely, we travel, we synthesize — but there is more structure behind the process than that implies.",
      "**Step 1: collect external rankings.** For every city, we pull rankings from Time Out, Condé Nast Traveler, The New York Times, The Guardian, Monocle, Culture Trip, and the best local travel press. If a neighborhood appears in three or more of these, it is a serious contender.",
      "**Step 2: weight for walkability, café density, and residential life.** We deliberately down-weight neighborhoods that are interesting mainly because of a single museum or monument. A great neighborhood must function as a place to live.",
      "**Step 3: consult local experts where we can.** Our editors live in or regularly visit about 30 of the cities on the site. For the rest, we rely on conversations with locals we trust — journalists, chefs, hotel concierges, restaurant owners.",
      "**Step 4: our editorial call.** After the quantitative and qualitative input, the final ranking is an editorial decision. We pick the five neighborhoods per city that best represent the range of what a traveler should see, not just the five most famous ones.",
      "The process is imperfect. We miss things. We take reader feedback seriously — if you think we are wrong about your city, tell us. Our job is to update.",
    ],
  },
  {
    slug: 'neighborhood-cafe-culture-by-city',
    title: 'Neighborhood café culture, by city',
    excerpt: 'Every great city has its own café ritual. Here is how to decode it.',
    author: '50 Best Neighborhoods Editorial',
    date: '2026-01-23',
    tags: ['cafes', 'food', 'guide'],
    body: [
      "Café culture is the single most reliable indicator of a great neighborhood, but the rituals vary wildly from city to city. Here is a short decoder for the ones we visit most.",
      "**Italy.** Stand at the bar, order an espresso, drink it in 60 seconds, pay, leave. Sitting at a table after 11 AM often means a 300% price markup. Locals never order a cappuccino after noon.",
      "**France.** Sitting is the whole point. Nursing one coffee for an hour while watching the street is not rude — it is the entire culture. Do not tip on coffee alone; a couple of coins is enough.",
      "**Vienna.** Coffeehouses are living rooms. You can sit for three hours reading a newspaper, and the waiter will not hurry you. A Melange is the local order; ask for it, not a 'cappuccino'.",
      "**Japan.** Two cultures in parallel. Traditional kissaten are slow, quiet, with classical music and 1960s decor. Specialty third-wave cafés serve the most precisely-brewed coffee on Earth. Both reward patience and silence.",
      "**Australia & New Zealand.** The inventors of modern café culture. Flat whites are the default. Baristas take their craft seriously to a degree unknown anywhere else. Brunch is an institution.",
      "**Nordics.** Coffee is not a ceremony, it is fuel, but the fuel is excellent. Expect single-origin, light-roast, pour-over culture. The fika break in Sweden is the exception — a daily social pause built around coffee and a pastry.",
      "When in doubt: watch what locals do, do the same.",
    ],
  },
];

export function getAllPosts() {
  return [...POSTS].sort((a, b) => (a.date < b.date ? 1 : -1));
}

export function getPost(slug) {
  return POSTS.find((p) => p.slug === slug);
}
