// lib/neighborhood-data.js
// Flagship dataset: 20 major world cities × 5 editorially ranked neighborhoods.
// Each entry: name, city, country, cityRank (1-5), tag, blurb, population est, sources[].
// Sources are short fair-use attributions linking back to the original publication.
// Expand incrementally — see scripts/README for data pipeline.

export const NEIGHBORHOODS = [
  // ─── NEW YORK ───
  { name: "Williamsburg", city: "New York", country: "United States", cityRank: 1, tag: "The creative capital of Brooklyn", blurb: "Once industrial, now a global shorthand for hip — Williamsburg is where New York's indie music, third-wave coffee and warehouse-gallery scenes took root. Smorgasburg on Saturdays, vintage shopping on Bedford Avenue, and some of the best rooftop bars in the five boroughs.", sources: [{ pub: "Time Out New York", url: "https://www.timeout.com/newyork/neighborhoods" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/new-york-city" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel/new-york" }] },
  { name: "West Village", city: "New York", country: "United States", cityRank: 2, tag: "Cobblestone charm in the heart of Manhattan", blurb: "Tree-lined streets, Federal-style townhouses and an intimate village feel unlike anywhere else in Manhattan. The West Village remains New York's most romantic neighborhood — home to landmark jazz clubs, tucked-away wine bars, and some of the city's most celebrated restaurants.", sources: [{ pub: "Time Out New York", url: "https://www.timeout.com/newyork" }, { pub: "Eater NY", url: "https://ny.eater.com/maps" }, { pub: "The Infatuation", url: "https://www.theinfatuation.com/new-york" }] },
  { name: "Lower East Side", city: "New York", country: "United States", cityRank: 3, tag: "Where old New York meets the new avant-garde", blurb: "The LES wears its tenement history on its sleeve while hosting some of the city's most forward-looking galleries, cocktail bars and natural-wine restaurants. Dimes Square is the current epicenter, but Orchard and Ludlow still deliver the grit.", sources: [{ pub: "Time Out New York", url: "https://www.timeout.com/newyork" }, { pub: "New York Magazine", url: "https://nymag.com/strategist" }, { pub: "Eater NY", url: "https://ny.eater.com" }] },
  { name: "Harlem", city: "New York", country: "United States", cityRank: 4, tag: "The cultural soul of Uptown", blurb: "From the Apollo Theater to Sylvia's soul food, Harlem's cultural legacy runs deeper than any other American neighborhood. A wave of new restaurants, jazz clubs and boutique hotels along Lenox Avenue is writing the next chapter.", sources: [{ pub: "The New York Times", url: "https://www.nytimes.com/section/nyregion" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "Time Out New York", url: "https://www.timeout.com/newyork" }] },
  { name: "SoHo", city: "New York", country: "United States", cityRank: 5, tag: "Cast-iron architecture meets world-class shopping", blurb: "The birthplace of the New York loft and still the city's most concentrated luxury shopping district. Behind the flagship stores, SoHo's cast-iron facades, cobblestone streets and hidden galleries reward anyone willing to look up.", sources: [{ pub: "Time Out New York", url: "https://www.timeout.com/newyork" }, { pub: "Vogue", url: "https://www.vogue.com/tag/city/new-york-city" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },

  // ─── LONDON ───
  { name: "Shoreditch", city: "London", country: "United Kingdom", cityRank: 1, tag: "East London's creative engine room", blurb: "Street art on Brick Lane, warehouse parties off Old Street, and the densest concentration of independent coffee, cocktail bars and design studios in the UK. Shoreditch set the template for every 'hip neighborhood' piece written about London in the past fifteen years — and still somehow stays ahead.", sources: [{ pub: "Time Out London", url: "https://www.timeout.com/london/neighbourhoods" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/london" }, { pub: "Condé Nast Traveller UK", url: "https://www.cntraveller.com/gallery/best-neighbourhoods-london" }] },
  { name: "Notting Hill", city: "London", country: "United Kingdom", cityRank: 2, tag: "Pastel houses and Portobello treasures", blurb: "Forget the film — the real Notting Hill is Portobello Market on a Friday morning, the Electric Cinema on Portobello Road, and rows of pastel-painted houses that photograph beautifully in any weather. Still London's most picture-perfect neighborhood.", sources: [{ pub: "Time Out London", url: "https://www.timeout.com/london" }, { pub: "Condé Nast Traveller UK", url: "https://www.cntraveller.com" }, { pub: "The Telegraph", url: "https://www.telegraph.co.uk/travel/destinations/europe/united-kingdom/england/london" }] },
  { name: "Soho", city: "London", country: "United Kingdom", cityRank: 3, tag: "London's beating, neon-lit heart", blurb: "Theatreland, Chinatown, the last of the old Berwick Street record shops and a drinking scene that has defined London nightlife for three centuries. Soho is noisy, messy and absolutely essential — there is nowhere else like it in Europe.", sources: [{ pub: "Time Out London", url: "https://www.timeout.com/london" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/london" }, { pub: "Evening Standard", url: "https://www.standard.co.uk/going-out" }] },
  { name: "Peckham", city: "London", country: "United Kingdom", cityRank: 4, tag: "South London's coolest rooftop", blurb: "Frank's Café on top of a multi-storey car park gave Peckham its reputation; the wave of galleries, independent restaurants and record bars on Bellenden Road cemented it. The most talked-about neighborhood south of the river.", sources: [{ pub: "Time Out London", url: "https://www.timeout.com/london" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/london" }, { pub: "Evening Standard", url: "https://www.standard.co.uk" }] },
  { name: "Hackney", city: "London", country: "United Kingdom", cityRank: 5, tag: "Canal-side cool and killer coffee", blurb: "Broadway Market on a Saturday, London Fields in summer, and a relentless wave of new bakeries, natural-wine bars and design studios spreading outward from Mare Street. Hackney is where London's creatives actually live.", sources: [{ pub: "Time Out London", url: "https://www.timeout.com/london" }, { pub: "Condé Nast Traveller UK", url: "https://www.cntraveller.com" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/london" }] },

  // ─── PARIS ───
  { name: "Le Marais", city: "Paris", country: "France", cityRank: 1, tag: "Medieval Paris, perfectly preserved", blurb: "The only major district of Paris untouched by Haussmann's rebuild, Le Marais keeps its medieval street plan, Renaissance mansions and Jewish, LGBTQ+ and artistic heritage in extraordinary balance. The Place des Vosges is arguably the most beautiful square in the city.", sources: [{ pub: "Time Out Paris", url: "https://www.timeout.com/paris/en" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/paris" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },
  { name: "Canal Saint-Martin", city: "Paris", country: "France", cityRank: 2, tag: "Where Paris comes to picnic", blurb: "Iron footbridges, tree-lined quays and the city's best apéro scene when the sun shines. The streets around the canal have become the natural habitat of young Parisian designers, booksellers and pastry chefs — and remain refreshingly un-touristed.", sources: [{ pub: "Time Out Paris", url: "https://www.timeout.com/paris/en" }, { pub: "Le Figaro", url: "https://www.lefigaro.fr/sortir-paris" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "Montmartre", city: "Paris", country: "France", cityRank: 3, tag: "Bohemian Paris on the hill", blurb: "Yes, it's touristy around Sacré-Cœur, but walk five minutes in any direction and Montmartre becomes the village it has always been — a maze of staircases, hidden vineyards, cabaret history and the kind of Parisian views that justify the climb.", sources: [{ pub: "Time Out Paris", url: "https://www.timeout.com/paris/en" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/paris" }] },
  { name: "Belleville", city: "Paris", country: "France", cityRank: 4, tag: "Paris at its most cosmopolitan", blurb: "Climb the Parc de Belleville for arguably the best skyline view in Paris, then descend into the city's most diverse neighborhood — a layered map of North African, Chinese, Vietnamese and artist-studio Paris that feels a world away from the postcard version.", sources: [{ pub: "Time Out Paris", url: "https://www.timeout.com/paris/en" }, { pub: "Le Monde", url: "https://www.lemonde.fr/en/m-le-mag" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },
  { name: "Saint-Germain-des-Prés", city: "Paris", country: "France", cityRank: 5, tag: "Intellectual Paris in cashmere and linen", blurb: "The Left Bank neighborhood that hosted Sartre, de Beauvoir and Hemingway still does literary lunches better than anywhere in the city. Café de Flore, Les Deux Magots, the publishing houses along Rue de Seine — Saint-Germain at its best is quiet, elegant and quietly expensive.", sources: [{ pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "Time Out Paris", url: "https://www.timeout.com/paris/en" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },

  // ─── TOKYO ───
  { name: "Shimokitazawa", city: "Tokyo", country: "Japan", cityRank: 1, tag: "Tokyo's indie soul", blurb: "Vintage clothing, tiny live-music venues, second-hand bookstores and the densest concentration of specialty coffee shops in Tokyo. 'Shimokita' has resisted high-rise development and remains the most walkable, most human-scaled neighborhood in the city.", sources: [{ pub: "Time Out Tokyo", url: "https://www.timeout.com/tokyo" }, { pub: "The Japan Times", url: "https://www.japantimes.co.jp/life/" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/tokyo" }] },
  { name: "Shibuya", city: "Tokyo", country: "Japan", cityRank: 2, tag: "The world's most famous crosswalk", blurb: "The Shibuya Scramble is the image most people associate with Tokyo, but the real neighborhood begins in the side streets — Udagawacho for records, Dogenzaka for live houses, Shibuya Yokocho for late-night yakitori. The heart of Japanese youth culture.", sources: [{ pub: "Time Out Tokyo", url: "https://www.timeout.com/tokyo" }, { pub: "The Japan Times", url: "https://www.japantimes.co.jp" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },
  { name: "Daikanyama", city: "Tokyo", country: "Japan", cityRank: 3, tag: "Tokyo's quiet luxury village", blurb: "The T-Site bookstore is justifiably famous, but Daikanyama's real appeal is its quiet, low-rise streets — a rare corner of central Tokyo designed for walking, browsing and lingering in design-forward cafés. The Brooklyn of Tokyo, if Brooklyn were neater.", sources: [{ pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "Time Out Tokyo", url: "https://www.timeout.com/tokyo" }, { pub: "Monocle", url: "https://monocle.com" }] },
  { name: "Yanaka", city: "Tokyo", country: "Japan", cityRank: 4, tag: "Old Tokyo frozen in time", blurb: "One of the few neighborhoods that escaped both the 1923 earthquake and WWII firebombings, Yanaka retains the wooden houses, narrow lanes and temple-lined streets of pre-war Tokyo. The Yanaka Ginza shopping street feels like time travel.", sources: [{ pub: "The Japan Times", url: "https://www.japantimes.co.jp" }, { pub: "Time Out Tokyo", url: "https://www.timeout.com/tokyo" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },
  { name: "Shinjuku", city: "Tokyo", country: "Japan", cityRank: 5, tag: "Neon, skyscrapers and Golden Gai", blurb: "Shinjuku contains multitudes — the world's busiest train station, Godzilla-sized neon billboards, department stores, Kabukicho's red-light district and Golden Gai's six square blocks of tiny bars. The most intense concentration of city on Earth.", sources: [{ pub: "Time Out Tokyo", url: "https://www.timeout.com/tokyo" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/tokyo" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },

  // ─── BERLIN ───
  { name: "Kreuzberg", city: "Berlin", country: "Germany", cityRank: 1, tag: "Berlin's punk heart, still beating", blurb: "From the Turkish market on Maybachufer to the clubs along the Spree, Kreuzberg is where Berlin's counterculture was forged and still lives. Gentrification is reshaping it, but Oranienstraße at midnight still feels exactly like it should.", sources: [{ pub: "Time Out Berlin", url: "https://www.timeout.com/berlin" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/berlin" }, { pub: "Der Tagesspiegel", url: "https://www.tagesspiegel.de" }] },
  { name: "Neukölln", city: "Berlin", country: "Germany", cityRank: 2, tag: "Where Berlin moves next", blurb: "Kreuzberg's younger sibling has become the most talked-about neighborhood in Berlin — Weserstraße for bars, Sonnenallee for Middle Eastern food, Hermannplatz for the kind of unpolished energy central Berlin is losing.", sources: [{ pub: "Time Out Berlin", url: "https://www.timeout.com/berlin" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/berlin" }] },
  { name: "Prenzlauer Berg", city: "Berlin", country: "Germany", cityRank: 3, tag: "Cobblestones, cafés and quiet corners", blurb: "The leafiest, most liveable of Berlin's central districts — Helmholtzplatz on a Saturday morning, independent bookshops on Stargarder Straße, and some of the best third-wave coffee in the city. Gentler than Kreuzberg, and all the more rewarding for it.", sources: [{ pub: "Time Out Berlin", url: "https://www.timeout.com/berlin" }, { pub: "Der Tagesspiegel", url: "https://www.tagesspiegel.de" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/berlin" }] },
  { name: "Friedrichshain", city: "Berlin", country: "Germany", cityRank: 4, tag: "Club capital of the continent", blurb: "Home to Berghain, RAW Gelände and the longest stretch of the East Side Gallery, Friedrichshain remains Berlin's techno heartland. Boxhagener Platz offers a gentler face — brunch, flea markets, and some of the best falafel in the city.", sources: [{ pub: "Resident Advisor", url: "https://ra.co" }, { pub: "Time Out Berlin", url: "https://www.timeout.com/berlin" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/berlin" }] },
  { name: "Mitte", city: "Berlin", country: "Germany", cityRank: 5, tag: "History, galleries and the city's front door", blurb: "The literal middle of Berlin — Museum Island, Brandenburg Gate, the government quarter and the gallery district of Auguststraße. Polished, historic and increasingly expensive, Mitte is Berlin's most international face.", sources: [{ pub: "Time Out Berlin", url: "https://www.timeout.com/berlin" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },

  // ─── BARCELONA ───
  { name: "El Born", city: "Barcelona", country: "Spain", cityRank: 1, tag: "Medieval streets, modern cocktails", blurb: "The tightest, loveliest tangle of lanes in Ciutat Vella — Born has the Picasso Museum, Santa María del Mar, and the city's densest concentration of tapas bars and boutique shops. Every alley rewards aimless wandering.", sources: [{ pub: "Time Out Barcelona", url: "https://www.timeout.com/barcelona/en" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/barcelona" }, { pub: "El País", url: "https://english.elpais.com" }] },
  { name: "Gràcia", city: "Barcelona", country: "Spain", cityRank: 2, tag: "Barcelona's village within the city", blurb: "Once an independent town, Gràcia still feels that way — small plazas filled with families, no high-rises, the Festa Major de Gràcia in August, and some of the city's best vermouth bars along Carrer de Verdi.", sources: [{ pub: "Time Out Barcelona", url: "https://www.timeout.com/barcelona/en" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/barcelona" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "El Raval", city: "Barcelona", country: "Spain", cityRank: 3, tag: "Gritty, global and wildly alive", blurb: "Home to the MACBA, the most diverse population in the city, and a bar scene that ranges from century-old absinthe dens to third-wave coffee roasters. El Raval's reputation for edge is part of its charm.", sources: [{ pub: "Time Out Barcelona", url: "https://www.timeout.com/barcelona/en" }, { pub: "El País", url: "https://english.elpais.com" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/barcelona" }] },
  { name: "Poble Sec", city: "Barcelona", country: "Spain", cityRank: 4, tag: "Tapas on Carrer Blai, sunset on Montjuïc", blurb: "Carrer Blai is one of the great tapa-crawl streets in Spain — pinchos for a euro, standing room only. Climb Montjuïc afterwards for the best free view of Barcelona, and time it for sunset.", sources: [{ pub: "Time Out Barcelona", url: "https://www.timeout.com/barcelona/en" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "El País", url: "https://english.elpais.com" }] },
  { name: "Poblenou", city: "Barcelona", country: "Spain", cityRank: 5, tag: "Barcelona's post-industrial playground", blurb: "The 22@ regeneration turned old textile factories into design studios, co-working spaces and the best flat-white scene in the city. The Rambla del Poblenou stays local; the beach is a five-minute walk.", sources: [{ pub: "Time Out Barcelona", url: "https://www.timeout.com/barcelona/en" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/barcelona" }, { pub: "Monocle", url: "https://monocle.com" }] },

  // ─── MEXICO CITY ───
  { name: "Roma Norte", city: "Mexico City", country: "Mexico", cityRank: 1, tag: "CDMX's creative epicenter", blurb: "Leafy boulevards, art deco apartment blocks and the restaurant-and-bar scene that powered Mexico City's emergence as a global food capital. Álvaro Obregón on a Friday night is unmissable.", sources: [{ pub: "Time Out Mexico City", url: "https://www.timeout.com/mexico-city/en" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/mexico-city" }] },
  { name: "Condesa", city: "Mexico City", country: "Mexico", cityRank: 2, tag: "Art deco, green spaces, great food", blurb: "Roma Norte's next-door neighbor shares the bar scene but adds two of the city's loveliest parks — Parque México and Parque España — plus the best concentration of independent bookshops and coffee roasters in CDMX.", sources: [{ pub: "Time Out Mexico City", url: "https://www.timeout.com/mexico-city/en" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/mexicocity" }] },
  { name: "Coyoacán", city: "Mexico City", country: "Mexico", cityRank: 3, tag: "Frida's cobblestone village", blurb: "The Casa Azul draws the crowds, but Coyoacán's real charm is its weekend plazas, mariachi bands, churros from Mercado de Coyoacán, and streets that feel more like a colonial town than part of a megacity.", sources: [{ pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }, { pub: "Time Out Mexico City", url: "https://www.timeout.com/mexico-city/en" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "Polanco", city: "Mexico City", country: "Mexico", cityRank: 4, tag: "CDMX at its most polished", blurb: "The embassies, the Soumaya Museum, Presidente Masaryk's luxury boutiques, and Pujol — the restaurant that helped put Mexican fine dining on the global map. Polanco is Mexico City's best-dressed neighborhood.", sources: [{ pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }, { pub: "Time Out Mexico City", url: "https://www.timeout.com/mexico-city/en" }] },
  { name: "Centro Histórico", city: "Mexico City", country: "Mexico", cityRank: 5, tag: "The beating, historic heart of CDMX", blurb: "The Zócalo is the second-largest public square in the world; the surrounding streets hold the Templo Mayor, the Palacio de Bellas Artes, century-old cantinas and the kind of noisy, crowded, utterly alive energy that defines Mexico City.", sources: [{ pub: "Time Out Mexico City", url: "https://www.timeout.com/mexico-city/en" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/mexicocity" }] },

  // ─── BUENOS AIRES ───
  { name: "Palermo Soho", city: "Buenos Aires", country: "Argentina", cityRank: 1, tag: "The coolest grid in Latin America", blurb: "Cobblestone streets lined with boutiques, design studios, leafy plazas and the densest bar scene in Buenos Aires. Plaza Serrano is the epicenter; Honduras and Gurruchaga are the best walking streets.", sources: [{ pub: "Time Out Buenos Aires", url: "https://www.timeout.com/buenos-aires" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/buenos-aires" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },
  { name: "San Telmo", city: "Buenos Aires", country: "Argentina", cityRank: 2, tag: "Tango, antiques, Sunday afternoons", blurb: "The oldest neighborhood in Buenos Aires holds the city's best antique market every Sunday, tango shows in Plaza Dorrego, and the cobblestone atmosphere of 19th-century Porteño life. Slow, atmospheric, essential.", sources: [{ pub: "Time Out Buenos Aires", url: "https://www.timeout.com/buenos-aires" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/buenos-aires" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "Recoleta", city: "Buenos Aires", country: "Argentina", cityRank: 3, tag: "Parisian elegance in the Southern Hemisphere", blurb: "Belle Époque mansions, Avenida Alvear's luxury boutiques, the MALBA museum, and the extraordinary Recoleta Cemetery where Evita is buried. The most European-feeling corner of the self-proclaimed 'Paris of South America'.", sources: [{ pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }, { pub: "Time Out Buenos Aires", url: "https://www.timeout.com/buenos-aires" }] },
  { name: "Villa Crespo", city: "Buenos Aires", country: "Argentina", cityRank: 4, tag: "Palermo's quieter, cheaper sibling", blurb: "The creative overflow from Palermo Soho — independent designers, new parrillas, natural-wine bars and a Jewish heritage visible in bakeries and delis along Corrientes. Where locals actually live.", sources: [{ pub: "Time Out Buenos Aires", url: "https://www.timeout.com/buenos-aires" }, { pub: "Clarín", url: "https://www.clarin.com/ciudades" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/buenos-aires" }] },
  { name: "La Boca", city: "Buenos Aires", country: "Argentina", cityRank: 5, tag: "Painted houses and Maradona's ghost", blurb: "Caminito's candy-colored houses are a cliché for a reason, and La Bombonera — Boca Juniors' stadium — is a pilgrimage site for any football fan. Stick to the tourist corridor in daylight; the history makes it worth it.", sources: [{ pub: "Time Out Buenos Aires", url: "https://www.timeout.com/buenos-aires" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/buenos-aires" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },

  // ─── MELBOURNE ───
  { name: "Fitzroy", city: "Melbourne", country: "Australia", cityRank: 1, tag: "Australia's original cool neighborhood", blurb: "Brunswick Street and Gertrude Street gave Melbourne its reputation as Australia's most creative city — bookshops, vintage stores, live music venues and the kind of coffee culture that ruined every other cup forever. Still the benchmark.", sources: [{ pub: "Time Out Melbourne", url: "https://www.timeout.com/melbourne" }, { pub: "The Age", url: "https://www.theage.com.au/lifestyle/melbourne" }, { pub: "Broadsheet Melbourne", url: "https://www.broadsheet.com.au/melbourne" }] },
  { name: "Collingwood", city: "Melbourne", country: "Australia", cityRank: 2, tag: "Fitzroy's rougher, realer neighbor", blurb: "Smith Street is the gentrification frontline and one of the best bar streets in Melbourne — craft breweries, natural-wine bars, restaurants that would be standouts anywhere in the world. Smaller galleries and vintage shops fill the side streets.", sources: [{ pub: "Broadsheet Melbourne", url: "https://www.broadsheet.com.au/melbourne" }, { pub: "Time Out Melbourne", url: "https://www.timeout.com/melbourne" }, { pub: "The Age", url: "https://www.theage.com.au" }] },
  { name: "Brunswick", city: "Melbourne", country: "Australia", cityRank: 3, tag: "Live music and the best pizza in town", blurb: "Sydney Road's Italian heritage is still visible in the cannoli bakeries and pasta shops, but the real draw is the live music scene centered on the Howler, the Retreat Hotel and the Brunswick Green. Melbourne at its most multicultural.", sources: [{ pub: "The Age", url: "https://www.theage.com.au" }, { pub: "Time Out Melbourne", url: "https://www.timeout.com/melbourne" }, { pub: "Broadsheet Melbourne", url: "https://www.broadsheet.com.au/melbourne" }] },
  { name: "St Kilda", city: "Melbourne", country: "Australia", cityRank: 4, tag: "Beachside bohemia", blurb: "Melbourne's original seaside suburb — Luna Park, the St Kilda sea baths, Acland Street's cake shops, and a bar scene that peaks at summer sunset. A little seedy, a little glamorous, uniquely Melbourne.", sources: [{ pub: "Time Out Melbourne", url: "https://www.timeout.com/melbourne" }, { pub: "Broadsheet Melbourne", url: "https://www.broadsheet.com.au/melbourne" }, { pub: "The Age", url: "https://www.theage.com.au" }] },
  { name: "Carlton", city: "Melbourne", country: "Australia", cityRank: 5, tag: "Melbourne's Little Italy, with a PhD", blurb: "Lygon Street's Italian restaurants, the University of Melbourne campus, and two of the city's best green spaces in Carlton Gardens and the Royal Exhibition Building. Old-school Melbourne, done well.", sources: [{ pub: "The Age", url: "https://www.theage.com.au" }, { pub: "Time Out Melbourne", url: "https://www.timeout.com/melbourne" }, { pub: "Broadsheet Melbourne", url: "https://www.broadsheet.com.au/melbourne" }] },

  // ─── SINGAPORE ───
  { name: "Tiong Bahru", city: "Singapore", country: "Singapore", cityRank: 1, tag: "Art deco, hawker food, perfect coffee", blurb: "Singapore's first housing estate, now the city's most design-conscious neighborhood. Low-rise art deco blocks, the Tiong Bahru Market hawker centre, the beloved Tiong Bahru Bakery, and independent bookshops and boutiques filling the ground floors.", sources: [{ pub: "Time Out Singapore", url: "https://www.timeout.com/singapore" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/singapore" }, { pub: "The Straits Times", url: "https://www.straitstimes.com/life" }] },
  { name: "Kampong Glam", city: "Singapore", country: "Singapore", cityRank: 2, tag: "Haji Lane, the Sultan Mosque and street art", blurb: "The historic Malay-Arab quarter — Arab Street for textiles, Haji Lane for street art and independent boutiques, the golden dome of Sultan Mosque anchoring it all. One of the most photogenic corners of Singapore.", sources: [{ pub: "Time Out Singapore", url: "https://www.timeout.com/singapore" }, { pub: "The Straits Times", url: "https://www.straitstimes.com" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "Chinatown", city: "Singapore", country: "Singapore", cityRank: 3, tag: "Hawker heritage meets craft cocktails", blurb: "The Chinatown Complex hawker centre contains Michelin-starred street food; the surrounding shophouses hide Singapore's best speakeasies and craft-cocktail bars. Temple Street for tradition, Ann Siang Hill for the new wave.", sources: [{ pub: "Time Out Singapore", url: "https://www.timeout.com/singapore" }, { pub: "The Straits Times", url: "https://www.straitstimes.com" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "Katong", city: "Singapore", country: "Singapore", cityRank: 4, tag: "Peranakan heritage and laksa perfection", blurb: "Pastel Peranakan shophouses line Joo Chiat Road; 328 Katong Laksa serves what is widely regarded as the best bowl in Singapore. East Coast flavor, away from the skyscrapers.", sources: [{ pub: "The Straits Times", url: "https://www.straitstimes.com" }, { pub: "Time Out Singapore", url: "https://www.timeout.com/singapore" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "Dempsey Hill", city: "Singapore", country: "Singapore", cityRank: 5, tag: "Jungle, restaurants, hidden calm", blurb: "A former British army barracks turned into a leafy enclave of restaurants, art galleries and antique shops surrounded by rainforest. Singapore at its most surprising — and green.", sources: [{ pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "Time Out Singapore", url: "https://www.timeout.com/singapore" }, { pub: "The Straits Times", url: "https://www.straitstimes.com" }] },

  // ─── AMSTERDAM ───
  { name: "Jordaan", city: "Amsterdam", country: "Netherlands", cityRank: 1, tag: "Amsterdam's most charming canals", blurb: "Narrow streets, hidden courtyards (hofjes), the Anne Frank House, and the city's best brown cafés. The Jordaan is postcard Amsterdam without feeling like a postcard.", sources: [{ pub: "Time Out Amsterdam", url: "https://www.timeout.com/amsterdam" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/amsterdam" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/amsterdam" }] },
  { name: "De Pijp", city: "Amsterdam", country: "Netherlands", cityRank: 2, tag: "The Albert Cuyp market and brunch capital", blurb: "De Pijp's Albert Cuypmarkt is the biggest street market in the Netherlands; the surrounding streets hold some of the best coffee, brunch and bar culture in Amsterdam. The Heineken Experience is here, but skip it for the real thing.", sources: [{ pub: "Time Out Amsterdam", url: "https://www.timeout.com/amsterdam" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "NRC Handelsblad", url: "https://www.nrc.nl/" }] },
  { name: "Amsterdam-Oost", city: "Amsterdam", country: "Netherlands", cityRank: 3, tag: "Where Amsterdam actually hangs out", blurb: "Javastraat for multicultural food, Dappermarkt for the city's most diverse market, and the Oosterpark for picnics. Amsterdam Oost is locals-only cool, with excellent coffee and a growing bar scene.", sources: [{ pub: "Time Out Amsterdam", url: "https://www.timeout.com/amsterdam" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/amsterdam" }, { pub: "NRC Handelsblad", url: "https://www.nrc.nl/" }] },
  { name: "Noord", city: "Amsterdam", country: "Netherlands", cityRank: 4, tag: "A free ferry ride to the future", blurb: "The three-minute ferry from Centraal Station delivers you to Amsterdam's most experimental neighborhood — NDSM Wharf for street art and festivals, the A'DAM Lookout for views, and restaurants in converted shipyards.", sources: [{ pub: "Time Out Amsterdam", url: "https://www.timeout.com/amsterdam" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "Monocle", url: "https://monocle.com" }] },
  { name: "De Baarsjes", city: "Amsterdam", country: "Netherlands", cityRank: 5, tag: "Amsterdam-West's quiet rise", blurb: "The stretch around Admiraal de Ruijterweg and the Foodhallen has quietly become the most exciting food-and-drink district in Amsterdam — no tourist coaches, just smart bars, natural-wine joints and some of the city's best new restaurants.", sources: [{ pub: "Time Out Amsterdam", url: "https://www.timeout.com/amsterdam" }, { pub: "NRC Handelsblad", url: "https://www.nrc.nl/" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/amsterdam" }] },

  // ─── BANGKOK ───
  { name: "Ari", city: "Bangkok", country: "Thailand", cityRank: 1, tag: "Bangkok's cool, quiet middle", blurb: "A short BTS ride from downtown, Ari is where Bangkok locals go for independent coffee, design-forward bars and some of the best modern Thai restaurants in the city — without the Sukhumvit crowds.", sources: [{ pub: "Time Out Bangkok", url: "https://www.timeout.com/bangkok" }, { pub: "Bangkok Post", url: "https://www.bangkokpost.com/life" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/bangkok" }] },
  { name: "Thonglor", city: "Bangkok", country: "Thailand", cityRank: 2, tag: "Sukhumvit's nightlife spine", blurb: "Thonglor (Sukhumvit Soi 55) is Bangkok's most concentrated night-out strip — rooftop bars, speakeasies, late-night noodles and clubs that stay open until the last song. Home to some of the best cocktail bars in Asia.", sources: [{ pub: "Time Out Bangkok", url: "https://www.timeout.com/bangkok" }, { pub: "Bangkok Post", url: "https://www.bangkokpost.com" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "Yaowarat (Chinatown)", city: "Bangkok", country: "Thailand", cityRank: 3, tag: "The best street food in Southeast Asia", blurb: "Bangkok's Chinatown, Yaowarat, comes alive after dark with some of the best street food on the planet — fried seafood, noodle soups, Michelin-starred dim sum stalls. Walk the main road, then explore the alleys off it.", sources: [{ pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }, { pub: "Bangkok Post", url: "https://www.bangkokpost.com" }, { pub: "Time Out Bangkok", url: "https://www.timeout.com/bangkok" }] },
  { name: "Ekkamai", city: "Bangkok", country: "Thailand", cityRank: 4, tag: "Thonglor's slower, hipper neighbor", blurb: "Specialty coffee, curated Japanese izakayas, and a string of bars and concept stores along Ekkamai Soi 12. Where Bangkok's design-conscious actually live.", sources: [{ pub: "Time Out Bangkok", url: "https://www.timeout.com/bangkok" }, { pub: "Bangkok Post", url: "https://www.bangkokpost.com" }, { pub: "Monocle", url: "https://monocle.com" }] },
  { name: "Banglamphu", city: "Bangkok", country: "Thailand", cityRank: 5, tag: "Old Bangkok meets Khao San Road", blurb: "Yes, Khao San Road is a backpacker institution, but the surrounding Banglamphu neighborhood holds Old Bangkok at its best — temples, canals, century-old shop houses and some of the best local eats in the city.", sources: [{ pub: "Time Out Bangkok", url: "https://www.timeout.com/bangkok" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/bangkok" }, { pub: "Bangkok Post", url: "https://www.bangkokpost.com" }] },

  // ─── ISTANBUL ───
  { name: "Karaköy", city: "Istanbul", country: "Turkey", cityRank: 1, tag: "Old port, new creative scene", blurb: "Karaköy has transformed from a gritty port district into Istanbul's most design-conscious neighborhood — third-wave coffee, Istanbul Modern, contemporary galleries and some of the best new restaurants in the city, all within sight of the Galata Bridge.", sources: [{ pub: "Time Out Istanbul", url: "https://www.timeout.com/istanbul/en" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/istanbul" }] },
  { name: "Kadıköy", city: "Istanbul", country: "Turkey", cityRank: 2, tag: "Asian-side Istanbul at its liveliest", blurb: "The Kadıköy food market, Moda's seaside cafés, Bar Street on Kadife Sokak and one of the best alternative music scenes in the city. The Asian side remains more local, cheaper and increasingly where young Istanbullus want to live.", sources: [{ pub: "Time Out Istanbul", url: "https://www.timeout.com/istanbul/en" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/istanbul" }, { pub: "Hürriyet Daily News", url: "https://www.hurriyetdailynews.com" }] },
  { name: "Cihangir", city: "Istanbul", country: "Turkey", cityRank: 3, tag: "The writer's neighborhood of Istanbul", blurb: "Orhan Pamuk's beloved Cihangir is the Istanbul of used bookstores, Bosphorus views between apartment buildings, and tiny corner cafés where you can genuinely read a book without being hurried. Exactly as romantic as it sounds.", sources: [{ pub: "Time Out Istanbul", url: "https://www.timeout.com/istanbul/en" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "Balat", city: "Istanbul", country: "Turkey", cityRank: 4, tag: "Istanbul's most photogenic streets", blurb: "Rainbow-colored houses stacked up a hillside above the Golden Horn, a historic Jewish and Greek neighborhood now filling with antique shops, vintage cafés and street art. Instagram-famous, and actually deserves it.", sources: [{ pub: "The Guardian", url: "https://www.theguardian.com/travel/istanbul" }, { pub: "Time Out Istanbul", url: "https://www.timeout.com/istanbul/en" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "Beyoğlu", city: "Istanbul", country: "Turkey", cityRank: 5, tag: "İstiklal Caddesi and the city's nightlife", blurb: "The pedestrian İstiklal Caddesi is Istanbul's main artery — two kilometers of 19th-century architecture, historic passages, bars, meyhanes and music venues. From Taksim to Galata, Beyoğlu is Istanbul at its loudest and liveliest.", sources: [{ pub: "Time Out Istanbul", url: "https://www.timeout.com/istanbul/en" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/istanbul" }, { pub: "Hürriyet Daily News", url: "https://www.hurriyetdailynews.com" }] },

  // ─── SEOUL ───
  { name: "Seongsu-dong", city: "Seoul", country: "South Korea", cityRank: 1, tag: "The Brooklyn of Seoul", blurb: "Old shoe factories turned into design studios, cafés and independent boutiques. Seongsu-dong is Seoul's fastest-evolving neighborhood — concept stores, specialty coffee and pop-up culture at a level only Seoul can deliver.", sources: [{ pub: "Time Out Seoul", url: "https://www.timeout.com/seoul" }, { pub: "The Korea Herald", url: "https://www.koreaherald.com" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/seoul" }] },
  { name: "Ikseon-dong", city: "Seoul", country: "South Korea", cityRank: 2, tag: "Hanok alleys full of hidden cafés", blurb: "A maze of traditional Korean hanok houses converted into some of the prettiest cafés, craft shops and small restaurants in Seoul. Ten minutes from Jongno, worlds away from the high-rises.", sources: [{ pub: "The Korea Herald", url: "https://www.koreaherald.com" }, { pub: "Time Out Seoul", url: "https://www.timeout.com/seoul" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "Hongdae", city: "Seoul", country: "South Korea", cityRank: 3, tag: "Student energy, indie music, 24-hour bars", blurb: "Anchored by Hongik University, Hongdae is Seoul's youth culture capital — indie music venues, street performers, late-night eats and a bar scene that never really closes. Loud, young, essential.", sources: [{ pub: "Time Out Seoul", url: "https://www.timeout.com/seoul" }, { pub: "The Korea Herald", url: "https://www.koreaherald.com" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/seoul" }] },
  { name: "Itaewon", city: "Seoul", country: "South Korea", cityRank: 4, tag: "Seoul's international melting pot", blurb: "Historically the international quarter of Seoul, Itaewon's main strip and the surrounding Gyeongnidan and Haebangchon areas host the best-curated cocktail bars and multicultural restaurants in the city.", sources: [{ pub: "The Korea Herald", url: "https://www.koreaherald.com" }, { pub: "Time Out Seoul", url: "https://www.timeout.com/seoul" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "Yeonnam-dong", city: "Seoul", country: "South Korea", cityRank: 5, tag: "Gyeongui Line Forest, micro-cafés, slow days", blurb: "The reclaimed Gyeongui Line Forest park runs through the heart of Yeonnam-dong, now lined with independent cafés, bookshops and small restaurants. A newer, calmer counterpoint to Hongdae next door.", sources: [{ pub: "Time Out Seoul", url: "https://www.timeout.com/seoul" }, { pub: "The Korea Herald", url: "https://www.koreaherald.com" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },

  // ─── LISBON ───
  { name: "Alfama", city: "Lisbon", country: "Portugal", cityRank: 1, tag: "Fado, tiles, cobblestones", blurb: "Lisbon's oldest neighborhood — a medieval tangle of lanes climbing from the Tejo to the Castelo de São Jorge. Miradouros for views, fado houses for the national soul, and the Feira da Ladra flea market on Tuesdays and Saturdays.", sources: [{ pub: "Time Out Lisbon", url: "https://www.timeout.com/lisbon" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/lisbon" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/lisbon" }] },
  { name: "Príncipe Real", city: "Lisbon", country: "Portugal", cityRank: 2, tag: "Lisbon's design-conscious heart", blurb: "Concept stores in 19th-century palacetes, the Embaixada gallery, specialty coffee and some of the best restaurants in the city. Príncipe Real has taken over from Chiado as Lisbon's most stylish corner.", sources: [{ pub: "Time Out Lisbon", url: "https://www.timeout.com/lisbon" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "Monocle", url: "https://monocle.com" }] },
  { name: "Bairro Alto", city: "Lisbon", country: "Portugal", cityRank: 3, tag: "Lisbon's loudest nights", blurb: "By day a sleepy hillside district of graffiti and bookshops; by night, one of Europe's great bar neighborhoods — tiny, independent spots spilling onto the streets from sundown to sunrise. Drink your way through, slowly.", sources: [{ pub: "Time Out Lisbon", url: "https://www.timeout.com/lisbon" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/lisbon" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "LX Factory", city: "Lisbon", country: "Portugal", cityRank: 4, tag: "Industrial creativity under the 25 de Abril Bridge", blurb: "A former 19th-century textile complex in Alcântara, reborn as a creative village of design studios, bookshops (Ler Devagar is a must), restaurants and Sunday markets. The best place to see Lisbon's contemporary side.", sources: [{ pub: "Time Out Lisbon", url: "https://www.timeout.com/lisbon" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "Monocle", url: "https://monocle.com" }] },
  { name: "Graça", city: "Lisbon", country: "Portugal", cityRank: 5, tag: "The best sunset miradouro in Lisbon", blurb: "Above Alfama, quieter and more residential, Graça holds two of the city's best viewpoints — Miradouro da Graça and Miradouro da Senhora do Monte — plus old-school tascas where a meal still costs what it did ten years ago.", sources: [{ pub: "Time Out Lisbon", url: "https://www.timeout.com/lisbon" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/lisbon" }] },

  // ─── ROME ───
  { name: "Trastevere", city: "Rome", country: "Italy", cityRank: 1, tag: "Rome's most romantic maze", blurb: "Cobblestone lanes, ivy-draped walls and the best trattoria density in the city. Trastevere is touristy in the main squares and wonderfully local two streets away — stay for dinner and a post-dinner walk along the Tiber.", sources: [{ pub: "Time Out Rome", url: "https://www.timeout.com/rome" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/rome" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },
  { name: "Monti", city: "Rome", country: "Italy", cityRank: 2, tag: "Bohemian Rome, minutes from the Colosseum", blurb: "The oldest rione in Rome and the city's most effortlessly hip — vintage stores, artisan workshops, wine bars spilling onto Piazza della Madonna dei Monti, and a location five minutes from the Forum. Impossible to beat.", sources: [{ pub: "Time Out Rome", url: "https://www.timeout.com/rome" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/rome" }] },
  { name: "Testaccio", city: "Rome", country: "Italy", cityRank: 3, tag: "The real home of Roman cooking", blurb: "Testaccio's history as Rome's slaughterhouse district shaped the city's most authentic cuisine — this is where you go for proper cacio e pepe, carbonara and coda alla vaccinara. The Testaccio food market is a working institution.", sources: [{ pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }, { pub: "Time Out Rome", url: "https://www.timeout.com/rome" }, { pub: "Eater", url: "https://www.eater.com/maps" }] },
  { name: "Pigneto", city: "Rome", country: "Italy", cityRank: 4, tag: "Rome's gritty creative frontier", blurb: "Pier Paolo Pasolini filmed here for a reason — Pigneto has always been Rome's working-class, slightly bohemian edge. Now it hosts the best natural-wine bars and new restaurants in the city, all still refreshingly unpolished.", sources: [{ pub: "Time Out Rome", url: "https://www.timeout.com/rome" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/rome" }, { pub: "La Repubblica", url: "https://www.repubblica.it/sezione/viaggi" }] },
  { name: "Prati", city: "Rome", country: "Italy", cityRank: 5, tag: "Elegant Rome near the Vatican", blurb: "Just north of the Vatican, Prati is Rome at its cleanest and most orderly — grand 19th-century boulevards, serious shopping along Via Cola di Rienzo, and some of the best gelato in the city (Gelateria dei Gracchi, take note).", sources: [{ pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "Time Out Rome", url: "https://www.timeout.com/rome" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },

  // ─── LOS ANGELES ───
  { name: "Silver Lake", city: "Los Angeles", country: "United States", cityRank: 1, tag: "LA's indie spirit, bottled and bearded", blurb: "Sunset Junction, the Silver Lake Reservoir, Intelligentsia Coffee and a thousand bands that started playing at the Satellite and the Echo. Silver Lake has been LA's creative heart for two decades and counting.", sources: [{ pub: "Time Out Los Angeles", url: "https://www.timeout.com/los-angeles" }, { pub: "Los Angeles Times", url: "https://www.latimes.com/food" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/los-angeles" }] },
  { name: "Venice", city: "Los Angeles", country: "United States", cityRank: 2, tag: "Beachside bohemia and Abbot Kinney", blurb: "Boardwalk circus, skate parks, the canals that inspired the name, and Abbot Kinney Boulevard — one of the best shopping-and-dining strips in America. Venice remains LA at its most eclectic and sun-drenched.", sources: [{ pub: "Time Out Los Angeles", url: "https://www.timeout.com/los-angeles" }, { pub: "Los Angeles Times", url: "https://www.latimes.com" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },
  { name: "Highland Park", city: "Los Angeles", country: "United States", cityRank: 3, tag: "Northeast LA's hottest corridor", blurb: "York Boulevard and Figueroa Street have become LA's most exciting new restaurant-and-bar corridor. The architecture is classic Craftsman, the food is world-class, and you can still find parking.", sources: [{ pub: "Eater LA", url: "https://la.eater.com" }, { pub: "Los Angeles Times", url: "https://www.latimes.com/food" }, { pub: "Time Out Los Angeles", url: "https://www.timeout.com/los-angeles" }] },
  { name: "Echo Park", city: "Los Angeles", country: "United States", cityRank: 4, tag: "The lake, the lotus festival, the late-night tacos", blurb: "Echo Park Lake with its paddle boats and lotus festival; Sunset Boulevard's dive bars and vintage shops; and Echo Park Lake at night, when the skyline lights up over the water. A little rough around the edges, exactly as it should be.", sources: [{ pub: "Time Out Los Angeles", url: "https://www.timeout.com/los-angeles" }, { pub: "Los Angeles Times", url: "https://www.latimes.com" }, { pub: "Eater LA", url: "https://la.eater.com" }] },
  { name: "West Adams", city: "Los Angeles", country: "United States", cityRank: 5, tag: "LA's next-big-thing historic district", blurb: "Craftsman mansions, historic Black-owned businesses and the most-watched new restaurant wave in LA. West Adams is where the city's food writers are camping out in 2026 — get there before Netflix does.", sources: [{ pub: "Eater LA", url: "https://la.eater.com" }, { pub: "Los Angeles Times", url: "https://www.latimes.com/food" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },

  // ─── RIO DE JANEIRO ───
  { name: "Santa Teresa", city: "Rio de Janeiro", country: "Brazil", cityRank: 1, tag: "Hilltop bohemia overlooking the bay", blurb: "The old tram still climbs to Santa Teresa — Rio's artist neighborhood, with colonial mansions, miradouros that look straight at Sugarloaf, and some of the best small restaurants and bars in the city. The Escadaria Selarón is here.", sources: [{ pub: "Time Out Rio", url: "https://www.timeout.com/rio-de-janeiro" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/rio-de-janeiro" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/rio" }] },
  { name: "Ipanema", city: "Rio de Janeiro", country: "Brazil", cityRank: 2, tag: "The most famous beach in the world", blurb: "The beach from the song, the most expensive real estate in Brazil, and a laid-back bar-and-restaurant scene that proves sophistication doesn't need to be stuffy. Sundays on the closed-to-cars beach road are essential.", sources: [{ pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }, { pub: "Time Out Rio", url: "https://www.timeout.com/rio-de-janeiro" }] },
  { name: "Leblon", city: "Rio de Janeiro", country: "Brazil", cityRank: 3, tag: "Ipanema's quieter, classier neighbor", blurb: "Rio's most expensive neighborhood keeps a calmer pace — leafy streets, upmarket bakeries, some of the best restaurants in the city, and a stretch of Ipanema beach with more families and fewer crowds.", sources: [{ pub: "Time Out Rio", url: "https://www.timeout.com/rio-de-janeiro" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "O Globo", url: "https://oglobo.globo.com" }] },
  { name: "Lapa", city: "Rio de Janeiro", country: "Brazil", cityRank: 4, tag: "Samba, arches, Friday night", blurb: "The Arcos da Lapa aqueduct is the backdrop to Rio's most riotous nightlife — samba clubs like Rio Scenarium and Lapa 40 Graus, street parties every weekend, and the Escadaria Selarón climbing up to Santa Teresa.", sources: [{ pub: "Time Out Rio", url: "https://www.timeout.com/rio-de-janeiro" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/rio" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "Botafogo", city: "Rio de Janeiro", country: "Brazil", cityRank: 5, tag: "Rio's new creative hub", blurb: "Between Copacabana and Ipanema, Botafogo has quietly become Rio's most dynamic food-and-drink neighborhood — botecos turned gastropubs, rooftop bars with views of the Sugarloaf, and a cost of living that still makes sense.", sources: [{ pub: "Time Out Rio", url: "https://www.timeout.com/rio-de-janeiro" }, { pub: "O Globo", url: "https://oglobo.globo.com" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },

  // ─── COPENHAGEN ───
  { name: "Nørrebro", city: "Copenhagen", country: "Denmark", cityRank: 1, tag: "Copenhagen's most cosmopolitan district", blurb: "Jægersborggade is one of the best food streets in Scandinavia; Assistens Cemetery holds Hans Christian Andersen and Kierkegaard; Superkilen is the most photographed public park in Denmark. Nørrebro is young, diverse and essential.", sources: [{ pub: "Time Out Copenhagen", url: "https://www.timeout.com/copenhagen" }, { pub: "Monocle", url: "https://monocle.com" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/copenhagen" }] },
  { name: "Vesterbro", city: "Copenhagen", country: "Denmark", cityRank: 2, tag: "The Meatpacking District, Copenhagen-style", blurb: "Kødbyen (the Meatpacking District) holds Copenhagen's best new restaurants, bars and galleries in converted industrial spaces. The rest of Vesterbro is residential, leafy and quietly stylish — the definition of hygge-urban.", sources: [{ pub: "Time Out Copenhagen", url: "https://www.timeout.com/copenhagen" }, { pub: "Monocle", url: "https://monocle.com" }, { pub: "The New York Times", url: "https://www.nytimes.com/section/travel" }] },
  { name: "Christianshavn", city: "Copenhagen", country: "Denmark", cityRank: 3, tag: "Canals, houseboats, free-state Christiania", blurb: "A mini-Amsterdam of canals and houseboats, plus Freetown Christiania — the self-declared autonomous commune that remains one of Copenhagen's most fascinating corners. Noma is here too.", sources: [{ pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "Time Out Copenhagen", url: "https://www.timeout.com/copenhagen" }, { pub: "The Guardian", url: "https://www.theguardian.com/travel/copenhagen" }] },
  { name: "Refshaleøen", city: "Copenhagen", country: "Denmark", cityRank: 4, tag: "Copenhagen's waterfront future", blurb: "A former shipyard now home to Reffen street food market, the Copenhagen Contemporary art centre and the two-Michelin-starred Alchemist. A 15-minute bike ride from the center, a different city when you arrive.", sources: [{ pub: "Time Out Copenhagen", url: "https://www.timeout.com/copenhagen" }, { pub: "Monocle", url: "https://monocle.com" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },
  { name: "Østerbro", city: "Copenhagen", country: "Denmark", cityRank: 5, tag: "Family Copenhagen, at its most liveable", blurb: "Fælledparken is the city's biggest park; the streets around it hold Copenhagen at its quietest and most well-designed. Cycle-friendly, café-dense, and beloved by locals for the reasons tourists tend to miss.", sources: [{ pub: "Monocle", url: "https://monocle.com" }, { pub: "Time Out Copenhagen", url: "https://www.timeout.com/copenhagen" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }] },

  // ─── TORONTO ───
  { name: "Kensington Market", city: "Toronto", country: "Canada", cityRank: 1, tag: "Toronto's most multicultural block", blurb: "Vintage shops in former Victorian houses, Caribbean roti joints, Latin American bakeries, vegan cafés and the monthly Pedestrian Sunday car-free days. Kensington Market is Toronto at its most alive and unpretentious.", sources: [{ pub: "Time Out Toronto", url: "https://www.timeout.com/toronto" }, { pub: "The Globe and Mail", url: "https://www.theglobeandmail.com/life/travel/destinations/toronto" }, { pub: "Condé Nast Traveler", url: "https://www.cntraveler.com/destinations/toronto" }] },
  { name: "Queen West", city: "Toronto", country: "Canada", cityRank: 2, tag: "Toronto's most famous art-and-fashion strip", blurb: "West Queen West was once named one of the coolest neighborhoods in the world by Vogue, and Ossington Avenue has since taken over as the bar-and-restaurant strip. Still the city's most creative corridor.", sources: [{ pub: "Vogue", url: "https://www.vogue.com" }, { pub: "Time Out Toronto", url: "https://www.timeout.com/toronto" }, { pub: "The Globe and Mail", url: "https://www.theglobeandmail.com" }] },
  { name: "Leslieville", city: "Toronto", country: "Canada", cityRank: 3, tag: "Toronto's east-end brunch champion", blurb: "Queen Street East is a continuous strip of the best brunch spots, independent boutiques and family-friendly restaurants in Toronto. Just east of the downtown core and a world away in pace.", sources: [{ pub: "Time Out Toronto", url: "https://www.timeout.com/toronto" }, { pub: "The Globe and Mail", url: "https://www.theglobeandmail.com" }, { pub: "Toronto Life", url: "https://torontolife.com" }] },
  { name: "The Annex", city: "Toronto", country: "Canada", cityRank: 4, tag: "Toronto's literary, academic heart", blurb: "Home to the University of Toronto, the city's best indie bookstore (Bakka Phoenix), and the kind of Victorian-mansion streets that give Toronto its character. Honest Ed's is gone, but the Annex carries on.", sources: [{ pub: "Toronto Life", url: "https://torontolife.com" }, { pub: "Time Out Toronto", url: "https://www.timeout.com/toronto" }, { pub: "The Globe and Mail", url: "https://www.theglobeandmail.com" }] },
  { name: "Distillery District", city: "Toronto", country: "Canada", cityRank: 5, tag: "Victorian industrial beauty, restored", blurb: "The largest collection of preserved Victorian industrial architecture in North America, reborn as a pedestrian-only village of galleries, restaurants and the famous Toronto Christmas Market. Touristy but genuinely lovely.", sources: [{ pub: "Condé Nast Traveler", url: "https://www.cntraveler.com" }, { pub: "Time Out Toronto", url: "https://www.timeout.com/toronto" }, { pub: "The Globe and Mail", url: "https://www.theglobeandmail.com" }] },
];

// Country-level metadata for header cards
export const COUNTRIES = [
  { name: "United States", flag: "🇺🇸" },
  { name: "United Kingdom", flag: "🇬🇧" },
  { name: "France", flag: "🇫🇷" },
  { name: "Japan", flag: "🇯🇵" },
  { name: "Germany", flag: "🇩🇪" },
  { name: "Spain", flag: "🇪🇸" },
  { name: "Mexico", flag: "🇲🇽" },
  { name: "Argentina", flag: "🇦🇷" },
  { name: "Australia", flag: "🇦🇺" },
  { name: "Singapore", flag: "🇸🇬" },
  { name: "Netherlands", flag: "🇳🇱" },
  { name: "Thailand", flag: "🇹🇭" },
  { name: "Turkey", flag: "🇹🇷" },
  { name: "South Korea", flag: "🇰🇷" },
  { name: "Portugal", flag: "🇵🇹" },
  { name: "Italy", flag: "🇮🇹" },
  { name: "Brazil", flag: "🇧🇷" },
  { name: "Denmark", flag: "🇩🇰" },
  { name: "Canada", flag: "🇨🇦" },
];
