// scripts/cities-seed.mjs
// Curated seed list: city → 5 neighborhoods with editorial tags + Wikipedia article titles.
// The enrichment script fetches each Wikipedia summary and builds the final data file.
// To expand coverage: append new CITIES entries here and re-run `node scripts/fetch-neighborhoods.mjs`.

export const CITIES = [
  { name: "New York", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Williamsburg", wiki: "Williamsburg,_Brooklyn", cityRank: 1, tag: "The creative capital of Brooklyn" },
    { name: "West Village", wiki: "West_Village", cityRank: 2, tag: "Cobblestone charm in the heart of Manhattan" },
    { name: "Lower East Side", wiki: "Lower_East_Side", cityRank: 3, tag: "Where old New York meets the new avant-garde" },
    { name: "Harlem", wiki: "Harlem", cityRank: 4, tag: "The cultural soul of Uptown" },
    { name: "SoHo", wiki: "SoHo,_Manhattan", cityRank: 5, tag: "Cast-iron architecture meets world-class shopping" },
  ]},
  { name: "London", country: "United Kingdom", flag: "🇬🇧", neighborhoods: [
    { name: "Shoreditch", wiki: "Shoreditch", cityRank: 1, tag: "East London's creative engine room" },
    { name: "Notting Hill", wiki: "Notting_Hill", cityRank: 2, tag: "Pastel houses and Portobello treasures" },
    { name: "Soho", wiki: "Soho", cityRank: 3, tag: "London's beating, neon-lit heart" },
    { name: "Peckham", wiki: "Peckham", cityRank: 4, tag: "South London's coolest rooftop" },
    { name: "Hackney", wiki: "Hackney_Central", cityRank: 5, tag: "Canal-side cool and killer coffee" },
  ]},
  { name: "Paris", country: "France", flag: "🇫🇷", neighborhoods: [
    { name: "Le Marais", wiki: "Le_Marais", cityRank: 1, tag: "Medieval Paris, perfectly preserved" },
    { name: "Canal Saint-Martin", wiki: "Canal_Saint-Martin", cityRank: 2, tag: "Where Paris comes to picnic" },
    { name: "Montmartre", wiki: "Montmartre", cityRank: 3, tag: "Bohemian Paris on the hill" },
    { name: "Belleville", wiki: "Belleville,_Paris", cityRank: 4, tag: "Paris at its most cosmopolitan" },
    { name: "Saint-Germain-des-Prés", wiki: "Saint-Germain-des-Prés", cityRank: 5, tag: "Intellectual Paris in cashmere and linen" },
  ]},
  { name: "Tokyo", country: "Japan", flag: "🇯🇵", neighborhoods: [
    { name: "Shimokitazawa", wiki: "Shimokitazawa", cityRank: 1, tag: "Tokyo's indie soul" },
    { name: "Shibuya", wiki: "Shibuya", cityRank: 2, tag: "The world's most famous crosswalk" },
    { name: "Daikanyama", wiki: "Daikanyama", cityRank: 3, tag: "Tokyo's quiet luxury village" },
    { name: "Yanaka", wiki: "Yanaka,_Tokyo", cityRank: 4, tag: "Old Tokyo frozen in time" },
    { name: "Shinjuku", wiki: "Shinjuku", cityRank: 5, tag: "Neon, skyscrapers and Golden Gai" },
  ]},
  { name: "Berlin", country: "Germany", flag: "🇩🇪", neighborhoods: [
    { name: "Kreuzberg", wiki: "Kreuzberg", cityRank: 1, tag: "Berlin's punk heart, still beating" },
    { name: "Neukölln", wiki: "Neukölln", cityRank: 2, tag: "Where Berlin moves next" },
    { name: "Prenzlauer Berg", wiki: "Prenzlauer_Berg", cityRank: 3, tag: "Cobblestones, cafés and quiet corners" },
    { name: "Friedrichshain", wiki: "Friedrichshain", cityRank: 4, tag: "Club capital of the continent" },
    { name: "Mitte", wiki: "Mitte", cityRank: 5, tag: "History, galleries and the city's front door" },
  ]},
  { name: "Barcelona", country: "Spain", flag: "🇪🇸", neighborhoods: [
    { name: "El Born", wiki: "La_Ribera,_Barcelona", cityRank: 1, tag: "Medieval streets, modern cocktails" },
    { name: "Gràcia", wiki: "Gràcia", cityRank: 2, tag: "Barcelona's village within the city" },
    { name: "El Raval", wiki: "El_Raval", cityRank: 3, tag: "Gritty, global and wildly alive" },
    { name: "Poble Sec", wiki: "Poble-sec", cityRank: 4, tag: "Tapas on Carrer Blai, sunset on Montjuïc" },
    { name: "Poblenou", wiki: "Poblenou", cityRank: 5, tag: "Barcelona's post-industrial playground" },
  ]},
  { name: "Mexico City", country: "Mexico", flag: "🇲🇽", neighborhoods: [
    { name: "Roma Norte", wiki: "Colonia_Roma", cityRank: 1, tag: "CDMX's creative epicenter" },
    { name: "Condesa", wiki: "Condesa", cityRank: 2, tag: "Art deco, green spaces, great food" },
    { name: "Coyoacán", wiki: "Coyoacán", cityRank: 3, tag: "Frida's cobblestone village" },
    { name: "Polanco", wiki: "Polanco,_Mexico_City", cityRank: 4, tag: "CDMX at its most polished" },
    { name: "Centro Histórico", wiki: "Historic_center_of_Mexico_City", cityRank: 5, tag: "The beating, historic heart of CDMX" },
  ]},
  { name: "Buenos Aires", country: "Argentina", flag: "🇦🇷", neighborhoods: [
    { name: "Palermo", wiki: "Palermo,_Buenos_Aires", cityRank: 1, tag: "The coolest grid in Latin America" },
    { name: "San Telmo", wiki: "San_Telmo", cityRank: 2, tag: "Tango, antiques, Sunday afternoons" },
    { name: "Recoleta", wiki: "Recoleta,_Buenos_Aires", cityRank: 3, tag: "Parisian elegance in the Southern Hemisphere" },
    { name: "Villa Crespo", wiki: "Villa_Crespo", cityRank: 4, tag: "Palermo's quieter, cheaper sibling" },
    { name: "La Boca", wiki: "La_Boca", cityRank: 5, tag: "Painted houses and Maradona's ghost" },
  ]},
  { name: "Melbourne", country: "Australia", flag: "🇦🇺", neighborhoods: [
    { name: "Fitzroy", wiki: "Fitzroy,_Victoria", cityRank: 1, tag: "Australia's original cool neighborhood" },
    { name: "Collingwood", wiki: "Collingwood,_Victoria", cityRank: 2, tag: "Fitzroy's rougher, realer neighbor" },
    { name: "Brunswick", wiki: "Brunswick,_Victoria", cityRank: 3, tag: "Live music and the best pizza in town" },
    { name: "St Kilda", wiki: "St_Kilda,_Victoria", cityRank: 4, tag: "Beachside bohemia" },
    { name: "Carlton", wiki: "Carlton,_Victoria", cityRank: 5, tag: "Melbourne's Little Italy, with a PhD" },
  ]},
  { name: "Singapore", country: "Singapore", flag: "🇸🇬", neighborhoods: [
    { name: "Tiong Bahru", wiki: "Tiong_Bahru", cityRank: 1, tag: "Art deco, hawker food, perfect coffee" },
    { name: "Kampong Glam", wiki: "Kampong_Glam", cityRank: 2, tag: "Haji Lane, the Sultan Mosque and street art" },
    { name: "Chinatown", wiki: "Chinatown,_Singapore", cityRank: 3, tag: "Hawker heritage meets craft cocktails" },
    { name: "Katong", wiki: "Katong", cityRank: 4, tag: "Peranakan heritage and laksa perfection" },
    { name: "Dempsey Hill", wiki: "Tanglin", cityRank: 5, tag: "Jungle, restaurants, hidden calm" },
  ]},
  { name: "Amsterdam", country: "Netherlands", flag: "🇳🇱", neighborhoods: [
    { name: "Jordaan", wiki: "Jordaan", cityRank: 1, tag: "Amsterdam's most charming canals" },
    { name: "De Pijp", wiki: "De_Pijp", cityRank: 2, tag: "The Albert Cuyp market and brunch capital" },
    { name: "Amsterdam-Oost", wiki: "Amsterdam-Oost", cityRank: 3, tag: "Where Amsterdam actually hangs out" },
    { name: "Amsterdam-Noord", wiki: "Amsterdam-Noord", cityRank: 4, tag: "A free ferry ride to the future" },
    { name: "De Baarsjes", wiki: "De_Baarsjes", cityRank: 5, tag: "Amsterdam-West's quiet rise" },
  ]},
  { name: "Bangkok", country: "Thailand", flag: "🇹🇭", neighborhoods: [
    { name: "Ari", wiki: "Phaya_Thai_District", cityRank: 1, tag: "Bangkok's cool, quiet middle" },
    { name: "Thonglor", wiki: "Thong_Lo", cityRank: 2, tag: "Sukhumvit's nightlife spine" },
    { name: "Yaowarat", wiki: "Yaowarat_Road", cityRank: 3, tag: "The best street food in Southeast Asia" },
    { name: "Ekkamai", wiki: "Ekkamai", cityRank: 4, tag: "Thonglor's slower, hipper neighbor" },
    { name: "Banglamphu", wiki: "Banglamphu", cityRank: 5, tag: "Old Bangkok meets Khao San Road" },
  ]},
  { name: "Istanbul", country: "Turkey", flag: "🇹🇷", neighborhoods: [
    { name: "Karaköy", wiki: "Karaköy", cityRank: 1, tag: "Old port, new creative scene" },
    { name: "Kadıköy", wiki: "Kadıköy", cityRank: 2, tag: "Asian-side Istanbul at its liveliest" },
    { name: "Cihangir", wiki: "Cihangir", cityRank: 3, tag: "The writer's neighborhood of Istanbul" },
    { name: "Balat", wiki: "Balat", cityRank: 4, tag: "Istanbul's most photogenic streets" },
    { name: "Beyoğlu", wiki: "Beyoğlu", cityRank: 5, tag: "İstiklal Caddesi and the city's nightlife" },
  ]},
  { name: "Seoul", country: "South Korea", flag: "🇰🇷", neighborhoods: [
    { name: "Seongsu-dong", wiki: "Seongsu-dong", cityRank: 1, tag: "The Brooklyn of Seoul" },
    { name: "Ikseon-dong", wiki: "Ikseon-dong", cityRank: 2, tag: "Hanok alleys full of hidden cafés" },
    { name: "Hongdae", wiki: "Hongdae", cityRank: 3, tag: "Student energy, indie music, 24-hour bars" },
    { name: "Itaewon", wiki: "Itaewon", cityRank: 4, tag: "Seoul's international melting pot" },
    { name: "Yeonnam-dong", wiki: "Yeonnam-dong", cityRank: 5, tag: "Gyeongui Line Forest, micro-cafés, slow days" },
  ]},
  { name: "Lisbon", country: "Portugal", flag: "🇵🇹", neighborhoods: [
    { name: "Alfama", wiki: "Alfama", cityRank: 1, tag: "Fado, tiles, cobblestones" },
    { name: "Príncipe Real", wiki: "Príncipe_Real", cityRank: 2, tag: "Lisbon's design-conscious heart" },
    { name: "Bairro Alto", wiki: "Bairro_Alto", cityRank: 3, tag: "Lisbon's loudest nights" },
    { name: "LX Factory", wiki: "LX_Factory", cityRank: 4, tag: "Industrial creativity under the bridge" },
    { name: "Graça", wiki: "Graça_(Lisbon)", cityRank: 5, tag: "The best sunset miradouro in Lisbon" },
  ]},
  { name: "Rome", country: "Italy", flag: "🇮🇹", neighborhoods: [
    { name: "Trastevere", wiki: "Trastevere", cityRank: 1, tag: "Rome's most romantic maze" },
    { name: "Monti", wiki: "Monti_(rione_of_Rome)", cityRank: 2, tag: "Bohemian Rome, minutes from the Colosseum" },
    { name: "Testaccio", wiki: "Testaccio", cityRank: 3, tag: "The real home of Roman cooking" },
    { name: "Pigneto", wiki: "Pigneto", cityRank: 4, tag: "Rome's gritty creative frontier" },
    { name: "Prati", wiki: "Prati", cityRank: 5, tag: "Elegant Rome near the Vatican" },
  ]},
  { name: "Los Angeles", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Silver Lake", wiki: "Silver_Lake,_Los_Angeles", cityRank: 1, tag: "LA's indie spirit, bottled and bearded" },
    { name: "Venice", wiki: "Venice,_Los_Angeles", cityRank: 2, tag: "Beachside bohemia and Abbot Kinney" },
    { name: "Highland Park", wiki: "Highland_Park,_Los_Angeles", cityRank: 3, tag: "Northeast LA's hottest corridor" },
    { name: "Echo Park", wiki: "Echo_Park,_Los_Angeles", cityRank: 4, tag: "The lake, the lotus festival, the late-night tacos" },
    { name: "West Adams", wiki: "West_Adams,_Los_Angeles", cityRank: 5, tag: "LA's next-big-thing historic district" },
  ]},
  { name: "Rio de Janeiro", country: "Brazil", flag: "🇧🇷", neighborhoods: [
    { name: "Santa Teresa", wiki: "Santa_Teresa,_Rio_de_Janeiro", cityRank: 1, tag: "Hilltop bohemia overlooking the bay" },
    { name: "Ipanema", wiki: "Ipanema", cityRank: 2, tag: "The most famous beach in the world" },
    { name: "Leblon", wiki: "Leblon", cityRank: 3, tag: "Ipanema's quieter, classier neighbor" },
    { name: "Lapa", wiki: "Lapa,_Rio_de_Janeiro", cityRank: 4, tag: "Samba, arches, Friday night" },
    { name: "Botafogo", wiki: "Botafogo", cityRank: 5, tag: "Rio's new creative hub" },
  ]},
  { name: "Copenhagen", country: "Denmark", flag: "🇩🇰", neighborhoods: [
    { name: "Nørrebro", wiki: "Nørrebro", cityRank: 1, tag: "Copenhagen's most cosmopolitan district" },
    { name: "Vesterbro", wiki: "Vesterbro", cityRank: 2, tag: "The Meatpacking District, Copenhagen-style" },
    { name: "Christianshavn", wiki: "Christianshavn", cityRank: 3, tag: "Canals, houseboats, free-state Christiania" },
    { name: "Refshaleøen", wiki: "Refshaleøen", cityRank: 4, tag: "Copenhagen's waterfront future" },
    { name: "Østerbro", wiki: "Østerbro", cityRank: 5, tag: "Family Copenhagen, at its most liveable" },
  ]},
  { name: "Toronto", country: "Canada", flag: "🇨🇦", neighborhoods: [
    { name: "Kensington Market", wiki: "Kensington_Market", cityRank: 1, tag: "Toronto's most multicultural block" },
    { name: "Queen West", wiki: "Queen_Street_West", cityRank: 2, tag: "Toronto's most famous art-and-fashion strip" },
    { name: "Leslieville", wiki: "Leslieville", cityRank: 3, tag: "Toronto's east-end brunch champion" },
    { name: "The Annex", wiki: "The_Annex", cityRank: 4, tag: "Toronto's literary, academic heart" },
    { name: "Distillery District", wiki: "Distillery_District", cityRank: 5, tag: "Victorian industrial beauty, restored" },
  ]},

  // ── Expansion batch ──
  { name: "Chicago", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Wicker Park", wiki: "Wicker_Park,_Chicago", cityRank: 1, tag: "Chicago's creative West Side" },
    { name: "Logan Square", wiki: "Logan_Square,_Chicago", cityRank: 2, tag: "Boulevards, bungalows and killer bars" },
    { name: "Pilsen", wiki: "Pilsen,_Chicago", cityRank: 3, tag: "Mexican heritage, murals and mercados" },
    { name: "Hyde Park", wiki: "Hyde_Park,_Chicago", cityRank: 4, tag: "University town meets lakefront" },
    { name: "West Loop", wiki: "Near_West_Side,_Chicago", cityRank: 5, tag: "Chicago's restaurant powerhouse" },
  ]},
  { name: "San Francisco", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Mission District", wiki: "Mission_District,_San_Francisco", cityRank: 1, tag: "Murals, taquerias and fog-free sun" },
    { name: "Haight-Ashbury", wiki: "Haight-Ashbury", cityRank: 2, tag: "Where the Summer of Love happened" },
    { name: "North Beach", wiki: "North_Beach,_San_Francisco", cityRank: 3, tag: "SF's Little Italy and Beat home" },
    { name: "Castro District", wiki: "Castro_District,_San_Francisco", cityRank: 4, tag: "The heart of LGBTQ+ America" },
    { name: "Hayes Valley", wiki: "Hayes_Valley,_San_Francisco", cityRank: 5, tag: "Boutique SF at its most stylish" },
  ]},
  { name: "Boston", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Back Bay", wiki: "Back_Bay,_Boston", cityRank: 1, tag: "Brownstones, boutiques and the Charles" },
    { name: "North End", wiki: "North_End,_Boston", cityRank: 2, tag: "Boston's Little Italy" },
    { name: "Beacon Hill", wiki: "Beacon_Hill,_Boston", cityRank: 3, tag: "Gas lamps and cobblestones" },
    { name: "South End", wiki: "South_End,_Boston", cityRank: 4, tag: "Victorian rowhouses and restaurant row" },
    { name: "Cambridge", wiki: "Cambridge,_Massachusetts", cityRank: 5, tag: "Harvard, MIT and the best bookshops in New England" },
  ]},
  { name: "Miami", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Wynwood", wiki: "Wynwood", cityRank: 1, tag: "The street-art capital of the Americas" },
    { name: "Little Havana", wiki: "Little_Havana", cityRank: 2, tag: "Cuban cafés and Calle Ocho" },
    { name: "Design District", wiki: "Miami_Design_District", cityRank: 3, tag: "Luxury shopping, world-class architecture" },
    { name: "South Beach", wiki: "South_Beach", cityRank: 4, tag: "Art deco and ocean drive glamour" },
    { name: "Coconut Grove", wiki: "Coconut_Grove", cityRank: 5, tag: "Miami's leafy, bohemian corner" },
  ]},
  { name: "New Orleans", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "French Quarter", wiki: "French_Quarter", cityRank: 1, tag: "The beating heart of NOLA" },
    { name: "Marigny", wiki: "Faubourg_Marigny", cityRank: 2, tag: "Frenchmen Street and the real jazz" },
    { name: "Bywater", wiki: "Bywater,_New_Orleans", cityRank: 3, tag: "Colorful shotgun houses and creative energy" },
    { name: "Garden District", wiki: "Garden_District,_New_Orleans", cityRank: 4, tag: "Antebellum mansions and oak-lined streets" },
    { name: "Tremé", wiki: "Tremé", cityRank: 5, tag: "The oldest Black neighborhood in America" },
  ]},
  { name: "Washington", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Georgetown", wiki: "Georgetown_(Washington,_D.C.)", cityRank: 1, tag: "DC's prettiest, oldest district" },
    { name: "Dupont Circle", wiki: "Dupont_Circle", cityRank: 2, tag: "Embassies, bookshops and brunch" },
    { name: "Adams Morgan", wiki: "Adams_Morgan", cityRank: 3, tag: "DC's most international nightlife" },
    { name: "Capitol Hill", wiki: "Capitol_Hill", cityRank: 4, tag: "Where politics meets rowhouses" },
    { name: "Shaw", wiki: "Shaw_(Washington,_D.C.)", cityRank: 5, tag: "DC's cultural renaissance" },
  ]},
  { name: "Seattle", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Capitol Hill", wiki: "Capitol_Hill,_Seattle", cityRank: 1, tag: "Seattle's nightlife and queer heart" },
    { name: "Ballard", wiki: "Ballard,_Seattle", cityRank: 2, tag: "Scandinavian heritage and the Sunday market" },
    { name: "Pike Place", wiki: "Pike_Place_Market", cityRank: 3, tag: "The world-famous waterfront market" },
    { name: "Fremont", wiki: "Fremont,_Seattle", cityRank: 4, tag: "The self-declared center of the universe" },
    { name: "Georgetown", wiki: "Georgetown,_Seattle", cityRank: 5, tag: "Seattle's industrial-artist frontier" },
  ]},
  { name: "Austin", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "South Congress", wiki: "South_Congress,_Austin,_Texas", cityRank: 1, tag: "SoCo vintage and live music" },
    { name: "East Austin", wiki: "East_Austin,_Texas", cityRank: 2, tag: "Austin's most creative east side" },
    { name: "Downtown", wiki: "Downtown_Austin", cityRank: 3, tag: "Sixth Street and the live music capital" },
    { name: "Zilker", wiki: "Zilker,_Austin,_Texas", cityRank: 4, tag: "Barton Springs and ACL Festival" },
    { name: "Hyde Park", wiki: "Hyde_Park,_Austin,_Texas", cityRank: 5, tag: "Austin's leafy, historic core" },
  ]},
  { name: "Madrid", country: "Spain", flag: "🇪🇸", neighborhoods: [
    { name: "Malasaña", wiki: "Malasaña", cityRank: 1, tag: "Madrid's hip, independent heart" },
    { name: "La Latina", wiki: "La_Latina,_Madrid", cityRank: 2, tag: "Tapas crawls and Sunday vermouth" },
    { name: "Chueca", wiki: "Chueca", cityRank: 3, tag: "Madrid's LGBTQ+ and shopping district" },
    { name: "Salamanca", wiki: "Salamanca_(Madrid)", cityRank: 4, tag: "Madrid at its most elegant" },
    { name: "Lavapiés", wiki: "Lavapiés", cityRank: 5, tag: "The city's most multicultural maze" },
  ]},
  { name: "Milan", country: "Italy", flag: "🇮🇹", neighborhoods: [
    { name: "Brera", wiki: "Brera_(district_of_Milan)", cityRank: 1, tag: "Milan's artistic quarter" },
    { name: "Navigli", wiki: "Navigli", cityRank: 2, tag: "Canals, aperitivo and late nights" },
    { name: "Porta Nuova", wiki: "Porta_Nuova_(Milan)", cityRank: 3, tag: "Milan's sleek new skyline" },
    { name: "Isola", wiki: "Isola_(Milan)", cityRank: 4, tag: "Industrial-chic and local bars" },
    { name: "Porta Ticinese", wiki: "Porta_Ticinese", cityRank: 5, tag: "Medieval arches and Darsena nights" },
  ]},
  { name: "Vienna", country: "Austria", flag: "🇦🇹", neighborhoods: [
    { name: "Leopoldstadt", wiki: "Leopoldstadt", cityRank: 1, tag: "Vienna's Jewish heart reborn" },
    { name: "Neubau", wiki: "Neubau_(Vienna)", cityRank: 2, tag: "Vienna's coolest shopping streets" },
    { name: "Mariahilf", wiki: "Mariahilf", cityRank: 3, tag: "Vienna at its most shoppable" },
    { name: "Karmeliterviertel", wiki: "Karmeliterviertel", cityRank: 4, tag: "Markets, cafés and canal walks" },
    { name: "Innere Stadt", wiki: "Innere_Stadt", cityRank: 5, tag: "Imperial Vienna, the old town" },
  ]},
  { name: "Prague", country: "Czechia", flag: "🇨🇿", neighborhoods: [
    { name: "Žižkov", wiki: "Žižkov", cityRank: 1, tag: "Prague's bohemian pub capital" },
    { name: "Vinohrady", wiki: "Vinohrady", cityRank: 2, tag: "Leafy parks, cafés and Art Nouveau" },
    { name: "Malá Strana", wiki: "Malá_Strana", cityRank: 3, tag: "Baroque Prague under the castle" },
    { name: "Karlín", wiki: "Karlín_(Prague)", cityRank: 4, tag: "Prague's revived industrial district" },
    { name: "Staré Město", wiki: "Staré_Město_(Prague)", cityRank: 5, tag: "The astronomical clock and Old Town Square" },
  ]},
  { name: "Budapest", country: "Hungary", flag: "🇭🇺", neighborhoods: [
    { name: "Jewish Quarter", wiki: "Jewish_quarter_of_Budapest", cityRank: 1, tag: "Ruin bars and the Dohány Synagogue" },
    { name: "Buda Castle", wiki: "Buda_Castle", cityRank: 2, tag: "UNESCO-listed Baroque Budapest" },
    { name: "Ferencváros", wiki: "Ferencváros", cityRank: 3, tag: "Budapest's rising cultural district" },
    { name: "Erzsébetváros", wiki: "Erzsébetváros", cityRank: 4, tag: "The beating nightlife heart of Pest" },
    { name: "Újbuda", wiki: "Újbuda", cityRank: 5, tag: "Student Budapest on the Buda side" },
  ]},
  { name: "Stockholm", country: "Sweden", flag: "🇸🇪", neighborhoods: [
    { name: "Södermalm", wiki: "Södermalm", cityRank: 1, tag: "Stockholm's hippest island" },
    { name: "Gamla Stan", wiki: "Gamla_stan", cityRank: 2, tag: "The medieval old town" },
    { name: "Östermalm", wiki: "Östermalm", cityRank: 3, tag: "Stockholm at its most luxurious" },
    { name: "Vasastan", wiki: "Vasastan,_Stockholm", cityRank: 4, tag: "Leafy, literary Stockholm" },
    { name: "Kungsholmen", wiki: "Kungsholmen", cityRank: 5, tag: "Waterfront living, quieter side" },
  ]},
  { name: "Dublin", country: "Ireland", flag: "🇮🇪", neighborhoods: [
    { name: "Temple Bar", wiki: "Temple_Bar,_Dublin", cityRank: 1, tag: "Dublin's famous pub quarter" },
    { name: "Portobello", wiki: "Portobello,_Dublin", cityRank: 2, tag: "Canal-side cafés and Little Jerusalem" },
    { name: "Smithfield", wiki: "Smithfield,_Dublin", cityRank: 3, tag: "The old distillery district, rebuilt" },
    { name: "Stoneybatter", wiki: "Stoneybatter", cityRank: 4, tag: "Dublin's quirkiest village" },
    { name: "Ranelagh", wiki: "Ranelagh", cityRank: 5, tag: "Genteel south Dublin" },
  ]},
  { name: "Edinburgh", country: "United Kingdom", flag: "🇬🇧", neighborhoods: [
    { name: "Old Town", wiki: "Old_Town,_Edinburgh", cityRank: 1, tag: "The Royal Mile and the Castle" },
    { name: "Stockbridge", wiki: "Stockbridge,_Edinburgh", cityRank: 2, tag: "Village charm in the city" },
    { name: "Leith", wiki: "Leith", cityRank: 3, tag: "Edinburgh's reborn waterfront" },
    { name: "New Town", wiki: "New_Town,_Edinburgh", cityRank: 4, tag: "Georgian elegance, UNESCO-listed" },
    { name: "Bruntsfield", wiki: "Bruntsfield", cityRank: 5, tag: "Independent shops and the Meadows" },
  ]},
  { name: "Athens", country: "Greece", flag: "🇬🇷", neighborhoods: [
    { name: "Plaka", wiki: "Plaka", cityRank: 1, tag: "Athens under the Acropolis" },
    { name: "Psyri", wiki: "Psyri", cityRank: 2, tag: "The nightlife heart of old Athens" },
    { name: "Koukaki", wiki: "Koukaki", cityRank: 3, tag: "Athens' most liveable corner" },
    { name: "Exarcheia", wiki: "Exarcheia", cityRank: 4, tag: "Athens at its most political" },
    { name: "Monastiraki", wiki: "Monastiraki", cityRank: 5, tag: "Flea markets and ancient views" },
  ]},
  { name: "Munich", country: "Germany", flag: "🇩🇪", neighborhoods: [
    { name: "Schwabing", wiki: "Schwabing", cityRank: 1, tag: "Munich's bohemian old neighborhood" },
    { name: "Glockenbachviertel", wiki: "Glockenbachviertel", cityRank: 2, tag: "Munich's queer and creative quarter" },
    { name: "Haidhausen", wiki: "Haidhausen", cityRank: 3, tag: "Munich's quiet French corner" },
    { name: "Maxvorstadt", wiki: "Maxvorstadt", cityRank: 4, tag: "Museums, university and coffee" },
    { name: "Westend", wiki: "Westend,_Munich", cityRank: 5, tag: "Multicultural Munich" },
  ]},
  { name: "Hamburg", country: "Germany", flag: "🇩🇪", neighborhoods: [
    { name: "St. Pauli", wiki: "St._Pauli", cityRank: 1, tag: "The Reeperbahn and Hamburg's wild side" },
    { name: "Sternschanze", wiki: "Sternschanze", cityRank: 2, tag: "Hamburg's alternative heart" },
    { name: "Altona", wiki: "Altona,_Hamburg", cityRank: 3, tag: "Fish market and harbor views" },
    { name: "HafenCity", wiki: "HafenCity", cityRank: 4, tag: "Europe's biggest waterfront project" },
    { name: "Eppendorf", wiki: "Eppendorf,_Hamburg", cityRank: 5, tag: "Elegant Hamburg" },
  ]},
  { name: "Hong Kong", country: "Hong Kong", flag: "🇭🇰", neighborhoods: [
    { name: "Sheung Wan", wiki: "Sheung_Wan", cityRank: 1, tag: "Dried seafood meets third-wave coffee" },
    { name: "Central", wiki: "Central,_Hong_Kong", cityRank: 2, tag: "The financial and colonial heart" },
    { name: "Mong Kok", wiki: "Mong_Kok", cityRank: 3, tag: "Neon signs and the densest place on Earth" },
    { name: "Causeway Bay", wiki: "Causeway_Bay", cityRank: 4, tag: "Hong Kong's shopping epicenter" },
    { name: "Sai Ying Pun", wiki: "Sai_Ying_Pun", cityRank: 5, tag: "Gentrifying, hilly and fascinating" },
  ]},
  { name: "Mumbai", country: "India", flag: "🇮🇳", neighborhoods: [
    { name: "Bandra", wiki: "Bandra", cityRank: 1, tag: "Mumbai's creative Bollywood enclave" },
    { name: "Colaba", wiki: "Colaba", cityRank: 2, tag: "Colonial Mumbai by the sea" },
    { name: "Fort", wiki: "Fort,_Mumbai", cityRank: 3, tag: "Victorian Gothic and Gateway of India" },
    { name: "Lower Parel", wiki: "Lower_Parel", cityRank: 4, tag: "Mill-to-mall Mumbai" },
    { name: "Juhu", wiki: "Juhu", cityRank: 5, tag: "Beachfront Bollywood" },
  ]},
  { name: "Delhi", country: "India", flag: "🇮🇳", neighborhoods: [
    { name: "Hauz Khas Village", wiki: "Hauz_Khas", cityRank: 1, tag: "Medieval ruins and rooftop bars" },
    { name: "Connaught Place", wiki: "Connaught_Place,_New_Delhi", cityRank: 2, tag: "Delhi's colonial-era circle" },
    { name: "Chandni Chowk", wiki: "Chandni_Chowk", cityRank: 3, tag: "Old Delhi's lively bazaar" },
    { name: "Khan Market", wiki: "Khan_Market", cityRank: 4, tag: "Delhi's smartest shopping" },
    { name: "Nizamuddin", wiki: "Nizamuddin_West", cityRank: 5, tag: "Sufi shrines and Mughal tombs" },
  ]},
  { name: "Shanghai", country: "China", flag: "🇨🇳", neighborhoods: [
    { name: "French Concession", wiki: "Shanghai_French_Concession", cityRank: 1, tag: "Plane trees and art deco shikumen" },
    { name: "Xintiandi", wiki: "Xintiandi", cityRank: 2, tag: "Shanghai's stylish reborn lanes" },
    { name: "Tianzifang", wiki: "Tianzifang", cityRank: 3, tag: "Arts and craft alleys" },
    { name: "The Bund", wiki: "The_Bund", cityRank: 4, tag: "Colonial waterfront, Pudong skyline" },
    { name: "Jing'an", wiki: "Jing'an_District", cityRank: 5, tag: "Shanghai's smart commercial heart" },
  ]},
  { name: "Taipei", country: "Taiwan", flag: "🇹🇼", neighborhoods: [
    { name: "Ximending", wiki: "Ximending", cityRank: 1, tag: "Taipei's youth culture capital" },
    { name: "Da'an", wiki: "Da'an_District,_Taipei", cityRank: 2, tag: "Cafés, night markets, shopping" },
    { name: "Datong", wiki: "Datong_District,_Taipei", cityRank: 3, tag: "Old Taipei, Dihua Street" },
    { name: "Xinyi", wiki: "Xinyi_District,_Taipei", cityRank: 4, tag: "Taipei 101 and glossy shopping" },
    { name: "Zhongshan", wiki: "Zhongshan_District,_Taipei", cityRank: 5, tag: "Japanese colonial echoes" },
  ]},
  { name: "Kuala Lumpur", country: "Malaysia", flag: "🇲🇾", neighborhoods: [
    { name: "Bangsar", wiki: "Bangsar", cityRank: 1, tag: "KL's trendiest dining district" },
    { name: "Bukit Bintang", wiki: "Bukit_Bintang", cityRank: 2, tag: "The shopping and nightlife core" },
    { name: "Chinatown", wiki: "Petaling_Street", cityRank: 3, tag: "KL's lively old core" },
    { name: "Brickfields", wiki: "Brickfields", cityRank: 4, tag: "KL's Little India" },
    { name: "Mont Kiara", wiki: "Mont_Kiara", cityRank: 5, tag: "Expat KL, at ease" },
  ]},
  { name: "Jakarta", country: "Indonesia", flag: "🇮🇩", neighborhoods: [
    { name: "Menteng", wiki: "Menteng", cityRank: 1, tag: "Jakarta's leafy, diplomatic heart" },
    { name: "Kemang", wiki: "Kemang,_Jakarta", cityRank: 2, tag: "Jakarta's bar and café village" },
    { name: "Kota Tua", wiki: "Kota_Tua_Jakarta", cityRank: 3, tag: "Jakarta's colonial old town" },
    { name: "Kebayoran Baru", wiki: "Kebayoran_Baru", cityRank: 4, tag: "Jakarta's elegant modern quarter" },
    { name: "Kelapa Gading", wiki: "Kelapa_Gading", cityRank: 5, tag: "Jakarta's shopping and food capital" },
  ]},
  { name: "Osaka", country: "Japan", flag: "🇯🇵", neighborhoods: [
    { name: "Namba", wiki: "Namba", cityRank: 1, tag: "Dotonbori and the neon canal" },
    { name: "Umeda", wiki: "Umeda", cityRank: 2, tag: "Osaka's sky-high retail core" },
    { name: "Shinsekai", wiki: "Shinsekai", cityRank: 3, tag: "Retro Osaka, Tsutenkaku Tower" },
    { name: "Amerikamura", wiki: "Amerikamura", cityRank: 4, tag: "Osaka's youth and vintage hub" },
    { name: "Tenma", wiki: "Tenma,_Osaka", cityRank: 5, tag: "Long arcades and local izakaya" },
  ]},
  { name: "Kyoto", country: "Japan", flag: "🇯🇵", neighborhoods: [
    { name: "Gion", wiki: "Gion", cityRank: 1, tag: "Kyoto's geisha district" },
    { name: "Arashiyama", wiki: "Arashiyama", cityRank: 2, tag: "Bamboo groves and temple mountains" },
    { name: "Higashiyama", wiki: "Higashiyama-ku,_Kyoto", cityRank: 3, tag: "Temples, teahouses and traditional lanes" },
    { name: "Pontocho", wiki: "Pontocho", cityRank: 4, tag: "Kyoto's riverside dining alley" },
    { name: "Nishijin", wiki: "Nishijin", cityRank: 5, tag: "The traditional textile quarter" },
  ]},
  { name: "Dubai", country: "United Arab Emirates", flag: "🇦🇪", neighborhoods: [
    { name: "Downtown Dubai", wiki: "Downtown_Dubai", cityRank: 1, tag: "Burj Khalifa and the Dubai Mall" },
    { name: "Dubai Marina", wiki: "Dubai_Marina", cityRank: 2, tag: "Skyscrapers on the water" },
    { name: "Jumeirah", wiki: "Jumeirah", cityRank: 3, tag: "Beachside Dubai at its most polished" },
    { name: "Al Fahidi", wiki: "Al_Fahidi_Historical_Neighbourhood", cityRank: 4, tag: "Old Dubai, restored" },
    { name: "Deira", wiki: "Deira", cityRank: 5, tag: "Traditional souks and abras" },
  ]},
  { name: "Cairo", country: "Egypt", flag: "🇪🇬", neighborhoods: [
    { name: "Zamalek", wiki: "Zamalek", cityRank: 1, tag: "Cairo's leafy island district" },
    { name: "Islamic Cairo", wiki: "Islamic_Cairo", cityRank: 2, tag: "Medieval mosques and Khan el-Khalili" },
    { name: "Maadi", wiki: "Maadi", cityRank: 3, tag: "Leafy Cairo, expat-loved" },
    { name: "Heliopolis", wiki: "Heliopolis,_Cairo", cityRank: 4, tag: "Belle Époque planned Cairo" },
    { name: "Downtown Cairo", wiki: "Downtown_Cairo", cityRank: 5, tag: "Cairo's faded 20th-century grandeur" },
  ]},
  { name: "Cape Town", country: "South Africa", flag: "🇿🇦", neighborhoods: [
    { name: "Bo-Kaap", wiki: "Bo-Kaap", cityRank: 1, tag: "Rainbow houses and Cape Malay culture" },
    { name: "Woodstock", wiki: "Woodstock,_Cape_Town", cityRank: 2, tag: "Cape Town's creative hub" },
    { name: "V&A Waterfront", wiki: "Victoria_%26_Alfred_Waterfront", cityRank: 3, tag: "Working harbor, world-class shopping" },
    { name: "Sea Point", wiki: "Sea_Point", cityRank: 4, tag: "The promenade and Atlantic sunsets" },
    { name: "De Waterkant", wiki: "De_Waterkant", cityRank: 5, tag: "Cape Town's pink-house village" },
  ]},
  { name: "Marrakech", country: "Morocco", flag: "🇲🇦", neighborhoods: [
    { name: "Medina", wiki: "Medina_of_Marrakesh", cityRank: 1, tag: "UNESCO-listed heart of Marrakech" },
    { name: "Gueliz", wiki: "Gueliz", cityRank: 2, tag: "Modern Marrakech, French legacy" },
    { name: "Hivernage", wiki: "Hivernage", cityRank: 3, tag: "Gardens, hotels and nightlife" },
    { name: "Kasbah", wiki: "Kasbah_of_Marrakesh", cityRank: 4, tag: "Royal quarter and Saadian tombs" },
    { name: "Mellah", wiki: "Mellah_of_Marrakesh", cityRank: 5, tag: "The historic Jewish quarter" },
  ]},
  { name: "Tel Aviv", country: "Israel", flag: "🇮🇱", neighborhoods: [
    { name: "Neve Tzedek", wiki: "Neve_Tzedek", cityRank: 1, tag: "Tel Aviv's oldest neighborhood" },
    { name: "Florentin", wiki: "Florentin,_Tel_Aviv", cityRank: 2, tag: "Street art and the nightlife frontier" },
    { name: "Jaffa", wiki: "Jaffa", cityRank: 3, tag: "Ancient port, stone alleys" },
    { name: "Rothschild", wiki: "Rothschild_Boulevard", cityRank: 4, tag: "Bauhaus boulevard and café culture" },
    { name: "Kerem HaTeimanim", wiki: "Kerem_HaTeimanim", cityRank: 5, tag: "Yemenite food and the Carmel Market" },
  ]},
  { name: "São Paulo", country: "Brazil", flag: "🇧🇷", neighborhoods: [
    { name: "Vila Madalena", wiki: "Vila_Madalena", cityRank: 1, tag: "Street art, bars and bohemia" },
    { name: "Jardins", wiki: "Jardim_América,_São_Paulo", cityRank: 2, tag: "São Paulo at its most elegant" },
    { name: "Pinheiros", wiki: "Pinheiros", cityRank: 3, tag: "SP's design and food capital" },
    { name: "Liberdade", wiki: "Liberdade_(district_of_São_Paulo)", cityRank: 4, tag: "The largest Japanese district outside Japan" },
    { name: "Consolação", wiki: "Consolação_(district_of_São_Paulo)", cityRank: 5, tag: "Avenida Paulista and SP's nightlife" },
  ]},
  { name: "Lima", country: "Peru", flag: "🇵🇪", neighborhoods: [
    { name: "Miraflores", wiki: "Miraflores_District,_Lima", cityRank: 1, tag: "Lima's cliffside modern heart" },
    { name: "Barranco", wiki: "Barranco_District", cityRank: 2, tag: "Lima's bohemian, arty corner" },
    { name: "San Isidro", wiki: "San_Isidro_District,_Lima", cityRank: 3, tag: "Lima's leafy business district" },
    { name: "Centro Histórico", wiki: "Historic_Centre_of_Lima", cityRank: 4, tag: "Colonial Lima, UNESCO-listed" },
    { name: "Chorrillos", wiki: "Chorrillos_District,_Lima", cityRank: 5, tag: "Lima's quieter seaside" },
  ]},
  { name: "Bogotá", country: "Colombia", flag: "🇨🇴", neighborhoods: [
    { name: "La Candelaria", wiki: "La_Candelaria", cityRank: 1, tag: "Colonial Bogotá and street art" },
    { name: "Chapinero", wiki: "Chapinero", cityRank: 2, tag: "Bogotá's creative, diverse heart" },
    { name: "Usaquén", wiki: "Usaquén", cityRank: 3, tag: "Sunday flea market and cobblestone calm" },
    { name: "Zona Rosa", wiki: "Zona_Rosa,_Bogotá", cityRank: 4, tag: "Bogotá's upscale nightlife" },
    { name: "Teusaquillo", wiki: "Teusaquillo", cityRank: 5, tag: "Leafy residential Bogotá" },
  ]},
  { name: "Santiago", country: "Chile", flag: "🇨🇱", neighborhoods: [
    { name: "Bellavista", wiki: "Bellavista,_Santiago", cityRank: 1, tag: "Santiago's bohemian quarter" },
    { name: "Lastarria", wiki: "Lastarria", cityRank: 2, tag: "Cafés, galleries and museums" },
    { name: "Barrio Italia", wiki: "Barrio_Italia", cityRank: 3, tag: "Antiques and design workshops" },
    { name: "Providencia", wiki: "Providencia,_Chile", cityRank: 4, tag: "Santiago's liveable modern heart" },
    { name: "Las Condes", wiki: "Las_Condes", cityRank: 5, tag: "Santiago at its most polished" },
  ]},
  { name: "Havana", country: "Cuba", flag: "🇨🇺", neighborhoods: [
    { name: "Old Havana", wiki: "Old_Havana", cityRank: 1, tag: "UNESCO-listed colonial heart" },
    { name: "Vedado", wiki: "Vedado", cityRank: 2, tag: "Havana's 20th-century grandeur" },
    { name: "Miramar", wiki: "Miramar,_Havana", cityRank: 3, tag: "Leafy, diplomatic Havana" },
    { name: "Centro Habana", wiki: "Centro_Habana", cityRank: 4, tag: "Faded, crowded, real Havana" },
    { name: "Habana del Este", wiki: "Habana_del_Este", cityRank: 5, tag: "Havana's beach side" },
  ]},
  { name: "Sydney", country: "Australia", flag: "🇦🇺", neighborhoods: [
    { name: "Surry Hills", wiki: "Surry_Hills,_New_South_Wales", cityRank: 1, tag: "Sydney's cool creative core" },
    { name: "Newtown", wiki: "Newtown,_New_South_Wales", cityRank: 2, tag: "King Street and alternative Sydney" },
    { name: "Bondi", wiki: "Bondi_Beach", cityRank: 3, tag: "Australia's most famous beach" },
    { name: "Paddington", wiki: "Paddington,_New_South_Wales", cityRank: 4, tag: "Terrace houses and Oxford Street" },
    { name: "Darlinghurst", wiki: "Darlinghurst,_New_South_Wales", cityRank: 5, tag: "Sydney's nightlife and pride" },
  ]},
  { name: "Kraków", country: "Poland", flag: "🇵🇱", neighborhoods: [
    { name: "Kazimierz", wiki: "Kazimierz", cityRank: 1, tag: "Historic Jewish quarter, reborn" },
    { name: "Stare Miasto", wiki: "Stare_Miasto,_Kraków", cityRank: 2, tag: "UNESCO medieval old town" },
    { name: "Podgórze", wiki: "Podgórze", cityRank: 3, tag: "Across the Vistula, Schindler's factory" },
    { name: "Nowa Huta", wiki: "Nowa_Huta", cityRank: 4, tag: "Kraków's socialist planned city" },
    { name: "Zwierzyniec", wiki: "Zwierzyniec_(Kraków)", cityRank: 5, tag: "Green Kraków, mounds and monasteries" },
  ]},
  { name: "Porto", country: "Portugal", flag: "🇵🇹", neighborhoods: [
    { name: "Ribeira", wiki: "Ribeira,_Porto", cityRank: 1, tag: "Porto's UNESCO riverfront" },
    { name: "Foz do Douro", wiki: "Foz_do_Douro", cityRank: 2, tag: "Where the Douro meets the Atlantic" },
    { name: "Bolhão", wiki: "Mercado_do_Bolhão", cityRank: 3, tag: "The iconic Porto market and quarter" },
    { name: "Cedofeita", wiki: "Cedofeita", cityRank: 4, tag: "Porto's arty, independent side" },
    { name: "Miragaia", wiki: "Miragaia_(Porto)", cityRank: 5, tag: "Quiet riverside Porto" },
  ]},
  { name: "Valencia", country: "Spain", flag: "🇪🇸", neighborhoods: [
    { name: "El Carmen", wiki: "El_Carmen,_Valencia", cityRank: 1, tag: "Old Valencia's medieval heart" },
    { name: "Ruzafa", wiki: "Russafa", cityRank: 2, tag: "Valencia's hippest barrio" },
    { name: "El Cabanyal", wiki: "El_Cabanyal", cityRank: 3, tag: "Valencia's fishermen's quarter" },
    { name: "Ciutat Vella", wiki: "Ciutat_Vella", cityRank: 4, tag: "Old Town Valencia" },
    { name: "Benimaclet", wiki: "Benimaclet", cityRank: 5, tag: "Valencia's student village" },
  ]},
  { name: "Marseille", country: "France", flag: "🇫🇷", neighborhoods: [
    { name: "Le Panier", wiki: "Le_Panier", cityRank: 1, tag: "Marseille's oldest quarter" },
    { name: "Cours Julien", wiki: "Cours_Julien", cityRank: 2, tag: "Street art and creative nights" },
    { name: "La Joliette", wiki: "La_Joliette", cityRank: 3, tag: "Marseille's reborn waterfront" },
    { name: "Vieux-Port", wiki: "Old_Port_of_Marseille", cityRank: 4, tag: "The ancient harbor, still working" },
    { name: "Noailles", wiki: "Noailles,_Marseille", cityRank: 5, tag: "Marseille's most multicultural market" },
  ]},

  // ── Expansion batch 2 (push past 100 cities) ──
  { name: "Montreal", country: "Canada", flag: "🇨🇦", neighborhoods: [
    { name: "Mile End", wiki: "Mile_End,_Montreal", cityRank: 1, tag: "Montreal's literary, indie heart" },
    { name: "Plateau", wiki: "Le_Plateau-Mont-Royal", cityRank: 2, tag: "Murals, brunch and spiral staircases" },
    { name: "Old Montreal", wiki: "Old_Montreal", cityRank: 3, tag: "Cobblestone Vieux-Montréal" },
    { name: "Little Italy", wiki: "Little_Italy,_Montreal", cityRank: 4, tag: "Jean-Talon market and espresso culture" },
    { name: "Griffintown", wiki: "Griffintown", cityRank: 5, tag: "Montreal's reborn canal district" },
  ]},
  { name: "Vancouver", country: "Canada", flag: "🇨🇦", neighborhoods: [
    { name: "Gastown", wiki: "Gastown", cityRank: 1, tag: "Cobblestone Vancouver, reborn" },
    { name: "Yaletown", wiki: "Yaletown", cityRank: 2, tag: "Brick warehouses and seawall views" },
    { name: "Kitsilano", wiki: "Kitsilano", cityRank: 3, tag: "Beaches and yoga-mat cool" },
    { name: "Commercial Drive", wiki: "Commercial_Drive,_Vancouver", cityRank: 4, tag: "Vancouver's multicultural main street" },
    { name: "Main Street", wiki: "Mount_Pleasant,_Vancouver", cityRank: 5, tag: "Breweries, bikes and the new creative core" },
  ]},
  { name: "Oslo", country: "Norway", flag: "🇳🇴", neighborhoods: [
    { name: "Grünerløkka", wiki: "Grünerløkka", cityRank: 1, tag: "Oslo's hippest riverside district" },
    { name: "Frogner", wiki: "Frogner", cityRank: 2, tag: "Oslo at its most elegant" },
    { name: "Grønland", wiki: "Grønland,_Oslo", cityRank: 3, tag: "Oslo's multicultural core" },
    { name: "Majorstuen", wiki: "Majorstuen", cityRank: 4, tag: "Cafés, shopping and trams" },
    { name: "Tjuvholmen", wiki: "Tjuvholmen", cityRank: 5, tag: "Oslo's waterfront contemporary district" },
  ]},
  { name: "Helsinki", country: "Finland", flag: "🇫🇮", neighborhoods: [
    { name: "Kallio", wiki: "Kallio", cityRank: 1, tag: "Helsinki's bohemian heart" },
    { name: "Punavuori", wiki: "Punavuori", cityRank: 2, tag: "Design District Helsinki" },
    { name: "Kruununhaka", wiki: "Kruununhaka", cityRank: 3, tag: "Neoclassical Helsinki" },
    { name: "Töölö", wiki: "Töölö", cityRank: 4, tag: "Quiet, cultured Helsinki" },
    { name: "Kamppi", wiki: "Kamppi", cityRank: 5, tag: "Helsinki's busy central core" },
  ]},
  { name: "Zurich", country: "Switzerland", flag: "🇨🇭", neighborhoods: [
    { name: "Altstadt", wiki: "Altstadt_(Zurich)", cityRank: 1, tag: "Medieval Zürich on the river" },
    { name: "Kreis 4", wiki: "Aussersihl", cityRank: 2, tag: "Zurich's creative multicultural quarter" },
    { name: "Kreis 5", wiki: "Zürich-West", cityRank: 3, tag: "Industrial Zurich reborn" },
    { name: "Wiedikon", wiki: "Wiedikon", cityRank: 4, tag: "Quiet, diverse residential Zurich" },
    { name: "Seefeld", wiki: "Seefeld_(Zürich)", cityRank: 5, tag: "Lakeside luxury Zurich" },
  ]},
  { name: "Brussels", country: "Belgium", flag: "🇧🇪", neighborhoods: [
    { name: "Sablon", wiki: "Sablon/Zavel", cityRank: 1, tag: "Antiques, chocolate and Art Nouveau" },
    { name: "Ixelles", wiki: "Ixelles", cityRank: 2, tag: "Brussels' young, creative heart" },
    { name: "Saint-Gilles", wiki: "Saint-Gilles,_Belgium", cityRank: 3, tag: "Art Nouveau and boho cafés" },
    { name: "Dansaert", wiki: "Sainte-Catherine,_Brussels", cityRank: 4, tag: "Brussels' design and fashion quarter" },
    { name: "Marolles", wiki: "Marolles/Marollen", cityRank: 5, tag: "Brussels' flea-market bohemia" },
  ]},
  { name: "Florence", country: "Italy", flag: "🇮🇹", neighborhoods: [
    { name: "Oltrarno", wiki: "Oltrarno", cityRank: 1, tag: "Florence's artisan left bank" },
    { name: "Santa Croce", wiki: "Santa_Croce,_Florence", cityRank: 2, tag: "Florence around the basilica" },
    { name: "San Niccolò", wiki: "San_Niccolò,_Florence", cityRank: 3, tag: "Rooftop views and aperitivo" },
    { name: "San Lorenzo", wiki: "San_Lorenzo,_Florence", cityRank: 4, tag: "Central Market and Medici chapels" },
    { name: "San Marco", wiki: "San_Marco,_Florence", cityRank: 5, tag: "The Accademia and museum-rich north" },
  ]},
  { name: "Naples", country: "Italy", flag: "🇮🇹", neighborhoods: [
    { name: "Centro Storico", wiki: "Centro_Storico,_Naples", cityRank: 1, tag: "UNESCO Naples, chaotic and alive" },
    { name: "Vomero", wiki: "Vomero", cityRank: 2, tag: "Hilltop Naples, views to die for" },
    { name: "Chiaia", wiki: "Chiaia", cityRank: 3, tag: "Naples' most elegant seafront" },
    { name: "Quartieri Spagnoli", wiki: "Quartieri_Spagnoli", cityRank: 4, tag: "Narrow lanes and street life" },
    { name: "Posillipo", wiki: "Posillipo", cityRank: 5, tag: "Cliffside Naples" },
  ]},
  { name: "Venice", country: "Italy", flag: "🇮🇹", neighborhoods: [
    { name: "Dorsoduro", wiki: "Dorsoduro", cityRank: 1, tag: "Venice's art district" },
    { name: "Cannaregio", wiki: "Cannaregio", cityRank: 2, tag: "Local Venice, the Jewish Ghetto" },
    { name: "San Polo", wiki: "San_Polo", cityRank: 3, tag: "The Rialto and the smallest sestiere" },
    { name: "Castello", wiki: "Castello,_Venice", cityRank: 4, tag: "The quietest corner of Venice" },
    { name: "Giudecca", wiki: "Giudecca", cityRank: 5, tag: "Venice's island retreat" },
  ]},
  { name: "Bologna", country: "Italy", flag: "🇮🇹", neighborhoods: [
    { name: "Centro Storico", wiki: "Bologna", cityRank: 1, tag: "Porticoes and the food capital of Italy" },
    { name: "Via del Pratello", wiki: "Via_del_Pratello", cityRank: 2, tag: "Bologna's lively nightlife street" },
    { name: "Quadrilatero", wiki: "Quadrilatero_(Bologna)", cityRank: 3, tag: "Medieval food market" },
    { name: "Santo Stefano", wiki: "Santo_Stefano,_Bologna", cityRank: 4, tag: "Seven churches and porticoes" },
    { name: "San Petronio", wiki: "Basilica_of_San_Petronio", cityRank: 5, tag: "Bologna's central piazza" },
  ]},
  { name: "Kraków", country: "Poland", flag: "🇵🇱", neighborhoods: [
    { name: "Kazimierz", wiki: "Kazimierz", cityRank: 1, tag: "Historic Jewish Kraków" },
    { name: "Stare Miasto", wiki: "Stare_Miasto,_Kraków", cityRank: 2, tag: "UNESCO medieval old town" },
    { name: "Podgórze", wiki: "Podgórze", cityRank: 3, tag: "Across the Vistula" },
    { name: "Nowa Huta", wiki: "Nowa_Huta", cityRank: 4, tag: "Kraków's socialist district" },
    { name: "Kleparz", wiki: "Kleparz", cityRank: 5, tag: "Central Kraków's market quarter" },
  ]},
  { name: "Reykjavik", country: "Iceland", flag: "🇮🇸", neighborhoods: [
    { name: "101 Reykjavik", wiki: "101_Reykjavík", cityRank: 1, tag: "Downtown Reykjavik's arts core" },
    { name: "Laugavegur", wiki: "Laugavegur_(street)", cityRank: 2, tag: "Reykjavik's main shopping street" },
    { name: "Grandi", wiki: "Grandi_(Reykjavík)", cityRank: 3, tag: "Reykjavik's new waterfront" },
    { name: "Vesturbær", wiki: "Vesturbær", cityRank: 4, tag: "Reykjavik's quiet west" },
    { name: "Hlíðar", wiki: "Hlíðar", cityRank: 5, tag: "Residential Reykjavik" },
  ]},
  { name: "Tbilisi", country: "Georgia", flag: "🇬🇪", neighborhoods: [
    { name: "Old Tbilisi", wiki: "Old_Tbilisi", cityRank: 1, tag: "Sulphur baths and wooden balconies" },
    { name: "Sololaki", wiki: "Sololaki", cityRank: 2, tag: "Tbilisi's artistic old quarter" },
    { name: "Vera", wiki: "Vera_(Tbilisi)", cityRank: 3, tag: "Tbilisi's bohemian riverside" },
    { name: "Vake", wiki: "Vake_District", cityRank: 4, tag: "Leafy, upscale Tbilisi" },
    { name: "Saburtalo", wiki: "Saburtalo_District", cityRank: 5, tag: "Modern residential Tbilisi" },
  ]},
  { name: "Kyiv", country: "Ukraine", flag: "🇺🇦", neighborhoods: [
    { name: "Podil", wiki: "Podil", cityRank: 1, tag: "Kyiv's historic Dnipro-side district" },
    { name: "Pechersk", wiki: "Pechersk_Raion", cityRank: 2, tag: "Government and golden monasteries" },
    { name: "Shevchenkivskyi", wiki: "Shevchenkivskyi_District", cityRank: 3, tag: "Central, cultured Kyiv" },
    { name: "Obolon", wiki: "Obolon_Raion", cityRank: 4, tag: "Riverside Kyiv" },
    { name: "Lypky", wiki: "Lypky", cityRank: 5, tag: "Kyiv's most elegant central area" },
  ]},
  { name: "Sofia", country: "Bulgaria", flag: "🇧🇬", neighborhoods: [
    { name: "Oborishte", wiki: "Oborishte", cityRank: 1, tag: "Sofia's elegant central quarter" },
    { name: "Lozenets", wiki: "Lozenets", cityRank: 2, tag: "Sofia's trendy upscale district" },
    { name: "Mladost", wiki: "Mladost,_Sofia", cityRank: 3, tag: "Sofia's biggest residential quarter" },
    { name: "Vazrazhdane", wiki: "Vazrazhdane,_Sofia", cityRank: 4, tag: "Sofia's old central district" },
    { name: "Studentski", wiki: "Studentski,_Sofia", cityRank: 5, tag: "University Sofia" },
  ]},
  { name: "Bucharest", country: "Romania", flag: "🇷🇴", neighborhoods: [
    { name: "Lipscani", wiki: "Lipscani", cityRank: 1, tag: "Bucharest's historic old town" },
    { name: "Dorobanți", wiki: "Dorobanți", cityRank: 2, tag: "Elegant, leafy Bucharest" },
    { name: "Cotroceni", wiki: "Cotroceni", cityRank: 3, tag: "Belle Époque mansions" },
    { name: "Primăverii", wiki: "Primăverii", cityRank: 4, tag: "Bucharest's embassy quarter" },
    { name: "Floreasca", wiki: "Floreasca", cityRank: 5, tag: "Bucharest's lake-adjacent new core" },
  ]},
  { name: "Belgrade", country: "Serbia", flag: "🇷🇸", neighborhoods: [
    { name: "Stari Grad", wiki: "Stari_Grad,_Belgrade", cityRank: 1, tag: "Old Belgrade and the Kalemegdan fortress" },
    { name: "Savamala", wiki: "Savamala", cityRank: 2, tag: "Belgrade's riverside creative district" },
    { name: "Dorćol", wiki: "Dorćol", cityRank: 3, tag: "Historic Danube-side Belgrade" },
    { name: "Zemun", wiki: "Zemun", cityRank: 4, tag: "Austro-Hungarian Belgrade" },
    { name: "Vračar", wiki: "Vračar", cityRank: 5, tag: "Belgrade's cultured central district" },
  ]},
  { name: "Zagreb", country: "Croatia", flag: "🇭🇷", neighborhoods: [
    { name: "Gornji Grad", wiki: "Gornji_Grad,_Zagreb", cityRank: 1, tag: "Zagreb's upper town" },
    { name: "Donji Grad", wiki: "Donji_Grad,_Zagreb", cityRank: 2, tag: "Habsburg Zagreb below the hill" },
    { name: "Trešnjevka", wiki: "Trešnjevka", cityRank: 3, tag: "Zagreb's creative neighborhood" },
    { name: "Maksimir", wiki: "Maksimir", cityRank: 4, tag: "Zagreb's biggest park" },
    { name: "Britanski trg", wiki: "Britanski_trg", cityRank: 5, tag: "Zagreb's Sunday antique square" },
  ]},
  { name: "Ljubljana", country: "Slovenia", flag: "🇸🇮", neighborhoods: [
    { name: "Old Town", wiki: "Old_Ljubljana", cityRank: 1, tag: "Ljubljana's castle-hill heart" },
    { name: "Metelkova", wiki: "Metelkova", cityRank: 2, tag: "Ljubljana's autonomous culture zone" },
    { name: "Trnovo", wiki: "Trnovo_District", cityRank: 3, tag: "Ljubljana's riverside artsy corner" },
    { name: "Krakovo", wiki: "Krakovo", cityRank: 4, tag: "Ljubljana's historic village-in-the-city" },
    { name: "Šiška", wiki: "Šiška_District", cityRank: 5, tag: "Ljubljana's most populous district" },
  ]},
  { name: "Rotterdam", country: "Netherlands", flag: "🇳🇱", neighborhoods: [
    { name: "Katendrecht", wiki: "Katendrecht", cityRank: 1, tag: "Rotterdam's reborn peninsula" },
    { name: "Witte de Withstraat", wiki: "Witte_de_Withstraat", cityRank: 2, tag: "Rotterdam's art and bar street" },
    { name: "Kop van Zuid", wiki: "Kop_van_Zuid", cityRank: 3, tag: "Rotterdam's dramatic new skyline" },
    { name: "Delfshaven", wiki: "Delfshaven", cityRank: 4, tag: "Old Rotterdam that survived WWII" },
    { name: "Cool District", wiki: "Cool,_Rotterdam", cityRank: 5, tag: "Central Rotterdam, for real" },
  ]},
  { name: "Antwerp", country: "Belgium", flag: "🇧🇪", neighborhoods: [
    { name: "Het Zuid", wiki: "Zuid,_Antwerp", cityRank: 1, tag: "Antwerp's museum and design quarter" },
    { name: "Historic Centre", wiki: "Historic_Centre_of_Antwerp", cityRank: 2, tag: "Diamond city's medieval core" },
    { name: "Eilandje", wiki: "Eilandje", cityRank: 3, tag: "Antwerp's reborn docklands" },
    { name: "Zurenborg", wiki: "Zurenborg", cityRank: 4, tag: "Art Nouveau Antwerp" },
    { name: "Meir", wiki: "Meir", cityRank: 5, tag: "Antwerp's grand shopping street" },
  ]},
  { name: "Glasgow", country: "United Kingdom", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", neighborhoods: [
    { name: "Merchant City", wiki: "Merchant_City", cityRank: 1, tag: "Glasgow's design and culture quarter" },
    { name: "West End", wiki: "West_End,_Glasgow", cityRank: 2, tag: "Glasgow's university village" },
    { name: "Finnieston", wiki: "Finnieston", cityRank: 3, tag: "Glasgow's foodie corridor" },
    { name: "Southside", wiki: "Southside,_Glasgow", cityRank: 4, tag: "Glasgow's multicultural south" },
    { name: "Dennistoun", wiki: "Dennistoun", cityRank: 5, tag: "Glasgow's East End rising" },
  ]},
  { name: "Manchester", country: "United Kingdom", flag: "🇬🇧", neighborhoods: [
    { name: "Northern Quarter", wiki: "Northern_Quarter,_Manchester", cityRank: 1, tag: "Manchester's indie creative hub" },
    { name: "Ancoats", wiki: "Ancoats", cityRank: 2, tag: "The world's first industrial suburb" },
    { name: "Deansgate", wiki: "Deansgate", cityRank: 3, tag: "Manchester's main shopping street" },
    { name: "Spinningfields", wiki: "Spinningfields", cityRank: 4, tag: "Manchester's new business district" },
    { name: "Chorlton", wiki: "Chorlton-cum-Hardy", cityRank: 5, tag: "Manchester's liberal village" },
  ]},
  { name: "Bristol", country: "United Kingdom", flag: "🇬🇧", neighborhoods: [
    { name: "Stokes Croft", wiki: "Stokes_Croft", cityRank: 1, tag: "Bristol's street-art capital" },
    { name: "Clifton", wiki: "Clifton,_Bristol", cityRank: 2, tag: "Georgian Bristol above the Gorge" },
    { name: "Harbourside", wiki: "Bristol_Harbour", cityRank: 3, tag: "Bristol's reborn waterfront" },
    { name: "Gloucester Road", wiki: "Gloucester_Road,_Bristol", cityRank: 4, tag: "UK's longest stretch of indie shops" },
    { name: "Southville", wiki: "Southville,_Bristol", cityRank: 5, tag: "Bristol's south-side creative village" },
  ]},
  { name: "Birmingham", country: "United Kingdom", flag: "🇬🇧", neighborhoods: [
    { name: "Digbeth", wiki: "Digbeth", cityRank: 1, tag: "Birmingham's creative old industrial district" },
    { name: "Jewellery Quarter", wiki: "Jewellery_Quarter", cityRank: 2, tag: "200 years of Birmingham craftsmanship" },
    { name: "Moseley", wiki: "Moseley", cityRank: 3, tag: "Birmingham's leafy bohemian village" },
    { name: "Kings Heath", wiki: "Kings_Heath", cityRank: 4, tag: "Birmingham's independent main street" },
    { name: "Harborne", wiki: "Harborne", cityRank: 5, tag: "Birmingham's smartest suburb" },
  ]},
  { name: "Liverpool", country: "United Kingdom", flag: "🇬🇧", neighborhoods: [
    { name: "Baltic Triangle", wiki: "Baltic_Triangle", cityRank: 1, tag: "Liverpool's creative post-industrial quarter" },
    { name: "Ropewalks", wiki: "Ropewalks", cityRank: 2, tag: "Liverpool's bar and restaurant core" },
    { name: "Albert Dock", wiki: "Royal_Albert_Dock", cityRank: 3, tag: "UNESCO-listed Liverpool waterfront" },
    { name: "Georgian Quarter", wiki: "Canning,_Liverpool", cityRank: 4, tag: "Liverpool's best-preserved historic streets" },
    { name: "Lark Lane", wiki: "Lark_Lane", cityRank: 5, tag: "Liverpool's boho café strip" },
  ]},
  { name: "Leeds", country: "United Kingdom", flag: "🇬🇧", neighborhoods: [
    { name: "Call Lane", wiki: "Call_Lane", cityRank: 1, tag: "Leeds' drinking heart" },
    { name: "Chapel Allerton", wiki: "Chapel_Allerton", cityRank: 2, tag: "Leeds' leafy, brunch-loving village" },
    { name: "Headingley", wiki: "Headingley", cityRank: 3, tag: "Leeds' student and cricket district" },
    { name: "Kirkgate", wiki: "Kirkgate,_Leeds", cityRank: 4, tag: "Leeds' oldest street" },
    { name: "Roundhay", wiki: "Roundhay", cityRank: 5, tag: "Leeds' grand park neighborhood" },
  ]},
  { name: "Nairobi", country: "Kenya", flag: "🇰🇪", neighborhoods: [
    { name: "Westlands", wiki: "Westlands,_Nairobi", cityRank: 1, tag: "Nairobi's business and dining core" },
    { name: "Karen", wiki: "Karen,_Nairobi", cityRank: 2, tag: "Green, colonial-era Nairobi" },
    { name: "Lavington", wiki: "Lavington,_Nairobi", cityRank: 3, tag: "Nairobi's leafy western suburb" },
    { name: "Kilimani", wiki: "Kilimani", cityRank: 4, tag: "Nairobi's modern central quarter" },
    { name: "Hurlingham", wiki: "Hurlingham,_Nairobi", cityRank: 5, tag: "Nairobi's central shopping village" },
  ]},
  { name: "Lagos", country: "Nigeria", flag: "🇳🇬", neighborhoods: [
    { name: "Victoria Island", wiki: "Victoria_Island,_Lagos", cityRank: 1, tag: "Lagos' business and nightlife core" },
    { name: "Ikoyi", wiki: "Ikoyi", cityRank: 2, tag: "Lagos' most upscale quarter" },
    { name: "Lekki", wiki: "Lekki", cityRank: 3, tag: "Lagos' newest peninsula" },
    { name: "Lagos Island", wiki: "Lagos_Island", cityRank: 4, tag: "The historic heart of Lagos" },
    { name: "Yaba", wiki: "Yaba,_Lagos", cityRank: 5, tag: "Lagos' tech and student district" },
  ]},
  { name: "Accra", country: "Ghana", flag: "🇬🇭", neighborhoods: [
    { name: "Osu", wiki: "Osu,_Ghana", cityRank: 1, tag: "Accra's nightlife and restaurant spine" },
    { name: "East Legon", wiki: "East_Legon", cityRank: 2, tag: "Accra's polished new suburbs" },
    { name: "Jamestown", wiki: "Jamestown,_Accra", cityRank: 3, tag: "Accra's historic fishing quarter" },
    { name: "Labone", wiki: "Labone", cityRank: 4, tag: "Accra's embassy row" },
    { name: "Airport Residential", wiki: "Airport_Residential_Area", cityRank: 5, tag: "Accra's most affluent district" },
  ]},
  { name: "Addis Ababa", country: "Ethiopia", flag: "🇪🇹", neighborhoods: [
    { name: "Bole", wiki: "Bole,_Addis_Ababa", cityRank: 1, tag: "Addis' modern cosmopolitan heart" },
    { name: "Piassa", wiki: "Piassa_(Addis_Ababa)", cityRank: 2, tag: "Historic Italian-influenced Addis" },
    { name: "Kazanchis", wiki: "Kazanchis", cityRank: 3, tag: "Addis' new diplomatic district" },
    { name: "Merkato", wiki: "Mercato_(Addis_Ababa)", cityRank: 4, tag: "Africa's largest open-air market" },
    { name: "Arat Kilo", wiki: "Arat_Kilo", cityRank: 5, tag: "Addis' political core" },
  ]},
  { name: "Johannesburg", country: "South Africa", flag: "🇿🇦", neighborhoods: [
    { name: "Maboneng", wiki: "Maboneng_Precinct", cityRank: 1, tag: "Johannesburg's reborn creative district" },
    { name: "Braamfontein", wiki: "Braamfontein", cityRank: 2, tag: "Joburg's student and arts quarter" },
    { name: "Melville", wiki: "Melville,_Gauteng", cityRank: 3, tag: "Joburg's bohemian quarter" },
    { name: "Rosebank", wiki: "Rosebank,_Gauteng", cityRank: 4, tag: "Johannesburg's most liveable core" },
    { name: "Sandton", wiki: "Sandton", cityRank: 5, tag: "Africa's richest square mile" },
  ]},
  { name: "Beirut", country: "Lebanon", flag: "🇱🇧", neighborhoods: [
    { name: "Gemmayzeh", wiki: "Gemmayzeh", cityRank: 1, tag: "Beirut's beloved bar street" },
    { name: "Mar Mikhael", wiki: "Mar_Mikhael", cityRank: 2, tag: "Beirut's creative nightlife hub" },
    { name: "Hamra", wiki: "Hamra_Street", cityRank: 3, tag: "Beirut's historic café street" },
    { name: "Achrafieh", wiki: "Achrafieh", cityRank: 4, tag: "East Beirut's elegant heights" },
    { name: "Downtown", wiki: "Beirut_Central_District", cityRank: 5, tag: "Beirut's rebuilt heart" },
  ]},
  { name: "Amman", country: "Jordan", flag: "🇯🇴", neighborhoods: [
    { name: "Jabal Amman", wiki: "Jabal_Amman", cityRank: 1, tag: "Amman's historic first hill" },
    { name: "Jabal al-Weibdeh", wiki: "Jabal_Al-Weibdeh", cityRank: 2, tag: "Amman's artistic hilltop village" },
    { name: "Rainbow Street", wiki: "Rainbow_Street", cityRank: 3, tag: "Amman's café and boutique strip" },
    { name: "Abdoun", wiki: "Abdoun", cityRank: 4, tag: "Amman's upscale western quarter" },
    { name: "Downtown Amman", wiki: "Downtown_Amman", cityRank: 5, tag: "Amman's historic bazaar core" },
  ]},
  { name: "Tehran", country: "Iran", flag: "🇮🇷", neighborhoods: [
    { name: "Tajrish", wiki: "Tajrish", cityRank: 1, tag: "Northern Tehran's ancient bazaar" },
    { name: "Darband", wiki: "Darband,_Tehran", cityRank: 2, tag: "Mountain Tehran's river restaurants" },
    { name: "Grand Bazaar", wiki: "Grand_Bazaar,_Tehran", cityRank: 3, tag: "The beating commercial heart of Tehran" },
    { name: "Niavaran", wiki: "Niavaran", cityRank: 4, tag: "Tehran's royal gardens" },
    { name: "Valiasr", wiki: "Valiasr_Street", cityRank: 5, tag: "Tehran's famous plane-tree avenue" },
  ]},
  { name: "Riyadh", country: "Saudi Arabia", flag: "🇸🇦", neighborhoods: [
    { name: "Diriyah", wiki: "Diriyah", cityRank: 1, tag: "The Saudi state's UNESCO birthplace" },
    { name: "Olaya", wiki: "Al_Olaya", cityRank: 2, tag: "Riyadh's shimmering central district" },
    { name: "Diplomatic Quarter", wiki: "Diplomatic_Quarter,_Riyadh", cityRank: 3, tag: "Riyadh's leafy embassy enclave" },
    { name: "King Abdullah Financial District", wiki: "King_Abdullah_Financial_District", cityRank: 4, tag: "Riyadh's skyline of the future" },
    { name: "Al-Bathaa", wiki: "Al_Bathaa", cityRank: 5, tag: "Old Riyadh's historic core" },
  ]},
  { name: "Doha", country: "Qatar", flag: "🇶🇦", neighborhoods: [
    { name: "Souq Waqif", wiki: "Souq_Waqif", cityRank: 1, tag: "Doha's restored historic souq" },
    { name: "West Bay", wiki: "West_Bay,_Doha", cityRank: 2, tag: "Doha's skyscraper waterfront" },
    { name: "The Pearl", wiki: "The_Pearl-Qatar", cityRank: 3, tag: "Doha's artificial island luxury" },
    { name: "Msheireb", wiki: "Msheireb", cityRank: 4, tag: "Doha's rebuilt downtown" },
    { name: "Katara", wiki: "Katara_Cultural_Village", cityRank: 5, tag: "Doha's cultural village" },
  ]},
  { name: "Ho Chi Minh City", country: "Vietnam", flag: "🇻🇳", neighborhoods: [
    { name: "District 1", wiki: "District_1", cityRank: 1, tag: "Saigon's central, colonial core" },
    { name: "District 3", wiki: "District_3", cityRank: 2, tag: "Quiet, leafy central Saigon" },
    { name: "Thao Dien", wiki: "Thao_Dien", cityRank: 3, tag: "Saigon's expat village" },
    { name: "Cho Lon", wiki: "Cholon,_Ho_Chi_Minh_City", cityRank: 4, tag: "Saigon's historic Chinatown" },
    { name: "District 7", wiki: "District_7,_Ho_Chi_Minh_City", cityRank: 5, tag: "Saigon's new southern district" },
  ]},
  { name: "Hanoi", country: "Vietnam", flag: "🇻🇳", neighborhoods: [
    { name: "Old Quarter", wiki: "Hanoi_Old_Quarter", cityRank: 1, tag: "36 streets of ancient Hanoi" },
    { name: "French Quarter", wiki: "French_Quarter,_Hanoi", cityRank: 2, tag: "Colonial Hanoi, tree-lined" },
    { name: "Tay Ho", wiki: "Tây_Hồ_District", cityRank: 3, tag: "Hanoi's lakeside expat core" },
    { name: "Ba Dinh", wiki: "Ba_Đình_District", cityRank: 4, tag: "Hanoi's political heart" },
    { name: "Long Bien", wiki: "Long_Biên_District", cityRank: 5, tag: "Across the Red River" },
  ]},
  { name: "Manila", country: "Philippines", flag: "🇵🇭", neighborhoods: [
    { name: "Intramuros", wiki: "Intramuros", cityRank: 1, tag: "Old walled Manila" },
    { name: "Makati", wiki: "Makati", cityRank: 2, tag: "Manila's gleaming business district" },
    { name: "Bonifacio Global City", wiki: "Bonifacio_Global_City", cityRank: 3, tag: "Manila's planned new downtown" },
    { name: "Malate", wiki: "Malate,_Manila", cityRank: 4, tag: "Old Manila nightlife" },
    { name: "Poblacion", wiki: "Poblacion,_Makati", cityRank: 5, tag: "Manila's coolest bar district" },
  ]},
  { name: "Bali (Ubud)", country: "Indonesia", flag: "🇮🇩", neighborhoods: [
    { name: "Ubud Centre", wiki: "Ubud", cityRank: 1, tag: "Bali's cultural heart among the rice fields" },
    { name: "Seminyak", wiki: "Seminyak", cityRank: 2, tag: "Bali's stylish beach strip" },
    { name: "Canggu", wiki: "Canggu", cityRank: 3, tag: "Bali's digital nomad village" },
    { name: "Sanur", wiki: "Sanur,_Bali", cityRank: 4, tag: "Bali's quieter east coast" },
    { name: "Jimbaran", wiki: "Jimbaran", cityRank: 5, tag: "Seafood beach Bali" },
  ]},
];
