// scripts/cities-seed.mjs
// Curated seed list: city → 5 neighborhoods with editorial tags + Wikipedia article titles.
// The enrichment script fetches each Wikipedia summary and builds the final data file.
// To expand coverage: append new CITIES entries here and re-run `node scripts/fetch-neighborhoods.mjs`.

export const CITIES = [
  { name: "New York", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Williamsburg", wiki: "Williamsburg,_Brooklyn", cityRank: 1, tag: "The creative capital of Brooklyn" },
    { name: "West Village", wiki: "West_Village", cityRank: 2, tag: "Cobblestone charm in the heart of Manhattan" },
    { name: "Lower East Side", wiki: "Lower_East_Side", cityRank: 3, tag: "Where old New York meets the new avant-garde" },
    { name: "Harlem", wiki: "Harlem", cityRank: 4, tag: "The cultural soul of Uptown" },
    { name: "SoHo", wiki: "SoHo,_Manhattan", cityRank: 5, tag: "Cast-iron architecture meets world-class shopping" },
  ]},
  { name: "London", country: "United Kingdom", flag: "🇬🇧", neighborhoods: [
    { name: "Shoreditch", wiki: "Shoreditch", cityRank: 1, tag: "East London's creative engine room" },
    { name: "Notting Hill", wiki: "Notting_Hill", cityRank: 2, tag: "Pastel houses and Portobello treasures" },
    { name: "Soho", wiki: "Soho", cityRank: 3, tag: "London's beating, neon-lit heart" },
    { name: "Peckham", wiki: "Peckham", cityRank: 4, tag: "South London's coolest rooftop" },
    { name: "Hackney", wiki: "Hackney_Central", cityRank: 5, tag: "Canal-side cool and killer coffee" },
  ]},
  { name: "Paris", country: "France", flag: "🇫🇷", neighborhoods: [
    { name: "Le Marais", wiki: "Le_Marais", cityRank: 1, tag: "Medieval Paris, perfectly preserved" },
    { name: "Canal Saint-Martin", wiki: "Canal_Saint-Martin", cityRank: 2, tag: "Where Paris comes to picnic" },
    { name: "Montmartre", wiki: "Montmartre", cityRank: 3, tag: "Bohemian Paris on the hill" },
    { name: "Belleville", wiki: "Belleville,_Paris", cityRank: 4, tag: "Paris at its most cosmopolitan" },
    { name: "Saint-Germain-des-Prés", wiki: "Saint-Germain-des-Prés", cityRank: 5, tag: "Intellectual Paris in cashmere and linen" },
  ]},
  { name: "Tokyo", country: "Japan", flag: "🇯🇵", neighborhoods: [
    { name: "Shimokitazawa", wiki: "Shimokitazawa", cityRank: 1, tag: "Tokyo's indie soul" },
    { name: "Shibuya", wiki: "Shibuya", cityRank: 2, tag: "The world's most famous crosswalk" },
    { name: "Daikanyama", wiki: "Daikanyama", cityRank: 3, tag: "Tokyo's quiet luxury village" },
    { name: "Yanaka", wiki: "Yanaka,_Tokyo", cityRank: 4, tag: "Old Tokyo frozen in time" },
    { name: "Shinjuku", wiki: "Shinjuku", cityRank: 5, tag: "Neon, skyscrapers and Golden Gai" },
  ]},
  { name: "Berlin", country: "Germany", flag: "🇩🇪", neighborhoods: [
    { name: "Kreuzberg", wiki: "Kreuzberg", cityRank: 1, tag: "Berlin's punk heart, still beating" },
    { name: "Neukölln", wiki: "Neukölln", cityRank: 2, tag: "Where Berlin moves next" },
    { name: "Prenzlauer Berg", wiki: "Prenzlauer_Berg", cityRank: 3, tag: "Cobblestones, cafés and quiet corners" },
    { name: "Friedrichshain", wiki: "Friedrichshain", cityRank: 4, tag: "Club capital of the continent" },
    { name: "Mitte", wiki: "Mitte", cityRank: 5, tag: "History, galleries and the city's front door" },
  ]},
  { name: "Barcelona", country: "Spain", flag: "🇪🇸", neighborhoods: [
    { name: "El Born", wiki: "El_Born,_Barcelona", cityRank: 1, tag: "Medieval streets, modern cocktails" },
    { name: "Gràcia", wiki: "Gràcia", cityRank: 2, tag: "Barcelona's village within the city" },
    { name: "El Raval", wiki: "El_Raval", cityRank: 3, tag: "Gritty, global and wildly alive" },
    { name: "Poble Sec", wiki: "Poble-sec", cityRank: 4, tag: "Tapas on Carrer Blai, sunset on Montjuïc" },
    { name: "Poblenou", wiki: "Poblenou", cityRank: 5, tag: "Barcelona's post-industrial playground" },
  ]},
  { name: "Mexico City", country: "Mexico", flag: "🇲🇽", neighborhoods: [
    { name: "Roma Norte", wiki: "Colonia_Roma", cityRank: 1, tag: "CDMX's creative epicenter" },
    { name: "Condesa", wiki: "Condesa", cityRank: 2, tag: "Art deco, green spaces, great food" },
    { name: "Coyoacán", wiki: "Coyoacán", cityRank: 3, tag: "Frida's cobblestone village" },
    { name: "Polanco", wiki: "Polanco,_Mexico_City", cityRank: 4, tag: "CDMX at its most polished" },
    { name: "Centro Histórico", wiki: "Historic_center_of_Mexico_City", cityRank: 5, tag: "The beating, historic heart of CDMX" },
  ]},
  { name: "Buenos Aires", country: "Argentina", flag: "🇦🇷", neighborhoods: [
    { name: "Palermo", wiki: "Palermo,_Buenos_Aires", cityRank: 1, tag: "The coolest grid in Latin America" },
    { name: "San Telmo", wiki: "San_Telmo", cityRank: 2, tag: "Tango, antiques, Sunday afternoons" },
    { name: "Recoleta", wiki: "Recoleta,_Buenos_Aires", cityRank: 3, tag: "Parisian elegance in the Southern Hemisphere" },
    { name: "Villa Crespo", wiki: "Villa_Crespo", cityRank: 4, tag: "Palermo's quieter, cheaper sibling" },
    { name: "La Boca", wiki: "La_Boca", cityRank: 5, tag: "Painted houses and Maradona's ghost" },
  ]},
  { name: "Melbourne", country: "Australia", flag: "🇦🇺", neighborhoods: [
    { name: "Fitzroy", wiki: "Fitzroy,_Victoria", cityRank: 1, tag: "Australia's original cool neighborhood" },
    { name: "Collingwood", wiki: "Collingwood,_Victoria", cityRank: 2, tag: "Fitzroy's rougher, realer neighbor" },
    { name: "Brunswick", wiki: "Brunswick,_Victoria", cityRank: 3, tag: "Live music and the best pizza in town" },
    { name: "St Kilda", wiki: "St_Kilda,_Victoria", cityRank: 4, tag: "Beachside bohemia" },
    { name: "Carlton", wiki: "Carlton,_Victoria", cityRank: 5, tag: "Melbourne's Little Italy, with a PhD" },
  ]},
  { name: "Singapore", country: "Singapore", flag: "🇸🇬", neighborhoods: [
    { name: "Tiong Bahru", wiki: "Tiong_Bahru", cityRank: 1, tag: "Art deco, hawker food, perfect coffee" },
    { name: "Kampong Glam", wiki: "Kampong_Glam", cityRank: 2, tag: "Haji Lane, the Sultan Mosque and street art" },
    { name: "Chinatown", wiki: "Chinatown,_Singapore", cityRank: 3, tag: "Hawker heritage meets craft cocktails" },
    { name: "Katong", wiki: "Katong", cityRank: 4, tag: "Peranakan heritage and laksa perfection" },
    { name: "Dempsey Hill", wiki: "Dempsey_Hill", cityRank: 5, tag: "Jungle, restaurants, hidden calm" },
  ]},
  { name: "Amsterdam", country: "Netherlands", flag: "🇳🇱", neighborhoods: [
    { name: "Jordaan", wiki: "Jordaan", cityRank: 1, tag: "Amsterdam's most charming canals" },
    { name: "De Pijp", wiki: "De_Pijp", cityRank: 2, tag: "The Albert Cuyp market and brunch capital" },
    { name: "Amsterdam-Oost", wiki: "Amsterdam-Oost", cityRank: 3, tag: "Where Amsterdam actually hangs out" },
    { name: "Amsterdam-Noord", wiki: "Amsterdam-Noord", cityRank: 4, tag: "A free ferry ride to the future" },
    { name: "De Baarsjes", wiki: "De_Baarsjes", cityRank: 5, tag: "Amsterdam-West's quiet rise" },
  ]},
  { name: "Bangkok", country: "Thailand", flag: "🇹🇭", neighborhoods: [
    { name: "Ari", wiki: "Ari_(Bangkok)", cityRank: 1, tag: "Bangkok's cool, quiet middle" },
    { name: "Thonglor", wiki: "Thong_Lo", cityRank: 2, tag: "Sukhumvit's nightlife spine" },
    { name: "Yaowarat", wiki: "Yaowarat_Road", cityRank: 3, tag: "The best street food in Southeast Asia" },
    { name: "Ekkamai", wiki: "Ekkamai", cityRank: 4, tag: "Thonglor's slower, hipper neighbor" },
    { name: "Banglamphu", wiki: "Banglamphu", cityRank: 5, tag: "Old Bangkok meets Khao San Road" },
  ]},
  { name: "Istanbul", country: "Turkey", flag: "🇹🇷", neighborhoods: [
    { name: "Karaköy", wiki: "Karaköy", cityRank: 1, tag: "Old port, new creative scene" },
    { name: "Kadıköy", wiki: "Kadıköy", cityRank: 2, tag: "Asian-side Istanbul at its liveliest" },
    { name: "Cihangir", wiki: "Cihangir", cityRank: 3, tag: "The writer's neighborhood of Istanbul" },
    { name: "Balat", wiki: "Balat", cityRank: 4, tag: "Istanbul's most photogenic streets" },
    { name: "Beyoğlu", wiki: "Beyoğlu", cityRank: 5, tag: "İstiklal Caddesi and the city's nightlife" },
  ]},
  { name: "Seoul", country: "South Korea", flag: "🇰🇷", neighborhoods: [
    { name: "Seongsu-dong", wiki: "Seongsu-dong", cityRank: 1, tag: "The Brooklyn of Seoul" },
    { name: "Ikseon-dong", wiki: "Ikseon-dong", cityRank: 2, tag: "Hanok alleys full of hidden cafés" },
    { name: "Hongdae", wiki: "Hongdae", cityRank: 3, tag: "Student energy, indie music, 24-hour bars" },
    { name: "Itaewon", wiki: "Itaewon", cityRank: 4, tag: "Seoul's international melting pot" },
    { name: "Yeonnam-dong", wiki: "Yeonnam-dong", cityRank: 5, tag: "Gyeongui Line Forest, micro-cafés, slow days" },
  ]},
  { name: "Lisbon", country: "Portugal", flag: "🇵🇹", neighborhoods: [
    { name: "Alfama", wiki: "Alfama", cityRank: 1, tag: "Fado, tiles, cobblestones" },
    { name: "Príncipe Real", wiki: "Príncipe_Real", cityRank: 2, tag: "Lisbon's design-conscious heart" },
    { name: "Bairro Alto", wiki: "Bairro_Alto", cityRank: 3, tag: "Lisbon's loudest nights" },
    { name: "LX Factory", wiki: "LX_Factory", cityRank: 4, tag: "Industrial creativity under the bridge" },
    { name: "Graça", wiki: "Graça_(Lisbon)", cityRank: 5, tag: "The best sunset miradouro in Lisbon" },
  ]},
  { name: "Rome", country: "Italy", flag: "🇮🇹", neighborhoods: [
    { name: "Trastevere", wiki: "Trastevere", cityRank: 1, tag: "Rome's most romantic maze" },
    { name: "Monti", wiki: "Monti_(rione_of_Rome)", cityRank: 2, tag: "Bohemian Rome, minutes from the Colosseum" },
    { name: "Testaccio", wiki: "Testaccio", cityRank: 3, tag: "The real home of Roman cooking" },
    { name: "Pigneto", wiki: "Pigneto", cityRank: 4, tag: "Rome's gritty creative frontier" },
    { name: "Prati", wiki: "Prati", cityRank: 5, tag: "Elegant Rome near the Vatican" },
  ]},
  { name: "Los Angeles", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Silver Lake", wiki: "Silver_Lake,_Los_Angeles", cityRank: 1, tag: "LA's indie spirit, bottled and bearded" },
    { name: "Venice", wiki: "Venice,_Los_Angeles", cityRank: 2, tag: "Beachside bohemia and Abbot Kinney" },
    { name: "Highland Park", wiki: "Highland_Park,_Los_Angeles", cityRank: 3, tag: "Northeast LA's hottest corridor" },
    { name: "Echo Park", wiki: "Echo_Park,_Los_Angeles", cityRank: 4, tag: "The lake, the lotus festival, the late-night tacos" },
    { name: "West Adams", wiki: "West_Adams,_Los_Angeles", cityRank: 5, tag: "LA's next-big-thing historic district" },
  ]},
  { name: "Rio de Janeiro", country: "Brazil", flag: "🇧🇷", neighborhoods: [
    { name: "Santa Teresa", wiki: "Santa_Teresa,_Rio_de_Janeiro", cityRank: 1, tag: "Hilltop bohemia overlooking the bay" },
    { name: "Ipanema", wiki: "Ipanema", cityRank: 2, tag: "The most famous beach in the world" },
    { name: "Leblon", wiki: "Leblon", cityRank: 3, tag: "Ipanema's quieter, classier neighbor" },
    { name: "Lapa", wiki: "Lapa,_Rio_de_Janeiro", cityRank: 4, tag: "Samba, arches, Friday night" },
    { name: "Botafogo", wiki: "Botafogo", cityRank: 5, tag: "Rio's new creative hub" },
  ]},
  { name: "Copenhagen", country: "Denmark", flag: "🇩🇰", neighborhoods: [
    { name: "Nørrebro", wiki: "Nørrebro", cityRank: 1, tag: "Copenhagen's most cosmopolitan district" },
    { name: "Vesterbro", wiki: "Vesterbro", cityRank: 2, tag: "The Meatpacking District, Copenhagen-style" },
    { name: "Christianshavn", wiki: "Christianshavn", cityRank: 3, tag: "Canals, houseboats, free-state Christiania" },
    { name: "Refshaleøen", wiki: "Refshaleøen", cityRank: 4, tag: "Copenhagen's waterfront future" },
    { name: "Østerbro", wiki: "Østerbro", cityRank: 5, tag: "Family Copenhagen, at its most liveable" },
  ]},
  { name: "Toronto", country: "Canada", flag: "🇨🇦", neighborhoods: [
    { name: "Kensington Market", wiki: "Kensington_Market", cityRank: 1, tag: "Toronto's most multicultural block" },
    { name: "Queen West", wiki: "Queen_Street_West", cityRank: 2, tag: "Toronto's most famous art-and-fashion strip" },
    { name: "Leslieville", wiki: "Leslieville", cityRank: 3, tag: "Toronto's east-end brunch champion" },
    { name: "The Annex", wiki: "The_Annex", cityRank: 4, tag: "Toronto's literary, academic heart" },
    { name: "Distillery District", wiki: "Distillery_District", cityRank: 5, tag: "Victorian industrial beauty, restored" },
  ]},

  // ── Expansion batch ──
  { name: "Chicago", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Wicker Park", wiki: "Wicker_Park,_Chicago", cityRank: 1, tag: "Chicago's creative West Side" },
    { name: "Logan Square", wiki: "Logan_Square,_Chicago", cityRank: 2, tag: "Boulevards, bungalows and killer bars" },
    { name: "Pilsen", wiki: "Pilsen,_Chicago", cityRank: 3, tag: "Mexican heritage, murals and mercados" },
    { name: "Hyde Park", wiki: "Hyde_Park,_Chicago", cityRank: 4, tag: "University town meets lakefront" },
    { name: "West Loop", wiki: "Near_West_Side,_Chicago", cityRank: 5, tag: "Chicago's restaurant powerhouse" },
  ]},
  { name: "San Francisco", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Mission District", wiki: "Mission_District,_San_Francisco", cityRank: 1, tag: "Murals, taquerias and fog-free sun" },
    { name: "Haight-Ashbury", wiki: "Haight-Ashbury", cityRank: 2, tag: "Where the Summer of Love happened" },
    { name: "North Beach", wiki: "North_Beach,_San_Francisco", cityRank: 3, tag: "SF's Little Italy and Beat home" },
    { name: "Castro District", wiki: "Castro_District,_San_Francisco", cityRank: 4, tag: "The heart of LGBTQ+ America" },
    { name: "Hayes Valley", wiki: "Hayes_Valley,_San_Francisco", cityRank: 5, tag: "Boutique SF at its most stylish" },
  ]},
  { name: "Boston", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Back Bay", wiki: "Back_Bay,_Boston", cityRank: 1, tag: "Brownstones, boutiques and the Charles" },
    { name: "North End", wiki: "North_End,_Boston", cityRank: 2, tag: "Boston's Little Italy" },
    { name: "Beacon Hill", wiki: "Beacon_Hill,_Boston", cityRank: 3, tag: "Gas lamps and cobblestones" },
    { name: "South End", wiki: "South_End,_Boston", cityRank: 4, tag: "Victorian rowhouses and restaurant row" },
    { name: "Cambridge", wiki: "Cambridge,_Massachusetts", cityRank: 5, tag: "Harvard, MIT and the best bookshops in New England" },
  ]},
  { name: "Miami", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Wynwood", wiki: "Wynwood", cityRank: 1, tag: "The street-art capital of the Americas" },
    { name: "Little Havana", wiki: "Little_Havana", cityRank: 2, tag: "Cuban cafés and Calle Ocho" },
    { name: "Design District", wiki: "Miami_Design_District", cityRank: 3, tag: "Luxury shopping, world-class architecture" },
    { name: "South Beach", wiki: "South_Beach", cityRank: 4, tag: "Art deco and ocean drive glamour" },
    { name: "Coconut Grove", wiki: "Coconut_Grove", cityRank: 5, tag: "Miami's leafy, bohemian corner" },
  ]},
  { name: "New Orleans", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "French Quarter", wiki: "French_Quarter", cityRank: 1, tag: "The beating heart of NOLA" },
    { name: "Marigny", wiki: "Faubourg_Marigny", cityRank: 2, tag: "Frenchmen Street and the real jazz" },
    { name: "Bywater", wiki: "Bywater,_New_Orleans", cityRank: 3, tag: "Colorful shotgun houses and creative energy" },
    { name: "Garden District", wiki: "Garden_District,_New_Orleans", cityRank: 4, tag: "Antebellum mansions and oak-lined streets" },
    { name: "Tremé", wiki: "Tremé", cityRank: 5, tag: "The oldest Black neighborhood in America" },
  ]},
  { name: "Washington", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Georgetown", wiki: "Georgetown_(Washington,_D.C.)", cityRank: 1, tag: "DC's prettiest, oldest district" },
    { name: "Dupont Circle", wiki: "Dupont_Circle", cityRank: 2, tag: "Embassies, bookshops and brunch" },
    { name: "Adams Morgan", wiki: "Adams_Morgan", cityRank: 3, tag: "DC's most international nightlife" },
    { name: "Capitol Hill", wiki: "Capitol_Hill", cityRank: 4, tag: "Where politics meets rowhouses" },
    { name: "Shaw", wiki: "Shaw_(Washington,_D.C.)", cityRank: 5, tag: "DC's cultural renaissance" },
  ]},
  { name: "Seattle", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "Capitol Hill", wiki: "Capitol_Hill,_Seattle", cityRank: 1, tag: "Seattle's nightlife and queer heart" },
    { name: "Ballard", wiki: "Ballard,_Seattle", cityRank: 2, tag: "Scandinavian heritage and the Sunday market" },
    { name: "Pike Place", wiki: "Pike_Place_Market", cityRank: 3, tag: "The world-famous waterfront market" },
    { name: "Fremont", wiki: "Fremont,_Seattle", cityRank: 4, tag: "The self-declared center of the universe" },
    { name: "Georgetown", wiki: "Georgetown,_Seattle", cityRank: 5, tag: "Seattle's industrial-artist frontier" },
  ]},
  { name: "Austin", country: "United States", flag: "🇺🇸", neighborhoods: [
    { name: "South Congress", wiki: "South_Congress,_Austin,_Texas", cityRank: 1, tag: "SoCo vintage and live music" },
    { name: "East Austin", wiki: "East_Austin,_Texas", cityRank: 2, tag: "Austin's most creative east side" },
    { name: "Downtown", wiki: "Downtown_Austin", cityRank: 3, tag: "Sixth Street and the live music capital" },
    { name: "Zilker", wiki: "Zilker,_Austin,_Texas", cityRank: 4, tag: "Barton Springs and ACL Festival" },
    { name: "Hyde Park", wiki: "Hyde_Park,_Austin,_Texas", cityRank: 5, tag: "Austin's leafy, historic core" },
  ]},
  { name: "Madrid", country: "Spain", flag: "🇪🇸", neighborhoods: [
    { name: "Malasaña", wiki: "Malasaña", cityRank: 1, tag: "Madrid's hip, independent heart" },
    { name: "La Latina", wiki: "La_Latina,_Madrid", cityRank: 2, tag: "Tapas crawls and Sunday vermouth" },
    { name: "Chueca", wiki: "Chueca", cityRank: 3, tag: "Madrid's LGBTQ+ and shopping district" },
    { name: "Salamanca", wiki: "Salamanca_(Madrid)", cityRank: 4, tag: "Madrid at its most elegant" },
    { name: "Lavapiés", wiki: "Lavapiés", cityRank: 5, tag: "The city's most multicultural maze" },
  ]},
  { name: "Milan", country: "Italy", flag: "🇮🇹", neighborhoods: [
    { name: "Brera", wiki: "Brera_(district_of_Milan)", cityRank: 1, tag: "Milan's artistic quarter" },
    { name: "Navigli", wiki: "Navigli", cityRank: 2, tag: "Canals, aperitivo and late nights" },
    { name: "Porta Nuova", wiki: "Porta_Nuova_(Milan)", cityRank: 3, tag: "Milan's sleek new skyline" },
    { name: "Isola", wiki: "Isola_(Milan)", cityRank: 4, tag: "Industrial-chic and local bars" },
    { name: "Porta Ticinese", wiki: "Porta_Ticinese", cityRank: 5, tag: "Medieval arches and Darsena nights" },
  ]},
  { name: "Vienna", country: "Austria", flag: "🇦🇹", neighborhoods: [
    { name: "Leopoldstadt", wiki: "Leopoldstadt", cityRank: 1, tag: "Vienna's Jewish heart reborn" },
    { name: "Neubau", wiki: "Neubau_(Vienna)", cityRank: 2, tag: "Vienna's coolest shopping streets" },
    { name: "Mariahilf", wiki: "Mariahilf", cityRank: 3, tag: "Vienna at its most shoppable" },
    { name: "Karmeliterviertel", wiki: "Karmeliterviertel", cityRank: 4, tag: "Markets, cafés and canal walks" },
    { name: "Innere Stadt", wiki: "Innere_Stadt", cityRank: 5, tag: "Imperial Vienna, the old town" },
  ]},
  { name: "Prague", country: "Czechia", flag: "🇨🇿", neighborhoods: [
    { name: "Žižkov", wiki: "Žižkov", cityRank: 1, tag: "Prague's bohemian pub capital" },
    { name: "Vinohrady", wiki: "Vinohrady", cityRank: 2, tag: "Leafy parks, cafés and Art Nouveau" },
    { name: "Malá Strana", wiki: "Malá_Strana", cityRank: 3, tag: "Baroque Prague under the castle" },
    { name: "Karlín", wiki: "Karlín_(Prague)", cityRank: 4, tag: "Prague's revived industrial district" },
    { name: "Staré Město", wiki: "Staré_Město_(Prague)", cityRank: 5, tag: "The astronomical clock and Old Town Square" },
  ]},
  { name: "Budapest", country: "Hungary", flag: "🇭🇺", neighborhoods: [
    { name: "Jewish Quarter", wiki: "Jewish_quarter_of_Budapest", cityRank: 1, tag: "Ruin bars and the Dohány Synagogue" },
    { name: "Buda Castle", wiki: "Buda_Castle", cityRank: 2, tag: "UNESCO-listed Baroque Budapest" },
    { name: "Ferencváros", wiki: "Ferencváros", cityRank: 3, tag: "Budapest's rising cultural district" },
    { name: "Erzsébetváros", wiki: "Erzsébetváros", cityRank: 4, tag: "The beating nightlife heart of Pest" },
    { name: "Újbuda", wiki: "Újbuda", cityRank: 5, tag: "Student Budapest on the Buda side" },
  ]},
  { name: "Stockholm", country: "Sweden", flag: "🇸🇪", neighborhoods: [
    { name: "Södermalm", wiki: "Södermalm", cityRank: 1, tag: "Stockholm's hippest island" },
    { name: "Gamla Stan", wiki: "Gamla_stan", cityRank: 2, tag: "The medieval old town" },
    { name: "Östermalm", wiki: "Östermalm", cityRank: 3, tag: "Stockholm at its most luxurious" },
    { name: "Vasastan", wiki: "Vasastan,_Stockholm", cityRank: 4, tag: "Leafy, literary Stockholm" },
    { name: "Kungsholmen", wiki: "Kungsholmen", cityRank: 5, tag: "Waterfront living, quieter side" },
  ]},
  { name: "Dublin", country: "Ireland", flag: "🇮🇪", neighborhoods: [
    { name: "Temple Bar", wiki: "Temple_Bar,_Dublin", cityRank: 1, tag: "Dublin's famous pub quarter" },
    { name: "Portobello", wiki: "Portobello,_Dublin", cityRank: 2, tag: "Canal-side cafés and Little Jerusalem" },
    { name: "Smithfield", wiki: "Smithfield,_Dublin", cityRank: 3, tag: "The old distillery district, rebuilt" },
    { name: "Stoneybatter", wiki: "Stoneybatter", cityRank: 4, tag: "Dublin's quirkiest village" },
    { name: "Ranelagh", wiki: "Ranelagh", cityRank: 5, tag: "Genteel south Dublin" },
  ]},
  { name: "Edinburgh", country: "United Kingdom", flag: "🇬🇧", neighborhoods: [
    { name: "Old Town", wiki: "Old_Town,_Edinburgh", cityRank: 1, tag: "The Royal Mile and the Castle" },
    { name: "Stockbridge", wiki: "Stockbridge,_Edinburgh", cityRank: 2, tag: "Village charm in the city" },
    { name: "Leith", wiki: "Leith", cityRank: 3, tag: "Edinburgh's reborn waterfront" },
    { name: "New Town", wiki: "New_Town,_Edinburgh", cityRank: 4, tag: "Georgian elegance, UNESCO-listed" },
    { name: "Bruntsfield", wiki: "Bruntsfield", cityRank: 5, tag: "Independent shops and the Meadows" },
  ]},
  { name: "Athens", country: "Greece", flag: "🇬🇷", neighborhoods: [
    { name: "Plaka", wiki: "Plaka", cityRank: 1, tag: "Athens under the Acropolis" },
    { name: "Psyri", wiki: "Psyri", cityRank: 2, tag: "The nightlife heart of old Athens" },
    { name: "Koukaki", wiki: "Koukaki", cityRank: 3, tag: "Athens' most liveable corner" },
    { name: "Exarcheia", wiki: "Exarcheia", cityRank: 4, tag: "Athens at its most political" },
    { name: "Monastiraki", wiki: "Monastiraki", cityRank: 5, tag: "Flea markets and ancient views" },
  ]},
  { name: "Munich", country: "Germany", flag: "🇩🇪", neighborhoods: [
    { name: "Schwabing", wiki: "Schwabing", cityRank: 1, tag: "Munich's bohemian old neighborhood" },
    { name: "Glockenbachviertel", wiki: "Glockenbachviertel", cityRank: 2, tag: "Munich's queer and creative quarter" },
    { name: "Haidhausen", wiki: "Haidhausen", cityRank: 3, tag: "Munich's quiet French corner" },
    { name: "Maxvorstadt", wiki: "Maxvorstadt", cityRank: 4, tag: "Museums, university and coffee" },
    { name: "Westend", wiki: "Westend,_Munich", cityRank: 5, tag: "Multicultural Munich" },
  ]},
  { name: "Hamburg", country: "Germany", flag: "🇩🇪", neighborhoods: [
    { name: "St. Pauli", wiki: "St._Pauli", cityRank: 1, tag: "The Reeperbahn and Hamburg's wild side" },
    { name: "Sternschanze", wiki: "Sternschanze", cityRank: 2, tag: "Hamburg's alternative heart" },
    { name: "Altona", wiki: "Altona,_Hamburg", cityRank: 3, tag: "Fish market and harbor views" },
    { name: "HafenCity", wiki: "HafenCity", cityRank: 4, tag: "Europe's biggest waterfront project" },
    { name: "Eppendorf", wiki: "Eppendorf,_Hamburg", cityRank: 5, tag: "Elegant Hamburg" },
  ]},
  { name: "Hong Kong", country: "Hong Kong", flag: "🇭🇰", neighborhoods: [
    { name: "Sheung Wan", wiki: "Sheung_Wan", cityRank: 1, tag: "Dried seafood meets third-wave coffee" },
    { name: "Central", wiki: "Central,_Hong_Kong", cityRank: 2, tag: "The financial and colonial heart" },
    { name: "Mong Kok", wiki: "Mong_Kok", cityRank: 3, tag: "Neon signs and the densest place on Earth" },
    { name: "Causeway Bay", wiki: "Causeway_Bay", cityRank: 4, tag: "Hong Kong's shopping epicenter" },
    { name: "Sai Ying Pun", wiki: "Sai_Ying_Pun", cityRank: 5, tag: "Gentrifying, hilly and fascinating" },
  ]},
  { name: "Mumbai", country: "India", flag: "🇮🇳", neighborhoods: [
    { name: "Bandra", wiki: "Bandra", cityRank: 1, tag: "Mumbai's creative Bollywood enclave" },
    { name: "Colaba", wiki: "Colaba", cityRank: 2, tag: "Colonial Mumbai by the sea" },
    { name: "Fort", wiki: "Fort,_Mumbai", cityRank: 3, tag: "Victorian Gothic and Gateway of India" },
    { name: "Lower Parel", wiki: "Lower_Parel", cityRank: 4, tag: "Mill-to-mall Mumbai" },
    { name: "Juhu", wiki: "Juhu", cityRank: 5, tag: "Beachfront Bollywood" },
  ]},
  { name: "Delhi", country: "India", flag: "🇮🇳", neighborhoods: [
    { name: "Hauz Khas Village", wiki: "Hauz_Khas", cityRank: 1, tag: "Medieval ruins and rooftop bars" },
    { name: "Connaught Place", wiki: "Connaught_Place,_New_Delhi", cityRank: 2, tag: "Delhi's colonial-era circle" },
    { name: "Chandni Chowk", wiki: "Chandni_Chowk", cityRank: 3, tag: "Old Delhi's lively bazaar" },
    { name: "Khan Market", wiki: "Khan_Market", cityRank: 4, tag: "Delhi's smartest shopping" },
    { name: "Nizamuddin", wiki: "Nizamuddin_West", cityRank: 5, tag: "Sufi shrines and Mughal tombs" },
  ]},
  { name: "Shanghai", country: "China", flag: "🇨🇳", neighborhoods: [
    { name: "French Concession", wiki: "Shanghai_French_Concession", cityRank: 1, tag: "Plane trees and art deco shikumen" },
    { name: "Xintiandi", wiki: "Xintiandi", cityRank: 2, tag: "Shanghai's stylish reborn lanes" },
    { name: "Tianzifang", wiki: "Tianzifang", cityRank: 3, tag: "Arts and craft alleys" },
    { name: "The Bund", wiki: "The_Bund", cityRank: 4, tag: "Colonial waterfront, Pudong skyline" },
    { name: "Jing'an", wiki: "Jing'an_District", cityRank: 5, tag: "Shanghai's smart commercial heart" },
  ]},
  { name: "Taipei", country: "Taiwan", flag: "🇹🇼", neighborhoods: [
    { name: "Ximending", wiki: "Ximending", cityRank: 1, tag: "Taipei's youth culture capital" },
    { name: "Da'an", wiki: "Da'an_District,_Taipei", cityRank: 2, tag: "Cafés, night markets, shopping" },
    { name: "Datong", wiki: "Datong_District,_Taipei", cityRank: 3, tag: "Old Taipei, Dihua Street" },
    { name: "Xinyi", wiki: "Xinyi_District,_Taipei", cityRank: 4, tag: "Taipei 101 and glossy shopping" },
    { name: "Zhongshan", wiki: "Zhongshan_District,_Taipei", cityRank: 5, tag: "Japanese colonial echoes" },
  ]},
  { name: "Kuala Lumpur", country: "Malaysia", flag: "🇲🇾", neighborhoods: [
    { name: "Bangsar", wiki: "Bangsar", cityRank: 1, tag: "KL's trendiest dining district" },
    { name: "Bukit Bintang", wiki: "Bukit_Bintang", cityRank: 2, tag: "The shopping and nightlife core" },
    { name: "Chinatown", wiki: "Petaling_Street", cityRank: 3, tag: "KL's lively old core" },
    { name: "Brickfields", wiki: "Brickfields", cityRank: 4, tag: "KL's Little India" },
    { name: "Mont Kiara", wiki: "Mont_Kiara", cityRank: 5, tag: "Expat KL, at ease" },
  ]},
  { name: "Jakarta", country: "Indonesia", flag: "🇮🇩", neighborhoods: [
    { name: "Menteng", wiki: "Menteng", cityRank: 1, tag: "Jakarta's leafy, diplomatic heart" },
    { name: "Kemang", wiki: "Kemang,_Jakarta", cityRank: 2, tag: "Jakarta's bar and café village" },
    { name: "Kota Tua", wiki: "Kota_Tua_Jakarta", cityRank: 3, tag: "Jakarta's colonial old town" },
    { name: "Kebayoran Baru", wiki: "Kebayoran_Baru", cityRank: 4, tag: "Jakarta's elegant modern quarter" },
    { name: "Kelapa Gading", wiki: "Kelapa_Gading", cityRank: 5, tag: "Jakarta's shopping and food capital" },
  ]},
  { name: "Osaka", country: "Japan", flag: "🇯🇵", neighborhoods: [
    { name: "Namba", wiki: "Namba", cityRank: 1, tag: "Dotonbori and the neon canal" },
    { name: "Umeda", wiki: "Umeda", cityRank: 2, tag: "Osaka's sky-high retail core" },
    { name: "Shinsekai", wiki: "Shinsekai", cityRank: 3, tag: "Retro Osaka, Tsutenkaku Tower" },
    { name: "Amerikamura", wiki: "Amerikamura", cityRank: 4, tag: "Osaka's youth and vintage hub" },
    { name: "Tenma", wiki: "Tenma,_Osaka", cityRank: 5, tag: "Long arcades and local izakaya" },
  ]},
  { name: "Kyoto", country: "Japan", flag: "🇯🇵", neighborhoods: [
    { name: "Gion", wiki: "Gion", cityRank: 1, tag: "Kyoto's geisha district" },
    { name: "Arashiyama", wiki: "Arashiyama", cityRank: 2, tag: "Bamboo groves and temple mountains" },
    { name: "Higashiyama", wiki: "Higashiyama-ku,_Kyoto", cityRank: 3, tag: "Temples, teahouses and traditional lanes" },
    { name: "Pontocho", wiki: "Pontocho", cityRank: 4, tag: "Kyoto's riverside dining alley" },
    { name: "Nishijin", wiki: "Nishijin", cityRank: 5, tag: "The traditional textile quarter" },
  ]},
  { name: "Dubai", country: "United Arab Emirates", flag: "🇦🇪", neighborhoods: [
    { name: "Downtown Dubai", wiki: "Downtown_Dubai", cityRank: 1, tag: "Burj Khalifa and the Dubai Mall" },
    { name: "Dubai Marina", wiki: "Dubai_Marina", cityRank: 2, tag: "Skyscrapers on the water" },
    { name: "Jumeirah", wiki: "Jumeirah", cityRank: 3, tag: "Beachside Dubai at its most polished" },
    { name: "Al Fahidi", wiki: "Al_Fahidi_Historical_Neighbourhood", cityRank: 4, tag: "Old Dubai, restored" },
    { name: "Deira", wiki: "Deira", cityRank: 5, tag: "Traditional souks and abras" },
  ]},
  { name: "Cairo", country: "Egypt", flag: "🇪🇬", neighborhoods: [
    { name: "Zamalek", wiki: "Zamalek", cityRank: 1, tag: "Cairo's leafy island district" },
    { name: "Islamic Cairo", wiki: "Islamic_Cairo", cityRank: 2, tag: "Medieval mosques and Khan el-Khalili" },
    { name: "Maadi", wiki: "Maadi", cityRank: 3, tag: "Leafy Cairo, expat-loved" },
    { name: "Heliopolis", wiki: "Heliopolis,_Cairo", cityRank: 4, tag: "Belle Époque planned Cairo" },
    { name: "Downtown Cairo", wiki: "Downtown_Cairo", cityRank: 5, tag: "Cairo's faded 20th-century grandeur" },
  ]},
  { name: "Cape Town", country: "South Africa", flag: "🇿🇦", neighborhoods: [
    { name: "Bo-Kaap", wiki: "Bo-Kaap", cityRank: 1, tag: "Rainbow houses and Cape Malay culture" },
    { name: "Woodstock", wiki: "Woodstock,_Cape_Town", cityRank: 2, tag: "Cape Town's creative hub" },
    { name: "V&A Waterfront", wiki: "Victoria_%26_Alfred_Waterfront", cityRank: 3, tag: "Working harbor, world-class shopping" },
    { name: "Sea Point", wiki: "Sea_Point", cityRank: 4, tag: "The promenade and Atlantic sunsets" },
    { name: "De Waterkant", wiki: "De_Waterkant", cityRank: 5, tag: "Cape Town's pink-house village" },
  ]},
  { name: "Marrakech", country: "Morocco", flag: "🇲🇦", neighborhoods: [
    { name: "Medina", wiki: "Medina_of_Marrakesh", cityRank: 1, tag: "UNESCO-listed heart of Marrakech" },
    { name: "Gueliz", wiki: "Gueliz", cityRank: 2, tag: "Modern Marrakech, French legacy" },
    { name: "Hivernage", wiki: "Hivernage", cityRank: 3, tag: "Gardens, hotels and nightlife" },
    { name: "Kasbah", wiki: "Kasbah_of_Marrakesh", cityRank: 4, tag: "Royal quarter and Saadian tombs" },
    { name: "Mellah", wiki: "Mellah_of_Marrakesh", cityRank: 5, tag: "The historic Jewish quarter" },
  ]},
  { name: "Tel Aviv", country: "Israel", flag: "🇮🇱", neighborhoods: [
    { name: "Neve Tzedek", wiki: "Neve_Tzedek", cityRank: 1, tag: "Tel Aviv's oldest neighborhood" },
    { name: "Florentin", wiki: "Florentin,_Tel_Aviv", cityRank: 2, tag: "Street art and the nightlife frontier" },
    { name: "Jaffa", wiki: "Jaffa", cityRank: 3, tag: "Ancient port, stone alleys" },
    { name: "Rothschild", wiki: "Rothschild_Boulevard", cityRank: 4, tag: "Bauhaus boulevard and café culture" },
    { name: "Kerem HaTeimanim", wiki: "Kerem_HaTeimanim", cityRank: 5, tag: "Yemenite food and the Carmel Market" },
  ]},
  { name: "São Paulo", country: "Brazil", flag: "🇧🇷", neighborhoods: [
    { name: "Vila Madalena", wiki: "Vila_Madalena", cityRank: 1, tag: "Street art, bars and bohemia" },
    { name: "Jardins", wiki: "Jardim_América,_São_Paulo", cityRank: 2, tag: "São Paulo at its most elegant" },
    { name: "Pinheiros", wiki: "Pinheiros", cityRank: 3, tag: "SP's design and food capital" },
    { name: "Liberdade", wiki: "Liberdade_(district_of_São_Paulo)", cityRank: 4, tag: "The largest Japanese district outside Japan" },
    { name: "Consolação", wiki: "Consolação_(district_of_São_Paulo)", cityRank: 5, tag: "Avenida Paulista and SP's nightlife" },
  ]},
  { name: "Lima", country: "Peru", flag: "🇵🇪", neighborhoods: [
    { name: "Miraflores", wiki: "Miraflores_District,_Lima", cityRank: 1, tag: "Lima's cliffside modern heart" },
    { name: "Barranco", wiki: "Barranco_District", cityRank: 2, tag: "Lima's bohemian, arty corner" },
    { name: "San Isidro", wiki: "San_Isidro_District,_Lima", cityRank: 3, tag: "Lima's leafy business district" },
    { name: "Centro Histórico", wiki: "Historic_Centre_of_Lima", cityRank: 4, tag: "Colonial Lima, UNESCO-listed" },
    { name: "Chorrillos", wiki: "Chorrillos_District,_Lima", cityRank: 5, tag: "Lima's quieter seaside" },
  ]},
  { name: "Bogotá", country: "Colombia", flag: "🇨🇴", neighborhoods: [
    { name: "La Candelaria", wiki: "La_Candelaria", cityRank: 1, tag: "Colonial Bogotá and street art" },
    { name: "Chapinero", wiki: "Chapinero", cityRank: 2, tag: "Bogotá's creative, diverse heart" },
    { name: "Usaquén", wiki: "Usaquén", cityRank: 3, tag: "Sunday flea market and cobblestone calm" },
    { name: "Zona Rosa", wiki: "Zona_Rosa,_Bogotá", cityRank: 4, tag: "Bogotá's upscale nightlife" },
    { name: "Teusaquillo", wiki: "Teusaquillo", cityRank: 5, tag: "Leafy residential Bogotá" },
  ]},
  { name: "Santiago", country: "Chile", flag: "🇨🇱", neighborhoods: [
    { name: "Bellavista", wiki: "Bellavista,_Santiago", cityRank: 1, tag: "Santiago's bohemian quarter" },
    { name: "Lastarria", wiki: "Lastarria", cityRank: 2, tag: "Cafés, galleries and museums" },
    { name: "Barrio Italia", wiki: "Barrio_Italia", cityRank: 3, tag: "Antiques and design workshops" },
    { name: "Providencia", wiki: "Providencia,_Chile", cityRank: 4, tag: "Santiago's liveable modern heart" },
    { name: "Las Condes", wiki: "Las_Condes", cityRank: 5, tag: "Santiago at its most polished" },
  ]},
  { name: "Havana", country: "Cuba", flag: "🇨🇺", neighborhoods: [
    { name: "Old Havana", wiki: "Old_Havana", cityRank: 1, tag: "UNESCO-listed colonial heart" },
    { name: "Vedado", wiki: "Vedado", cityRank: 2, tag: "Havana's 20th-century grandeur" },
    { name: "Miramar", wiki: "Miramar,_Havana", cityRank: 3, tag: "Leafy, diplomatic Havana" },
    { name: "Centro Habana", wiki: "Centro_Habana", cityRank: 4, tag: "Faded, crowded, real Havana" },
    { name: "Habana del Este", wiki: "Habana_del_Este", cityRank: 5, tag: "Havana's beach side" },
  ]},
  { name: "Sydney", country: "Australia", flag: "🇦🇺", neighborhoods: [
    { name: "Surry Hills", wiki: "Surry_Hills,_New_South_Wales", cityRank: 1, tag: "Sydney's cool creative core" },
    { name: "Newtown", wiki: "Newtown,_New_South_Wales", cityRank: 2, tag: "King Street and alternative Sydney" },
    { name: "Bondi", wiki: "Bondi_Beach", cityRank: 3, tag: "Australia's most famous beach" },
    { name: "Paddington", wiki: "Paddington,_New_South_Wales", cityRank: 4, tag: "Terrace houses and Oxford Street" },
    { name: "Darlinghurst", wiki: "Darlinghurst,_New_South_Wales", cityRank: 5, tag: "Sydney's nightlife and pride" },
  ]},
  { name: "Kraków", country: "Poland", flag: "🇵🇱", neighborhoods: [
    { name: "Kazimierz", wiki: "Kazimierz", cityRank: 1, tag: "Historic Jewish quarter, reborn" },
    { name: "Stare Miasto", wiki: "Stare_Miasto,_Kraków", cityRank: 2, tag: "UNESCO medieval old town" },
    { name: "Podgórze", wiki: "Podgórze", cityRank: 3, tag: "Across the Vistula, Schindler's factory" },
    { name: "Nowa Huta", wiki: "Nowa_Huta", cityRank: 4, tag: "Kraków's socialist planned city" },
    { name: "Zwierzyniec", wiki: "Zwierzyniec_(Kraków)", cityRank: 5, tag: "Green Kraków, mounds and monasteries" },
  ]},
  { name: "Porto", country: "Portugal", flag: "🇵🇹", neighborhoods: [
    { name: "Ribeira", wiki: "Ribeira,_Porto", cityRank: 1, tag: "Porto's UNESCO riverfront" },
    { name: "Foz do Douro", wiki: "Foz_do_Douro", cityRank: 2, tag: "Where the Douro meets the Atlantic" },
    { name: "Bolhão", wiki: "Mercado_do_Bolhão", cityRank: 3, tag: "The iconic Porto market and quarter" },
    { name: "Cedofeita", wiki: "Cedofeita", cityRank: 4, tag: "Porto's arty, independent side" },
    { name: "Miragaia", wiki: "Miragaia_(Porto)", cityRank: 5, tag: "Quiet riverside Porto" },
  ]},
  { name: "Valencia", country: "Spain", flag: "🇪🇸", neighborhoods: [
    { name: "El Carmen", wiki: "El_Carmen,_Valencia", cityRank: 1, tag: "Old Valencia's medieval heart" },
    { name: "Ruzafa", wiki: "Russafa", cityRank: 2, tag: "Valencia's hippest barrio" },
    { name: "El Cabanyal", wiki: "El_Cabanyal", cityRank: 3, tag: "Valencia's fishermen's quarter" },
    { name: "Ciutat Vella", wiki: "Ciutat_Vella", cityRank: 4, tag: "Old Town Valencia" },
    { name: "Benimaclet", wiki: "Benimaclet", cityRank: 5, tag: "Valencia's student village" },
  ]},
  { name: "Marseille", country: "France", flag: "🇫🇷", neighborhoods: [
    { name: "Le Panier", wiki: "Le_Panier", cityRank: 1, tag: "Marseille's oldest quarter" },
    { name: "Cours Julien", wiki: "Cours_Julien", cityRank: 2, tag: "Street art and creative nights" },
    { name: "La Joliette", wiki: "La_Joliette", cityRank: 3, tag: "Marseille's reborn waterfront" },
    { name: "Vieux-Port", wiki: "Vieux-Port_of_Marseille", cityRank: 4, tag: "The ancient harbor, still working" },
    { name: "Noailles", wiki: "Noailles,_Marseille", cityRank: 5, tag: "Marseille's most multicultural market" },
  ]},
];
